In [5]:
import pandas as pd
import glob
import os

cgm_5files_mv = glob.glob("C:/python_hackathon/HUPA-UC Diabetes Dataset-20250820T010637Z-1-001/HUPA-UC Diabetes Dataset/CGM5_MV/*.csv")

dfs = []
for file in cgm_5files_mv :
    if os.path.isfile(file):
        df = pd.read_csv(file, sep=';')
        df['patient_id'] = os.path.basename(file).replace('.csv', '')
        dfs.append(df)


df_CGM5_MV= pd.concat(dfs, ignore_index=True)

# Move patient_id to first column
cols = ['patient_id'] + [col for col in df_CGM5_MV.columns if col != 'patient_id']
df_CGM5_MV = df_CGM5_MV[cols]

df_CGM5_MV

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.35950,82.322835,34.0,0.091667,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.72800,83.740157,0.0,0.091667,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.74950,80.525180,0.0,0.091667,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.35950,89.129032,20.0,0.091667,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15200,92.495652,0.0,0.075000,0.0,0.0
...,...,...,...,...,...,...,...,...,...
18084,HUPA0005P,2018-07-22T23:25:00,76.5,4.26350,83.140496,0.0,0.075000,0.0,0.0
18085,HUPA0005P,2018-07-22T23:30:00,57.0,4.26350,83.041667,0.0,0.075000,0.0,0.0
18086,HUPA0005P,2018-07-22T23:35:00,53.0,4.26350,79.071429,0.0,0.075000,0.0,0.0
18087,HUPA0005P,2018-07-22T23:40:00,49.0,4.26350,82.910714,0.0,0.075000,0.0,0.0
18088,HUPA0005P,2018-07-22T23:45:00,45.0,5.54255,82.250000,6.0,0.075000,0.0,0.0

In [6]:
df_CGM5_MV[df_CGM5_MV.duplicated(subset="patient_id", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="time", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="glucose", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="heart_rate", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="steps", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="basal_rate", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="bolus_volume_delivered", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="carb_input", keep=False)]

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.35950,82.322835,34.0,0.091667,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.72800,83.740157,0.0,0.091667,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.74950,80.525180,0.0,0.091667,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.35950,89.129032,20.0,0.091667,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15200,92.495652,0.0,0.075000,0.0,0.0
...,...,...,...,...,...,...,...,...,...
18084,HUPA0005P,2018-07-22T23:25:00,76.5,4.26350,83.140496,0.0,0.075000,0.0,0.0
18085,HUPA0005P,2018-07-22T23:30:00,57.0,4.26350,83.041667,0.0,0.075000,0.0,0.0
18086,HUPA0005P,2018-07-22T23:35:00,53.0,4.26350,79.071429,0.0,0.075000,0.0,0.0
18087,HUPA0005P,2018-07-22T23:40:00,49.0,4.26350,82.910714,0.0,0.075000,0.0,0.0
18088,HUPA0005P,2018-07-22T23:45:00,45.0,5.54255,82.250000,6.0,0.075000,0.0,0.0

In [7]:
df_CGM5_MV.columns = df_CGM5_MV.columns.str.title()

In [8]:
df_CGM5_MV = df_CGM5_MV.round(2)

In [9]:
df_CGM5_MV.isnull().values.any()

np.False_

In [13]:
df_CGM5_MV[df_CGM5_MV['Glucose'] > 400]

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
2692,HUPA0001P,2018-06-23T03:00:00,401.00,4.03,76.95,0.0,0.05,0.0,0.0
2698,HUPA0001P,2018-06-23T03:30:00,430.00,4.03,73.78,0.0,0.05,0.0,0.0
2701,HUPA0001P,2018-06-23T03:45:00,418.00,4.03,70.07,0.0,0.05,0.0,0.0
2704,HUPA0001P,2018-06-23T04:00:00,430.00,4.03,75.11,0.0,0.05,0.0,0.0
2707,HUPA0001P,2018-06-23T04:15:00,444.00,4.11,76.34,0.0,0.05,0.5,0.0
2710,HUPA0001P,2018-06-23T04:30:00,439.00,11.35,92.42,83.0,0.05,0.0,0.0
2713,HUPA0001P,2018-06-23T04:45:00,429.00,9.98,81.58,101.0,0.05,0.0,0.0
2716,HUPA0001P,2018-06-23T05:00:00,427.00,4.03,66.69,0.0,0.04,0.0,0.0
11264,HUPA0004P,2018-07-10T09:35:00,403.67,12.30,90.00,13.0,0.07,0.0,0.0
11265,HUPA0004P,2018-07-10T09:40:00,407.33,7.91,89.13,0.0,0.07,0.0,0.0
11266,HUPA0004P,2018-07-10T09:45:00,411.00,9.79,87.66,0.0,0.07,0.0,0.0
11267,HUPA0004P,2018-07-10T09:50:00,409.67,9.92,87.41,5.0,0.07,0.0,0.0
11268,HUPA0004P,2018-07-10T09:55:00,408.33,7.78,87.70,0.0,0.07,0.0,0.0
11269,HUPA0004P,2018-07-10T10:00:00,407.00,7.53,89.50,0.0,0.05,0.0,0.0
11270,HUPA0004P,2018-07-10T10:05:00,404.33,13.68,97.20,41.0,0.05,0.0,0.0
11271,HUPA0004P,2018-07-10T10:10:00,401.67,8.03,89.79,0.0,0.05,0.0,0.0
13062,HUPA0004P,2018-07-16T15:25:00,402.00,8.66,74.14,0.0,0.08,0.0,0.0
13063,HUPA0004P,2018-07-16T15:30:00,406.00,10.29,74.13,54.0,0.08,0.0,0.0
13399,HUPA0004P,2018-07-17T19:30:00,403.00,11.30,72.40,11.0,0.11,0.0,0.0

In [14]:
df_CGM5_MV[df_CGM5_MV['Glucose'] < 40]

Empty DataFrame
Columns: [Patient_Id, Time, Glucose, Calories, Heart_Rate, Steps, Basal_Rate, Bolus_Volume_Delivered, Carb_Input]
Index: []

In [15]:
df_CGM5_MV['Glucose_Outlier'] = (df_CGM5_MV['Glucose'] < 40) | (df_CGM5_MV['Glucose'] > 400)

In [16]:
df_CGM5_MV.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input,Glucose_Outlier
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0,False
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0,False
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0,False
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0,False
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0,False

In [20]:
df_CGM5_MV.to_csv("cleaned_CGM5_MV.csv", index=False)

In [21]:
df_CGM5_MV.to_csv(r"C:/python_hackathon/cleaned_CGM5_MV.csv", index=False)