<h2>Merging all the files together</h2>

In [126]:
%cd "H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Final cleaned csv files"

H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Final cleaned csv files

In [5]:
import os
os.getcwd()

'H:\\Numpy Ninja\\Python Hackathon\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Final cleaned csv files'

In [8]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn

In [64]:
df1= pd.read_csv("cleaned_CGM5_MV_Maha_1.csv")
df1.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0

In [71]:
df1.columns = df1.columns.str.replace('_', ' ').str.title().str.replace(' ', '_')
df1.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0

In [73]:
#Save the individual cleaned file to a .csv file

df1.to_csv(
    r"cleaned_CGM5_MV_Maha_1.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [50]:
df1= df1.drop(columns=['Glucose_Outlier'])

In [51]:
df1

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0
...,...,...,...,...,...,...,...,...,...
18084,HUPA0005P,2018-07-22T23:25:00,76.5,4.26,83.14,0.0,0.08,0.0,0.0
18085,HUPA0005P,2018-07-22T23:30:00,57.0,4.26,83.04,0.0,0.08,0.0,0.0
18086,HUPA0005P,2018-07-22T23:35:00,53.0,4.26,79.07,0.0,0.08,0.0,0.0
18087,HUPA0005P,2018-07-22T23:40:00,49.0,4.26,82.91,0.0,0.08,0.0,0.0
18088,HUPA0005P,2018-07-22T23:45:00,45.0,5.54,82.25,6.0,0.08,0.0,0.0

In [65]:
df2= pd.read_csv("CGM5_ABI_cleaned_2.csv")
df2.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA0006P,2018-07-09 15:45:00,109.00,11.24,70.77,0.0,0.08,0.0,0.0
1,HUPA0006P,2018-07-09 15:50:00,107.67,8.11,70.19,5.0,0.08,0.0,0.0
2,HUPA0006P,2018-07-09 15:55:00,106.33,6.49,70.17,0.0,0.08,0.0,0.0
3,HUPA0006P,2018-07-09 16:00:00,105.00,7.07,72.37,0.0,0.06,0.0,0.0
4,HUPA0006P,2018-07-09 16:05:00,122.33,9.62,68.22,6.0,0.06,0.0,10.0

In [72]:
df2.columns = df2.columns.str.replace('_', ' ').str.title().str.replace(' ', '_')
df2.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0006P,2018-07-09 15:45:00,109.00,11.24,70.77,0.0,0.08,0.0,0.0
1,HUPA0006P,2018-07-09 15:50:00,107.67,8.11,70.19,5.0,0.08,0.0,0.0
2,HUPA0006P,2018-07-09 15:55:00,106.33,6.49,70.17,0.0,0.08,0.0,0.0
3,HUPA0006P,2018-07-09 16:00:00,105.00,7.07,72.37,0.0,0.06,0.0,0.0
4,HUPA0006P,2018-07-09 16:05:00,122.33,9.62,68.22,6.0,0.06,0.0,10.0

In [74]:
df2.to_csv(
    r"CGM5_ABI_cleaned_2.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [75]:
df1= pd.read_csv("cleaned_CGM5_MV_Maha_1.csv")
df2= pd.read_csv("CGM5_ABI_cleaned_2.csv")
df1,df2

(      Patient_Id                 Time  Glucose  Calories  Heart_Rate  Steps  \
 0      HUPA0001P  2018-06-13T18:40:00    332.0      6.36       82.32   34.0
 1      HUPA0001P  2018-06-13T18:45:00    326.0      7.73       83.74    0.0
 2      HUPA0001P  2018-06-13T18:50:00    330.0      4.75       80.53    0.0
 3      HUPA0001P  2018-06-13T18:55:00    324.0      6.36       89.13   20.0
 4      HUPA0001P  2018-06-13T19:00:00    306.0      5.15       92.50    0.0
 ...          ...                  ...      ...       ...         ...    ...
 18084  HUPA0005P  2018-07-22T23:25:00     76.5      4.26       83.14    0.0
 18085  HUPA0005P  2018-07-22T23:30:00     57.0      4.26       83.04    0.0
 18086  HUPA0005P  2018-07-22T23:35:00     53.0      4.26       79.07    0.0
 18087  HUPA0005P  2018-07-22T23:40:00     49.0      4.26       82.91    0.0
 18088  HUPA0005P  2018-07-22T23:45:00     45.0      5.54       82.25    6.0

        Basal_Rate  Bolus_Volume_Delivered  Carb_Input
 0            0.09                     0.0         0.0
 1            0.09                     0.0         0.0
 2            0.09                     0.0         0.0
 3            0.09                     0.0         0.0
 4            0.08                     0.0         0.0
 ...           ...                     ...         ...
 18084        0.08                     0.0         0.0
 18085        0.08                     0.0         0.0
 18086        0.08                     0.0         0.0
 18087        0.08                     0.0         0.0
 18088        0.08                     0.0         0.0

 [18089 rows x 9 columns],
       Patient_Id                 Time  Glucose  Calories  Heart_Rate  Steps  \
 0      HUPA0006P  2018-07-09 15:45:00   109.00     11.24       70.77    0.0
 1      HUPA0006P  2018-07-09 15:50:00   107.67      8.11       70.19    5.0
 2      HUPA0006P  2018-07-09 15:55:00   106.33      6.49       70.17    0.0
 3      HUPA0006P  2018-07-09 16:00:00   105.00      7.07       72.37    0.0
 4      HUPA0006P  2018-07-09 16:05:00   122.33      9.62       68.22    6.0
 ...          ...                  ...      ...       ...         ...    ...
 16825  HUPA0018P  2019-07-16 23:25:00   180.33      6.56       85.63    0.0
 16826  HUPA0018P  2019-07-16 23:30:00   188.00      4.95       85.46    0.0
 16827  HUPA0018P  2019-07-16 23:35:00   194.33      5.12       84.33    0.0
 16828  HUPA0018P  2019-07-16 23:40:00   200.67      9.35       85.87    0.0
 16829  HUPA0018P  2019-07-16 23:45:00   207.00      5.39       85.75    0.0

        Basal_Rate  Bolus_Volume_Delivered  Carb_Input
 0            0.08                     0.0         0.0
 1            0.08                     0.0         0.0
 2            0.08                     0.0         0.0
 3            0.06                     0.0         0.0
 4            0.06                     0.0        10.0
 ...           ...                     ...         ...
 16825        0.00                     0.0         0.0
 16826        0.00                     0.0         0.0
 16827        0.00                     0.0         0.0
 16828        0.00                     0.0         0.0
 16829        0.00                     0.0         0.0

 [16830 rows x 9 columns])

<h2> Merging first two files </h2>

In [76]:
dfs=[df1,df2]

In [77]:
merged_df = pd.concat(dfs, ignore_index=True)

In [79]:
merged_df = merged_df.sort_values(by=['Patient_Id', 'Time'])

In [82]:
merged_df.to_csv(r"First two files merged_1.csv", index=False)
print("Saved into one csv file")

Saved into one csv file

In [83]:
df3= pd.read_csv("All_Patients_Merged_Purnima_3.csv")
df3.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0.0,0.0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0.0,0.0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0.0,0.0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0.0,0.0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0.0,0.0,0.0

In [84]:
df3.columns = df3.columns.str.replace('_', ' ').str.title().str.replace(' ', '_')
df3.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0.0,0.0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0.0,0.0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0.0,0.0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0.0,0.0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0.0,0.0,0.0

In [85]:
df3.to_csv(
    r"All_Patients_Merged_Purnima_3.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [97]:
df5= pd.read_csv("First two files merged_1.csv")
df5.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0

<h2> Merging the third file</h2>

In [98]:
dfs1= [df5,df3]

In [99]:
merged_df1 = pd.concat(dfs1, ignore_index=True)

In [89]:
merged_df1 = merged_df1.sort_values(by=['Patient_Id', 'Time'])

In [100]:
merged_df1.to_csv(r"Third file merged.csv", index=False)
print("Saved into one csv file")

Saved into one csv file

<h2> Merging the fourth file </h2>

In [101]:
df4= pd.read_csv("Clean-data-fivefile-Harshali_4.csv")
df4.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0019P,2019-07-03 14:00:00,195.00,6.15,60.17,0,0.07,1.0,1.0
1,HUPA0019P,2019-07-03 14:05:00,193.67,9.75,64.26,20,0.07,0.0,0.0
2,HUPA0019P,2019-07-03 14:10:00,192.33,12.76,75.46,50,0.07,0.0,0.0
3,HUPA0019P,2019-07-03 14:15:00,191.00,14.97,76.36,65,0.07,0.0,0.0
4,HUPA0019P,2019-07-03 14:20:00,192.67,9.28,76.17,13,0.07,0.0,0.0

In [102]:
df6= pd.read_csv("Third file merged.csv")
df6.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0

In [103]:
dfs2= [df6,df4]

In [104]:
merged_df2 = pd.concat(dfs2, ignore_index=True)

In [105]:
merged_df2 = merged_df2.sort_values(by=['Patient_Id', 'Time'])

In [106]:
merged_df2.to_csv(r"Fourth file merged.csv", index=False)
print("Saved into one csv file")

Saved into one csv file

<h2>Merging the fifth file</h2>

In [114]:
df7 = pd.read_csv("Fourth file merged.csv")
df7.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0

In [121]:
df8= pd.read_csv("CleanedData_TM_Teja_5.csv")
df8

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0024P,2020-01-20 11:30:00,87.00,8.19,67.36,20,0.07,0.0,0.0
1,HUPA0024P,2020-01-20 11:35:00,86.00,17.99,75.25,107,0.07,0.0,0.0
2,HUPA0024P,2020-01-20 11:40:00,85.00,17.41,76.78,123,0.07,0.0,0.0
3,HUPA0024P,2020-01-20 11:45:00,84.00,10.38,83.67,30,0.07,0.0,0.0
4,HUPA0024P,2020-01-20 11:50:00,85.33,14.53,80.29,74,0.07,0.0,0.0
...,...,...,...,...,...,...,...,...,...
238716,HUPA0028P,2022-05-18 11:55:00,109.33,10.79,104.17,0,0.00,0.0,0.0
238717,HUPA0028P,2022-05-18 12:00:00,114.00,9.80,103.44,0,0.00,0.0,0.0
238718,HUPA0028P,2022-05-18 12:05:00,118.67,5.67,95.54,0,0.00,0.0,0.0
238719,HUPA0028P,2022-05-18 12:10:00,123.33,5.58,91.38,0,0.00,0.0,0.0
238720,HUPA0028P,2022-05-18 12:15:00,128.00,5.58,99.26,0,0.00,0.0,0.0

In [123]:
dfs3= [df7,df8]

In [124]:
merged_df3 = pd.concat(dfs3, ignore_index=True)

In [125]:
merged_df3.to_csv(r"Fifth file merged.csv", index=False)
print("Saved into one csv file")

Saved into one csv file