DATA CLEANING STEPS: Patient_id: HUPA011P

Get the correct working folder:

In [56]:
%cd "H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Raw files\HUPA-UC Diabetes Dataset"

H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Raw files\HUPA-UC Diabetes Dataset

Check the folder where the files are present:

In [57]:
import os
os.getcwd()

'H:\\Numpy Ninja\\Python Hackathon\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Raw files\\HUPA-UC Diabetes Dataset'

In [ ]:
Fetch the files using Dataframe:

In [58]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn



df_HUPA11 = pd.read_csv(
    "HUPA0011P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)


df_HUPA11

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...
3834,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0
3835,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0
3836,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0
3837,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0
3838,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0

Create a copy of the original dataset:

In [59]:
df_HUPA11Copy= df_HUPA11.copy()
df_HUPA11Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0

Check for the datatypes of the columns and also null values.

In [60]:
df_HUPA11.info()
df_HUPA11.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3839 entries, 0 to 3838
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3839 non-null   datetime64[ns]
 1   glucose                 3839 non-null   float64
 2   calories                3839 non-null   float64
 3   heart_rate              3839 non-null   float64
 4   steps                   3839 non-null   float64
 5   basal_rate              3839 non-null   int64
 6   bolus_volume_delivered  3839 non-null   int64
 7   carb_input              3839 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2)
memory usage: 240.1 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Add a new column called Patient_id.

In [61]:
df_HUPA11["patient_id"] = "HUPA011P"
df_HUPA11

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0,HUPA011P
1,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0,HUPA011P
2,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0,HUPA011P
3,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0,HUPA011P
4,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0,HUPA011P
...,...,...,...,...,...,...,...,...,...
3834,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0,HUPA011P
3835,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0,HUPA011P
3836,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0,HUPA011P
3837,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0,HUPA011P
3838,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0,HUPA011P

Bring the patient_id column to the beginning.

In [62]:
df_HUPA11 = df_HUPA11[["patient_id"] + [col for col in df_HUPA11.columns if col != "patient_id"]]
df_HUPA11

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA011P,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0
3835,HUPA011P,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0
3836,HUPA011P,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0
3837,HUPA011P,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0
3838,HUPA011P,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0

Remove whitespaces in the data

In [63]:
df_HUPA11.columns = df_HUPA11.columns.str.strip()

Capitalize the first letter of each column

In [64]:
df_HUPA11.columns = df_HUPA11.columns.str.capitalize()
df_HUPA11

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0
3835,HUPA011P,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0
3836,HUPA011P,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0
3837,HUPA011P,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0
3838,HUPA011P,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0

Check for duplicate records for the same timestamp

In [66]:
df_HUPA11['Time'].duplicated().sum()

np.int64(0)

In [ ]:
Save the cleaned file as .csv file

Round the float columns to 2 decimal places

In [68]:
float_cols = df_HUPA11.select_dtypes(include=['float64']).columns
df_HUPA11[float_cols] = df_HUPA11[float_cols].round(2)
df_HUPA11.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0,0,0.0

In [ ]:
Save the individual cleaned file to a .csv file

In [69]:
df_HUPA11.to_csv(
    r"H:/Numpy Ninja/Python Hackathon/Team2_ PyQueens_ Python Hackathon _MAY 2026/Team2_ PyQueens_ Python Hackathon _MAY 2026/Cleaned .csv files/HUPA011_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created