In [ ]:
DATA CLEANING STEPS: Patient_id: HUPA011P,HUPA014P,HUPA15P,HUPA16P,HUPA17P

Get the correct working folder:

In [1]:
%cd "H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Raw files\HUPA-UC Diabetes Dataset

H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Raw files\HUPA-UC Diabetes Dataset

Check the folder where the files are present:

In [2]:
import os
os.getcwd()

'H:\\Numpy Ninja\\Python Hackathon\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Raw files\\HUPA-UC Diabetes Dataset'

Fetch the files using Dataframe:

In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn

In [4]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn



df_HUPA11 = pd.read_csv(
    "HUPA0011P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)


df_HUPA11

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...
3834,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0
3835,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0
3836,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0
3837,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0
3838,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0

Create a copy of the original dataset:

In [5]:
df_HUPA11Copy= df_HUPA11.copy()
df_HUPA11Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0

Check for the datatypes of the columns and also null values.

In [6]:
df_HUPA11.info()
df_HUPA11.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3839 entries, 0 to 3838
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3839 non-null   datetime64[ns]
 1   glucose                 3839 non-null   float64
 2   calories                3839 non-null   float64
 3   heart_rate              3839 non-null   float64
 4   steps                   3839 non-null   float64
 5   basal_rate              3839 non-null   int64
 6   bolus_volume_delivered  3839 non-null   int64
 7   carb_input              3839 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2)
memory usage: 240.1 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Add a new column called Patient_id.

In [7]:
df_HUPA11["patient_id"] = "HUPA011P"
df_HUPA11

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0,HUPA011P
1,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0,HUPA011P
2,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0,HUPA011P
3,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0,HUPA011P
4,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0,HUPA011P
...,...,...,...,...,...,...,...,...,...
3834,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0,HUPA011P
3835,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0,HUPA011P
3836,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0,HUPA011P
3837,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0,HUPA011P
3838,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0,HUPA011P

Bring the patient_id column to the beginning.

In [8]:
df_HUPA11 = df_HUPA11[["patient_id"] + [col for col in df_HUPA11.columns if col != "patient_id"]]
df_HUPA11

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA011P,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0
3835,HUPA011P,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0
3836,HUPA011P,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0
3837,HUPA011P,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0
3838,HUPA011P,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0

Remove whitespaces in the data

In [9]:
df_HUPA11.columns = df_HUPA11.columns.str.strip()

Capitalize the first letter of each column

In [10]:
df_HUPA11.columns = df_HUPA11.columns.str.capitalize()
df_HUPA11

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0
3835,HUPA011P,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0
3836,HUPA011P,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0
3837,HUPA011P,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0
3838,HUPA011P,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0

Check for duplicate records for the same timestamp

In [11]:
df_HUPA11['Time'].duplicated().sum()

np.int64(0)

Round the float columns to 2 decimal places

In [17]:
float_cols = df_HUPA11.select_dtypes(include=['float64']).columns
df_HUPA11[float_cols] = df_HUPA11[float_cols].round(2)
df_HUPA11.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0,0,0.0

In [18]:
df_HUPA11.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0,0,0.0

Cleaning for the file HUPA014.csv

In [20]:

df_HUPA14 = pd.read_csv(
    "HUPA0014P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)


df_HUPA14

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 16:45:00,165.000000,4.49350,71.214286,0.0,0,10.0,5.0
1,2018-11-07 16:50:00,164.666667,4.49350,70.156522,0.0,0,0.0,0.0
2,2018-11-07 16:55:00,164.333333,4.49350,69.077519,0.0,0,0.0,0.0
3,2018-11-07 17:00:00,164.000000,4.49350,69.341270,0.0,0,0.0,0.0
4,2018-11-07 17:05:00,163.666667,4.49350,70.663793,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...
3824,2018-11-20 23:25:00,237.000000,5.21246,86.903226,0.0,0,0.0,0.0
3825,2018-11-20 23:30:00,247.000000,5.12259,86.064516,0.0,0,0.0,0.0
3826,2018-11-20 23:35:00,251.666667,7.27947,83.923077,18.0,0,0.0,0.0
3827,2018-11-20 23:40:00,256.333333,4.49350,76.722222,0.0,0,0.0,0.0
3828,2018-11-20 23:45:00,261.000000,4.49350,75.310345,0.0,0,0.0,0.0

Create a copy of the original Dataset

In [21]:
df_HUPA14Copy= df_HUPA14.copy()
df_HUPA14Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 16:45:00,165.000000,4.4935,71.214286,0.0,0,10.0,5.0
1,2018-11-07 16:50:00,164.666667,4.4935,70.156522,0.0,0,0.0,0.0
2,2018-11-07 16:55:00,164.333333,4.4935,69.077519,0.0,0,0.0,0.0
3,2018-11-07 17:00:00,164.000000,4.4935,69.341270,0.0,0,0.0,0.0
4,2018-11-07 17:05:00,163.666667,4.4935,70.663793,0.0,0,0.0,0.0

Check for the datatypes of the columns and also null values.

In [22]:
df_HUPA14.info()
df_HUPA14.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3829 entries, 0 to 3828
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3829 non-null   datetime64[ns]
 1   glucose                 3829 non-null   float64
 2   calories                3829 non-null   float64
 3   heart_rate              3829 non-null   float64
 4   steps                   3829 non-null   float64
 5   basal_rate              3829 non-null   int64
 6   bolus_volume_delivered  3829 non-null   float64
 7   carb_input              3829 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 239.4 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Add a new column called Patient_id.

In [23]:
df_HUPA14["patient_id"] = "HUPA014P"
df_HUPA14

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2018-11-07 16:45:00,165.000000,4.49350,71.214286,0.0,0,10.0,5.0,HUPA014P
1,2018-11-07 16:50:00,164.666667,4.49350,70.156522,0.0,0,0.0,0.0,HUPA014P
2,2018-11-07 16:55:00,164.333333,4.49350,69.077519,0.0,0,0.0,0.0,HUPA014P
3,2018-11-07 17:00:00,164.000000,4.49350,69.341270,0.0,0,0.0,0.0,HUPA014P
4,2018-11-07 17:05:00,163.666667,4.49350,70.663793,0.0,0,0.0,0.0,HUPA014P
...,...,...,...,...,...,...,...,...,...
3824,2018-11-20 23:25:00,237.000000,5.21246,86.903226,0.0,0,0.0,0.0,HUPA014P
3825,2018-11-20 23:30:00,247.000000,5.12259,86.064516,0.0,0,0.0,0.0,HUPA014P
3826,2018-11-20 23:35:00,251.666667,7.27947,83.923077,18.0,0,0.0,0.0,HUPA014P
3827,2018-11-20 23:40:00,256.333333,4.49350,76.722222,0.0,0,0.0,0.0,HUPA014P
3828,2018-11-20 23:45:00,261.000000,4.49350,75.310345,0.0,0,0.0,0.0,HUPA014P

Bring the patient_id column to the beginning

In [24]:
df_HUPA14 = df_HUPA14[["patient_id"] + [col for col in df_HUPA14.columns if col != "patient_id"]]
df_HUPA14

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA014P,2018-11-07 16:45:00,165.000000,4.49350,71.214286,0.0,0,10.0,5.0
1,HUPA014P,2018-11-07 16:50:00,164.666667,4.49350,70.156522,0.0,0,0.0,0.0
2,HUPA014P,2018-11-07 16:55:00,164.333333,4.49350,69.077519,0.0,0,0.0,0.0
3,HUPA014P,2018-11-07 17:00:00,164.000000,4.49350,69.341270,0.0,0,0.0,0.0
4,HUPA014P,2018-11-07 17:05:00,163.666667,4.49350,70.663793,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3824,HUPA014P,2018-11-20 23:25:00,237.000000,5.21246,86.903226,0.0,0,0.0,0.0
3825,HUPA014P,2018-11-20 23:30:00,247.000000,5.12259,86.064516,0.0,0,0.0,0.0
3826,HUPA014P,2018-11-20 23:35:00,251.666667,7.27947,83.923077,18.0,0,0.0,0.0
3827,HUPA014P,2018-11-20 23:40:00,256.333333,4.49350,76.722222,0.0,0,0.0,0.0
3828,HUPA014P,2018-11-20 23:45:00,261.000000,4.49350,75.310345,0.0,0,0.0,0.0

Remove whitespaces in the data

In [25]:
df_HUPA14.columns = df_HUPA14.columns.str.strip()

Capitalize the first letter of each column

In [26]:
df_HUPA14.columns = df_HUPA14.columns.str.capitalize()
df_HUPA14

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA014P,2018-11-07 16:45:00,165.000000,4.49350,71.214286,0.0,0,10.0,5.0
1,HUPA014P,2018-11-07 16:50:00,164.666667,4.49350,70.156522,0.0,0,0.0,0.0
2,HUPA014P,2018-11-07 16:55:00,164.333333,4.49350,69.077519,0.0,0,0.0,0.0
3,HUPA014P,2018-11-07 17:00:00,164.000000,4.49350,69.341270,0.0,0,0.0,0.0
4,HUPA014P,2018-11-07 17:05:00,163.666667,4.49350,70.663793,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3824,HUPA014P,2018-11-20 23:25:00,237.000000,5.21246,86.903226,0.0,0,0.0,0.0
3825,HUPA014P,2018-11-20 23:30:00,247.000000,5.12259,86.064516,0.0,0,0.0,0.0
3826,HUPA014P,2018-11-20 23:35:00,251.666667,7.27947,83.923077,18.0,0,0.0,0.0
3827,HUPA014P,2018-11-20 23:40:00,256.333333,4.49350,76.722222,0.0,0,0.0,0.0
3828,HUPA014P,2018-11-20 23:45:00,261.000000,4.49350,75.310345,0.0,0,0.0,0.0

Check for duplicate records for the same timestamp

In [27]:
df_HUPA14['Time'].duplicated().sum()

np.int64(0)

Round the float columns to 2 decimal places

In [28]:
float_cols = df_HUPA14.select_dtypes(include=['float64']).columns
df_HUPA14[float_cols] = df_HUPA14[float_cols].round(2)
df_HUPA14.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA014P,2018-11-07 16:45:00,165.00,4.49,71.21,0.0,0,10.0,5.0
1,HUPA014P,2018-11-07 16:50:00,164.67,4.49,70.16,0.0,0,0.0,0.0
2,HUPA014P,2018-11-07 16:55:00,164.33,4.49,69.08,0.0,0,0.0,0.0
3,HUPA014P,2018-11-07 17:00:00,164.00,4.49,69.34,0.0,0,0.0,0.0
4,HUPA014P,2018-11-07 17:05:00,163.67,4.49,70.66,0.0,0,0.0,0.0

Cleaning for the file HUPA015.csv

In [30]:

df_HUPA15 = pd.read_csv(
    "HUPA0015P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)
df_HUPA15

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0
1,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0
2,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0
3,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0
4,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0
...,...,...,...,...,...,...,...,...
3787,2019-04-09 19:50:00,243.666667,6.35100,74.000000,38.0,0,0,0
3788,2019-04-09 19:55:00,241.333333,4.23400,78.102332,0.0,0,0,0
3789,2019-04-09 20:00:00,239.000000,4.23400,82.748787,0.0,0,0,0
3790,2019-04-09 20:05:00,240.000000,4.23400,82.178256,0.0,0,0,0
3791,2019-04-09 20:10:00,241.000000,8.89140,70.629630,14.0,0,0,0

In [31]:
#Create a copy of the original Dataset

df_HUPA15Copy= df_HUPA15.copy()
df_HUPA15Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0
1,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0
2,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0
3,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0
4,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0

In [32]:
#Check for the datatypes of the columns and also null values.

df_HUPA15.info()
df_HUPA15.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3792 entries, 0 to 3791
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3792 non-null   datetime64[ns]
 1   glucose                 3792 non-null   float64
 2   calories                3792 non-null   float64
 3   heart_rate              3792 non-null   float64
 4   steps                   3792 non-null   float64
 5   basal_rate              3792 non-null   int64
 6   bolus_volume_delivered  3792 non-null   int64
 7   carb_input              3792 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(3)
memory usage: 237.1 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

In [33]:
#Add a new column called Patient_id.

df_HUPA15["patient_id"] = "HUPA015P"
df_HUPA15

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0,HUPA015P
1,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0,HUPA015P
2,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0,HUPA015P
3,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0,HUPA015P
4,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0,HUPA015P
...,...,...,...,...,...,...,...,...,...
3787,2019-04-09 19:50:00,243.666667,6.35100,74.000000,38.0,0,0,0,HUPA015P
3788,2019-04-09 19:55:00,241.333333,4.23400,78.102332,0.0,0,0,0,HUPA015P
3789,2019-04-09 20:00:00,239.000000,4.23400,82.748787,0.0,0,0,0,HUPA015P
3790,2019-04-09 20:05:00,240.000000,4.23400,82.178256,0.0,0,0,0,HUPA015P
3791,2019-04-09 20:10:00,241.000000,8.89140,70.629630,14.0,0,0,0,HUPA015P

In [34]:
#Bring the patient_id column to the beginning.

df_HUPA15 = df_HUPA15[["patient_id"] + [col for col in df_HUPA15.columns if col != "patient_id"]]
df_HUPA15

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA015P,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0
1,HUPA015P,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0
2,HUPA015P,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0
3,HUPA015P,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0
4,HUPA015P,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...
3787,HUPA015P,2019-04-09 19:50:00,243.666667,6.35100,74.000000,38.0,0,0,0
3788,HUPA015P,2019-04-09 19:55:00,241.333333,4.23400,78.102332,0.0,0,0,0
3789,HUPA015P,2019-04-09 20:00:00,239.000000,4.23400,82.748787,0.0,0,0,0
3790,HUPA015P,2019-04-09 20:05:00,240.000000,4.23400,82.178256,0.0,0,0,0
3791,HUPA015P,2019-04-09 20:10:00,241.000000,8.89140,70.629630,14.0,0,0,0

In [35]:
#Remove whitespaces in the data

df_HUPA15.columns = df_HUPA15.columns.str.strip()

In [36]:
#Capitalize the first letter of each column

df_HUPA15.columns = df_HUPA15.columns.str.capitalize()
df_HUPA15

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA015P,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0
1,HUPA015P,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0
2,HUPA015P,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0
3,HUPA015P,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0
4,HUPA015P,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...
3787,HUPA015P,2019-04-09 19:50:00,243.666667,6.35100,74.000000,38.0,0,0,0
3788,HUPA015P,2019-04-09 19:55:00,241.333333,4.23400,78.102332,0.0,0,0,0
3789,HUPA015P,2019-04-09 20:00:00,239.000000,4.23400,82.748787,0.0,0,0,0
3790,HUPA015P,2019-04-09 20:05:00,240.000000,4.23400,82.178256,0.0,0,0,0
3791,HUPA015P,2019-04-09 20:10:00,241.000000,8.89140,70.629630,14.0,0,0,0

In [37]:
#Check for duplicate records for the same timestamp

df_HUPA15['Time'].duplicated().sum()

np.int64(0)

In [38]:
#Round the float columns to 2 decimal places

float_cols = df_HUPA15.select_dtypes(include=['float64']).columns
df_HUPA15[float_cols] = df_HUPA15[float_cols].round(2)
df_HUPA15.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA015P,2019-03-27 16:15:00,60.00,17.70,109.16,15.0,0,0,0
1,HUPA015P,2019-03-27 16:20:00,58.67,6.77,89.54,0.0,0,0,0
2,HUPA015P,2019-03-27 16:25:00,57.33,6.01,56.89,32.0,0,0,0
3,HUPA015P,2019-03-27 16:30:00,56.00,5.50,58.72,0.0,0,0,0
4,HUPA015P,2019-03-27 16:35:00,54.00,4.66,58.18,0.0,0,0,0

In [40]:
#Cleaning for the file HUPA016.csv

df_HUPA16 = pd.read_csv(
    "HUPA0016P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)


df_HUPA16

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0
1,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0
2,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0
3,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0
4,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0
...,...,...,...,...,...,...,...,...
3830,2019-04-09 23:25:00,65.333333,4.656000,75.095238,0.0,0.073333,0.0,0.0
3831,2019-04-09 23:30:00,65.000000,4.842240,86.362205,0.0,0.073333,0.0,0.0
3832,2019-04-09 23:35:00,73.666667,4.749120,76.833333,0.0,0.073333,0.7,2.0
3833,2019-04-09 23:40:00,82.333333,4.749120,76.343284,0.0,0.073333,0.0,0.0
3834,2019-04-09 23:45:00,91.000000,4.656000,75.545455,0.0,0.073333,0.0,0.0

In [41]:
#Create a copy of the original Dataset

df_HUPA16Copy= df_HUPA16.copy()
df_HUPA16Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0
1,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0
2,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0
3,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0
4,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0

In [42]:
#Check for the datatypes of the columns and also null values.

df_HUPA16.info()
df_HUPA16.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3835 entries, 0 to 3834
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3835 non-null   datetime64[ns]
 1   glucose                 3835 non-null   float64
 2   calories                3835 non-null   float64
 3   heart_rate              3835 non-null   float64
 4   steps                   3835 non-null   float64
 5   basal_rate              3835 non-null   float64
 6   bolus_volume_delivered  3835 non-null   float64
 7   carb_input              3835 non-null   float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 239.8 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

In [43]:
#Add a new column called Patient_id.

df_HUPA16["patient_id"] = "HUPA016P"
df_HUPA16

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0,HUPA016P
1,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0,HUPA016P
2,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0,HUPA016P
3,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0,HUPA016P
4,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0,HUPA016P
...,...,...,...,...,...,...,...,...,...
3830,2019-04-09 23:25:00,65.333333,4.656000,75.095238,0.0,0.073333,0.0,0.0,HUPA016P
3831,2019-04-09 23:30:00,65.000000,4.842240,86.362205,0.0,0.073333,0.0,0.0,HUPA016P
3832,2019-04-09 23:35:00,73.666667,4.749120,76.833333,0.0,0.073333,0.7,2.0,HUPA016P
3833,2019-04-09 23:40:00,82.333333,4.749120,76.343284,0.0,0.073333,0.0,0.0,HUPA016P
3834,2019-04-09 23:45:00,91.000000,4.656000,75.545455,0.0,0.073333,0.0,0.0,HUPA016P

In [44]:
#Bring the patient_id column to the beginning.

df_HUPA16 = df_HUPA16[["patient_id"] + [col for col in df_HUPA16.columns if col != "patient_id"]]
df_HUPA16

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA016P,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0
1,HUPA016P,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0
2,HUPA016P,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0
3,HUPA016P,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0
4,HUPA016P,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3830,HUPA016P,2019-04-09 23:25:00,65.333333,4.656000,75.095238,0.0,0.073333,0.0,0.0
3831,HUPA016P,2019-04-09 23:30:00,65.000000,4.842240,86.362205,0.0,0.073333,0.0,0.0
3832,HUPA016P,2019-04-09 23:35:00,73.666667,4.749120,76.833333,0.0,0.073333,0.7,2.0
3833,HUPA016P,2019-04-09 23:40:00,82.333333,4.749120,76.343284,0.0,0.073333,0.0,0.0
3834,HUPA016P,2019-04-09 23:45:00,91.000000,4.656000,75.545455,0.0,0.073333,0.0,0.0

In [45]:
#Remove whitespaces in the data

df_HUPA16.columns = df_HUPA16.columns.str.strip()

In [46]:
#Capitalize the first letter of each column

df_HUPA16.columns = df_HUPA16.columns.str.capitalize()
df_HUPA16

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA016P,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0
1,HUPA016P,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0
2,HUPA016P,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0
3,HUPA016P,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0
4,HUPA016P,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3830,HUPA016P,2019-04-09 23:25:00,65.333333,4.656000,75.095238,0.0,0.073333,0.0,0.0
3831,HUPA016P,2019-04-09 23:30:00,65.000000,4.842240,86.362205,0.0,0.073333,0.0,0.0
3832,HUPA016P,2019-04-09 23:35:00,73.666667,4.749120,76.833333,0.0,0.073333,0.7,2.0
3833,HUPA016P,2019-04-09 23:40:00,82.333333,4.749120,76.343284,0.0,0.073333,0.0,0.0
3834,HUPA016P,2019-04-09 23:45:00,91.000000,4.656000,75.545455,0.0,0.073333,0.0,0.0

In [47]:
#Check for duplicate records for the same timestamp

df_HUPA16['Time'].duplicated().sum()

np.int64(0)

In [48]:
#Round the float columns to 2 decimal places

float_cols = df_HUPA11.select_dtypes(include=['float64']).columns
df_HUPA16[float_cols] = df_HUPA16[float_cols].round(2)
df_HUPA16.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA016P,2019-03-27 16:15:00,55.00,5.87,94.27,0.0,0.069167,0.0,0.0
1,HUPA016P,2019-03-27 16:20:00,55.33,5.87,92.79,0.0,0.069167,0.0,0.0
2,HUPA016P,2019-03-27 16:25:00,55.67,5.77,89.57,0.0,0.069167,0.0,0.0
3,HUPA016P,2019-03-27 16:30:00,56.00,22.54,112.90,278.0,0.069167,0.0,0.0
4,HUPA016P,2019-03-27 16:35:00,64.67,34.45,125.90,491.0,0.069167,0.0,0.0

In [145]:
#Cleaning for the file HUPA017.csv

df_HUPA17 = pd.read_csv(
    "HUPA0017P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)
df_HUPA17

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0
1,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0
2,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0
3,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0
4,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0
...,...,...,...,...,...,...,...,...
3594,2019-04-09 23:30:00,165.750000,4.77150,81.246461,0.0,0.059,0.0,0.0
3595,2019-04-09 23:35:00,166.833333,4.77150,80.897641,0.0,0.059,0.0,0.0
3596,2019-04-09 23:40:00,167.916667,4.77150,80.548820,0.0,0.059,0.0,0.0
3597,2019-04-09 23:45:00,169.000000,4.96236,80.200000,0.0,0.059,0.0,0.0
3598,2019-04-09 23:50:00,170.083333,8.87499,83.868421,35.0,0.059,0.0,0.0

In [146]:
#Create a copy of the original Dataset

df_HUPA17Copy= df_HUPA17.copy()
df_HUPA17Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0
1,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0
2,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0
3,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0
4,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0

In [147]:
#Check for the datatypes of the columns and also null values.

df_HUPA17.info()
df_HUPA17.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3599 entries, 0 to 3598
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3599 non-null   datetime64[ns]
 1   glucose                 3599 non-null   float64
 2   calories                3599 non-null   float64
 3   heart_rate              3599 non-null   float64
 4   steps                   3599 non-null   float64
 5   basal_rate              3599 non-null   float64
 6   bolus_volume_delivered  3599 non-null   float64
 7   carb_input              3599 non-null   float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 225.1 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

In [149]:
#Add a new column called Patient_id.

df_HUPA17["patient_id"] = "HUPA017P"
df_HUPA17

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0,HUPA017P
1,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0,HUPA017P
2,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0,HUPA017P
3,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0,HUPA017P
4,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0,HUPA017P
...,...,...,...,...,...,...,...,...,...
3594,2019-04-09 23:30:00,165.750000,4.77150,81.246461,0.0,0.059,0.0,0.0,HUPA017P
3595,2019-04-09 23:35:00,166.833333,4.77150,80.897641,0.0,0.059,0.0,0.0,HUPA017P
3596,2019-04-09 23:40:00,167.916667,4.77150,80.548820,0.0,0.059,0.0,0.0,HUPA017P
3597,2019-04-09 23:45:00,169.000000,4.96236,80.200000,0.0,0.059,0.0,0.0,HUPA017P
3598,2019-04-09 23:50:00,170.083333,8.87499,83.868421,35.0,0.059,0.0,0.0,HUPA017P

In [150]:
#Bring the patient_id column to the beginning.

df_HUPA17 = df_HUPA17[["patient_id"] + [col for col in df_HUPA17.columns if col != "patient_id"]]
df_HUPA17

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA017P,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0
1,HUPA017P,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0
2,HUPA017P,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0
3,HUPA017P,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0
4,HUPA017P,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3594,HUPA017P,2019-04-09 23:30:00,165.750000,4.77150,81.246461,0.0,0.059,0.0,0.0
3595,HUPA017P,2019-04-09 23:35:00,166.833333,4.77150,80.897641,0.0,0.059,0.0,0.0
3596,HUPA017P,2019-04-09 23:40:00,167.916667,4.77150,80.548820,0.0,0.059,0.0,0.0
3597,HUPA017P,2019-04-09 23:45:00,169.000000,4.96236,80.200000,0.0,0.059,0.0,0.0
3598,HUPA017P,2019-04-09 23:50:00,170.083333,8.87499,83.868421,35.0,0.059,0.0,0.0

In [151]:
#Remove whitespaces in the data

df_HUPA17.columns = df_HUPA17.columns.str.strip()

In [152]:
#Capitalize the first letter of each column

df_HUPA17.columns = df_HUPA17.columns.str.capitalize()
df_HUPA17

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA017P,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0
1,HUPA017P,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0
2,HUPA017P,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0
3,HUPA017P,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0
4,HUPA017P,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3594,HUPA017P,2019-04-09 23:30:00,165.750000,4.77150,81.246461,0.0,0.059,0.0,0.0
3595,HUPA017P,2019-04-09 23:35:00,166.833333,4.77150,80.897641,0.0,0.059,0.0,0.0
3596,HUPA017P,2019-04-09 23:40:00,167.916667,4.77150,80.548820,0.0,0.059,0.0,0.0
3597,HUPA017P,2019-04-09 23:45:00,169.000000,4.96236,80.200000,0.0,0.059,0.0,0.0
3598,HUPA017P,2019-04-09 23:50:00,170.083333,8.87499,83.868421,35.0,0.059,0.0,0.0

In [153]:
cols_to_round = [
    'Glucose',
    'Calories',
    'Heart_rate',
    'Steps',
    'Bolus_volume_delivered',
    'Carb_input'
]

df_HUPA17[cols_to_round] = df_HUPA17[cols_to_round].round(2)

Detect the outliers for all the five patients in each file. For that we give upper limits and lower limits for the parameters which we need to handle and only those files which has outliers will be displayed.

In [154]:
def identify_real_outliers(df):
    df['outlier'] = False
    df['outlier_column'] = ""

    for idx, row in df.iterrows():

        # Glucose
        if row['Glucose'] < 40 or row['Glucose'] >500:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Glucose, "

        # Heart rate
        if row['Heart_rate'] < 30 or row['Heart_rate'] > 220:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Heart_rate, "

        # Steps
        if row['Steps'] < 0 or row['Steps'] > 6000:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Steps, "

        # Bolus insulin
        if row['Bolus_volume_delivered'] < 0 or row['Bolus_volume_delivered'] > 25:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Bolus_volume_delivered, "

        # Carb input
        if row['Carb_input'] < 0 or row['Carb_input'] > 200:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Carb_input, "

    # ⭐ Print message
    if not df['outlier'].any():
        print("No outliers in the specified columns")
    else:
        print("Outliers found in the specified columns")

    # ⭐ Return only the outlier rows
    return df[df['outlier'] == True]

In [155]:
all_dfs = {
    "HUPA11": df_HUPA11,
    "HUPA14": df_HUPA14,
    "HUPA15": df_HUPA15,
    "HUPA16": df_HUPA16,
    "HUPA17": df_HUPA17
}

In [156]:
outlier_results = {}

for name, df in all_dfs.items():
    print(f"\nChecking outliers for {name}...")
    outlier_results[name] = identify_real_outliers(df)

Checking outliers for HUPA11...
No outliers in the specified columns

Checking outliers for HUPA14...
No outliers in the specified columns

Checking outliers for HUPA15...
No outliers in the specified columns

Checking outliers for HUPA16...
No outliers in the specified columns

Checking outliers for HUPA17...
Outliers found in the specified columns

In [157]:
outlier_results["HUPA17"]

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input,outlier,outlier_column
324,HUPA017P,2019-03-29 15:00:00,103.0,6.49,84.18,0.0,0.059,-1.0,7.0,True,"Bolus_volume_delivered,"
894,HUPA017P,2019-03-31 14:30:00,84.0,4.77,98.22,0.0,0.059,-1.0,4.0,True,"Bolus_volume_delivered,"
2601,HUPA017P,2019-04-06 12:45:00,134.0,14.60,100.23,84.0,0.059,-3.0,4.0,True,"Bolus_volume_delivered,"
2895,HUPA017P,2019-04-07 13:15:00,97.0,4.77,98.32,0.0,0.059,-1.0,2.5,True,"Bolus_volume_delivered,"

In [ ]:
Converting negative Bogus volume delievered column from negative to 0 for the patient HUPA017P

In [158]:
df_HUPA17.loc[df_HUPA17['Bolus_volume_delivered'] < 0, 'Bolus_volume_delivered'] = 0

In [159]:
df_HUPA17[df_HUPA17['Bolus_volume_delivered'] < 0]

Empty DataFrame
Columns: [Patient_id, Time, Glucose, Calories, Heart_rate, Steps, Basal_rate, Bolus_volume_delivered, Carb_input, outlier, outlier_column]
Index: []

In [160]:
df_HUPA17[df_HUPA17['outlier_column'].str.contains("Bolus_volume_delivered")]

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input,outlier,outlier_column
324,HUPA017P,2019-03-29 15:00:00,103.0,6.49,84.18,0.0,0.059,0.0,7.0,True,"Bolus_volume_delivered,"
894,HUPA017P,2019-03-31 14:30:00,84.0,4.77,98.22,0.0,0.059,0.0,4.0,True,"Bolus_volume_delivered,"
2601,HUPA017P,2019-04-06 12:45:00,134.0,14.60,100.23,84.0,0.059,0.0,4.0,True,"Bolus_volume_delivered,"
2895,HUPA017P,2019-04-07 13:15:00,97.0,4.77,98.32,0.0,0.059,0.0,2.5,True,"Bolus_volume_delivered,"

In [ ]:
Rem

In [168]:
df_HUPA11 = df_HUPA11.drop(columns=['outlier', 'outlier_column'])

In [171]:
df_HUPA14 = df_HUPA14.drop(columns=['outlier', 'outlier_column'])

In [172]:
df_HUPA15 = df_HUPA15.drop(columns=['outlier', 'outlier_column'])

In [173]:
df_HUPA16 = df_HUPA16.drop(columns=['outlier', 'outlier_column'])

In [174]:
df_HUPA17 = df_HUPA17.drop(columns=['outlier', 'outlier_column'])

In [180]:
#Save the individual cleaned file to a .csv file

df_HUPA11.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA011_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [181]:
#Save the individual cleaned file to a .csv file

df_HUPA14.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA014_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [182]:
#Save the individual cleaned file to a .csv file

df_HUPA15.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA015_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [183]:
#Save the individual cleaned file to a .csv file

df_HUPA16.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA016_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [184]:
#Save the individual cleaned file to a .csv file

df_HUPA17.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA017_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [185]:
df_HUPA14

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA014P,2018-11-07 16:45:00,165.00,4.49,71.21,0.0,0,10.0,5.0
1,HUPA014P,2018-11-07 16:50:00,164.67,4.49,70.16,0.0,0,0.0,0.0
2,HUPA014P,2018-11-07 16:55:00,164.33,4.49,69.08,0.0,0,0.0,0.0
3,HUPA014P,2018-11-07 17:00:00,164.00,4.49,69.34,0.0,0,0.0,0.0
4,HUPA014P,2018-11-07 17:05:00,163.67,4.49,70.66,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3824,HUPA014P,2018-11-20 23:25:00,237.00,5.21,86.90,0.0,0,0.0,0.0
3825,HUPA014P,2018-11-20 23:30:00,247.00,5.12,86.06,0.0,0,0.0,0.0
3826,HUPA014P,2018-11-20 23:35:00,251.67,7.28,83.92,18.0,0,0.0,0.0
3827,HUPA014P,2018-11-20 23:40:00,256.33,4.49,76.72,0.0,0,0.0,0.0
3828,HUPA014P,2018-11-20 23:45:00,261.00,4.49,75.31,0.0,0,0.0,0.0

In [167]:
df_HUPA11

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input,outlier,outlier_column
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0,0,0.0,False,
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0,0,0.0,False,
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0,0,0.0,False,
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0,0,0.0,False,
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0,0,0.0,False,
...,...,...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.00,5.40,63.00,0.0,0,0,0.0,False,
3835,HUPA011P,2018-11-20 23:30:00,213.00,6.65,62.02,0.0,0,0,0.0,False,
3836,HUPA011P,2018-11-20 23:35:00,212.00,5.32,62.98,0.0,0,0,0.0,False,
3837,HUPA011P,2018-11-20 23:40:00,211.00,4.74,72.13,0.0,0,0,0.0,False,
3838,HUPA011P,2018-11-20 23:45:00,210.00,8.32,73.22,50.0,0,0,0.0,False,

Remove all the outlier and outlier columns

In [186]:
df_HUPA16

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA016P,2019-03-27 16:15:00,55.00,5.87,94.27,0.0,0.069167,0.0,0.0
1,HUPA016P,2019-03-27 16:20:00,55.33,5.87,92.79,0.0,0.069167,0.0,0.0
2,HUPA016P,2019-03-27 16:25:00,55.67,5.77,89.57,0.0,0.069167,0.0,0.0
3,HUPA016P,2019-03-27 16:30:00,56.00,22.54,112.90,278.0,0.069167,0.0,0.0
4,HUPA016P,2019-03-27 16:35:00,64.67,34.45,125.90,491.0,0.069167,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3830,HUPA016P,2019-04-09 23:25:00,65.33,4.66,75.10,0.0,0.073333,0.0,0.0
3831,HUPA016P,2019-04-09 23:30:00,65.00,4.84,86.36,0.0,0.073333,0.0,0.0
3832,HUPA016P,2019-04-09 23:35:00,73.67,4.75,76.83,0.0,0.073333,0.7,2.0
3833,HUPA016P,2019-04-09 23:40:00,82.33,4.75,76.34,0.0,0.073333,0.0,0.0
3834,HUPA016P,2019-04-09 23:45:00,91.00,4.66,75.55,0.0,0.073333,0.0,0.0