Data Preprocessing - Data Cleaning

In [2]:
# ============================================================
# CELL 1 — Import Libraries
# ============================================================
import pandas as pd
import numpy as np

Loading Data Set

# ============================================================
# CELL 2 — Load Dataset
# ============================================================
df = pd.read_csv(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Raw files\HUPA-UC Diabetes Dataset\HUPA0006P.csv",
    sep=";"
)

print("Shape:", df.shape)
print("\nColumns:", list(df.columns))
df.head()

Check Duplicate

In [5]:
#CELL 3 — CHECK: Duplicates
# ============================================================
print("Full duplicate rows:", df.duplicated().sum())
print("Duplicate timestamps:", df.duplicated(subset='time').sum())

Full duplicate rows: 0
Duplicate timestamps: 0

In [ ]:
Fixing Done remains same rows

In [6]:
df = df.drop_duplicates()
df = df.drop_duplicates(subset='time', keep='first').reset_index(drop=True)
print("After fix — Shape:", df.shape)

After fix — Shape: (2290, 8)

In [ ]:
CHECK: Data Types

In [7]:
print(df.dtypes)

time                       object
glucose                   float64
calories                  float64
heart_rate                float64
steps                     float64
basal_rate                float64
bolus_volume_delivered    float64
carb_input                float64
dtype: object

In [8]:
df['time'] = pd.to_datetime(df['time'])

num_cols = ['glucose', 'calories', 'heart_rate', 'steps',
            'basal_rate', 'bolus_volume_delivered', 'carb_input']
df[num_cols] = df[num_cols].astype(float)

print("After fix:\n", df.dtypes)

After fix:
 time                      datetime64[ns]
glucose                          float64
calories                         float64
heart_rate                       float64
steps                            float64
basal_rate                       float64
bolus_volume_delivered           float64
carb_input                       float64
dtype: object

CHECK: Missing / Null Values

In [9]:
print("Null values per column:")
print(df.isnull().sum())
print("\nTotal nulls:", df.isnull().sum().sum())

Null values per column:
time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Total nulls: 0

In [10]:
# FIX: Null Values (interpolate if any found)
df[num_cols] = df[num_cols].interpolate(method='linear', limit_direction='both')
print("Nulls after fix:", df.isnull().sum().sum())

Nulls after fix: 0

 CHECK: Trim & Clean Text

In [11]:
#Check for leading/trailing whitespace in time column
print("Whitespace issues in time:")
print(df['time'].astype(str).str.contains(r'^\s|\s$').sum())

# Check column name whitespace
print("\nColumn names:")
print([f"'{c}'" for c in df.columns])

Whitespace issues in time:
0

Column names:
["'time'", "'glucose'", "'calories'", "'heart_rate'", "'steps'", "'basal_rate'", "'bolus_volume_delivered'", "'carb_input'"]

In [12]:
# FIX: Trim Text
df['time'] = pd.to_datetime(df['time'].astype(str).str.strip())
df.columns = df.columns.str.strip()
print("Text trimmed.")

Text trimmed.

CHECK: Standardize Values

In [13]:
# Check if data is sorted by time
is_sorted = df['time'].is_monotonic_increasing
print("Is sorted by time:", is_sorted)

# Check decimal precision
print("\nSample decimal values:")
print(df[num_cols].head(3))

Is sorted by time: True

Sample decimal values:
      glucose  calories  heart_rate  steps  basal_rate  \
0  109.000000  11.23939   70.769231    0.0       0.075
1  107.666667   8.11090   70.189655    5.0       0.075
2  106.333333   6.48872   70.170940    0.0       0.075

   bolus_volume_delivered  carb_input
0                     0.0         0.0
1                     0.0         0.0
2                     0.0         0.0

In [35]:
import pandas as pd

pd.options.display.float_format = '{:.2f}'.format
df.describe()

,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
count,2290,2290.00,2290.00,2290.00,2290.00,2290.00,2290.00,2290.00
mean,2018-07-13 15:07:30,165.11,9.84,65.62,34.01,0.08,0.10,0.10
min,2018-07-09 15:45:00,42.00,5.79,41.42,0.00,0.00,0.00,0.00
25%,2018-07-11 15:26:15,96.00,5.79,56.23,0.00,0.07,0.00,0.00
50%,2018-07-13 15:07:30,146.00,6.49,62.97,0.00,0.08,0.00,0.00
75%,2018-07-15 14:48:45,219.58,10.54,71.69,18.00,0.09,0.00,0.00
max,2018-07-17 14:30:00,399.11,61.87,157.70,626.00,0.11,10.80,10.00
std,NaN,84.45,7.17,14.35,83.94,0.02,0.80,0.81

CHECK: Invalid / Erroneous Values

In [15]:
# Glucose: valid CGM range is 40–400 mg/dL
print("Glucose outliers (<40 or >400):")
print(df[(df['glucose'] < 40) | (df['glucose'] > 400)][['time', 'glucose']])

# Negative values check
print("\nNegative values per column:")
for col in num_cols:
    neg = (df[col] < 0).sum()
    print(f"  {col}: {neg}")

# Heart rate zero check
print("\nZero heart rate rows:", (df['heart_rate'] == 0).sum())

Glucose outliers (<40 or >400):
                    time  glucose
2115 2018-07-17 00:00:00   401.00
2116 2018-07-17 00:05:00   406.00
2117 2018-07-17 00:10:00   411.00
2118 2018-07-17 00:15:00   416.00
2119 2018-07-17 00:20:00   423.33
2120 2018-07-17 00:25:00   430.67
2121 2018-07-17 00:30:00   438.00
2122 2018-07-17 00:35:00   430.22
2123 2018-07-17 00:40:00   422.44
2124 2018-07-17 00:45:00   414.67
2125 2018-07-17 00:50:00   406.89

Negative values per column:
  glucose: 0
  calories: 0
  heart_rate: 0
  steps: 0
  basal_rate: 0
  bolus_volume_delivered: 0
  carb_input: 0

Zero heart rate rows: 0

In [16]:
# FIX: Correct Invalid Values
df['glucose_outlier_flag'] = ((df['glucose'] < 40) | (df['glucose'] > 400)).astype(int)
df.loc[df['glucose_outlier_flag'] == 1, 'glucose'] = np.nan
df['glucose'] = df['glucose'].interpolate(method='linear', limit_direction='both').round(2)

print("Outliers after fix:", ((df['glucose'] < 40) | (df['glucose'] > 400)).sum())
print("Glucose range:", df['glucose'].min(), "–", df['glucose'].max())

Outliers after fix: 0
Glucose range: 42.0 – 399.11

checking column names

In [17]:
# ============================================================
# CELL 9 — CHECK: Column Names
# ============================================================
print("Current column names:")
print(df.columns.tolist())

Current column names:
['time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate', 'bolus_volume_delivered', 'carb_input', 'glucose_outlier_flag']

In [18]:
# FIX: Rename Columns
df = df.rename(columns={
    'time'                   : 'Time',
    'glucose'                : 'Glucose',
    'calories'               : 'Calories',
    'heart_rate'             : 'Heart Rate',
    'steps'                  : 'Steps',
    'basal_rate'             : 'Basal Rate',
    'bolus_volume_delivered' : 'Bolus Volume',
    'carb_input'             : 'Carb Input',
    '
})
print("Renamed:", df.columns.tolist())

Renamed: ['Time', 'Glucose', 'Calories', 'Heart Rate', 'Steps', 'Basal Rate', 'Bolus Volume', 'Carb Input', 'glucose_outlier_flag']

CHECK: Irrelevant Columns

In [19]:
print("All columns:")
print(df.columns.tolist())
print("\nOutlier flag column value counts:")
print(df['glucose_outlier_flag'].value_counts())

All columns:
['Time', 'Glucose', 'Calories', 'Heart Rate', 'Steps', 'Basal Rate', 'Bolus Volume', 'Carb Input', 'glucose_outlier_flag']

Outlier flag column value counts:
glucose_outlier_flag
0    2279
1      11
Name: count, dtype: int64

In [20]:
# FIX: Drop Outlier Flag Column
df = df.drop(columns=['glucose_outlier_flag'])
print("Columns after drop:", df.columns.tolist())

Columns after drop: ['Time', 'Glucose', 'Calories', 'Heart Rate', 'Steps', 'Basal Rate', 'Bolus Volume', 'Carb Input']

CELL 11 — CHECK: Inconsistent Categories

In [21]:
print("Zero value counts per column:")
for col in df.columns[1:]:
    zeros = (df[col] == 0).sum()
    pct = round(zeros / len(df) * 100, 1)
    print(f"  {col}: {zeros} zeros ({pct}%)")

Zero value counts per column:
  Glucose: 0 zeros (0.0%)
  Calories: 0 zeros (0.0%)
  Heart Rate: 0 zeros (0.0%)
  Steps: 1553 zeros (67.8%)
  Basal Rate: 42 zeros (1.8%)
  Bolus Volume: 2244 zeros (98.0%)
  Carb Input: 2253 zeros (98.4%)

In [22]:
# No fix needed — zeros are clinically valid
# (patient not moving = 0 steps, no bolus given = 0 bolus_units)
print("No fix required. Zeros are valid in this dataset.")

No fix required. Zeros are valid in this dataset.

CHECK: Validate Relationships / Keys

In [28]:
# ============================================================
# CELL 12 — CHECK: Validate Relationships / Keys
# ============================================================
print("Unique timestamps:", df['Time'].nunique(), "of", len(df))
print("Duplicate timestamps:", df.duplicated(subset='Time').sum())

diffs = df['Time'].diff().dropna()
print("\nTime interval check:")
print(diffs.value_counts())

Unique timestamps: 2290 of 2290
Duplicate timestamps: 0

Time interval check:
Time
0 days 00:05:00    2289
Name: count, dtype: int64

In [30]:
# No fix needed if all intervals = 5 min and no duplicates
print("Timestamp validation passed." if df.duplicated(subset='Time').sum() == 0 else "Fix needed.")

Timestamp validation passed.

Final Summary

In [31]:
# ============================================================
# CELL 13 — Final Summary
# ============================================================
print("Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nNull Values:\n", df.isnull().sum())
print("\nDescriptive Stats:")
df.describe()

Shape: (2290, 8)

Data Types:
 Time            datetime64[ns]
Glucose                float64
Calories               float64
Heart Rate             float64
Steps                  float64
Basal Rate             float64
Bolus Volume           float64
Carb Input             float64
dtype: object

Null Values:
 Time            0
Glucose         0
Calories        0
Heart Rate      0
Steps           0
Basal Rate      0
Bolus Volume    0
Carb Input      0
dtype: int64

Descriptive Stats:

,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
count,2290,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000
mean,2018-07-13 15:07:30,165.107017,9.843834,65.619393,34.008297,0.076646,0.099039,0.097817
min,2018-07-09 15:45:00,42.000000,5.790000,41.420000,0.000000,0.000000,0.000000,0.000000
25%,2018-07-11 15:26:15,96.000000,5.790000,56.225000,0.000000,0.070000,0.000000,0.000000
50%,2018-07-13 15:07:30,146.000000,6.490000,62.965000,0.000000,0.080000,0.000000,0.000000
75%,2018-07-15 14:48:45,219.585000,10.540000,71.687500,18.000000,0.090000,0.000000,0.000000
max,2018-07-17 14:30:00,399.110000,61.870000,157.700000,626.000000,0.110000,10.800000,10.000000
std,NaN,84.452280,7.173064,14.345908,83.938115,0.018611,0.797489,0.813170

,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
count,2290,2290.00,2290.00,2290.00,2290.00,2290.00,2290.00,2290.00
mean,2018-07-13 15:07:30,165.11,9.84,65.62,34.01,0.08,0.10,0.10
min,2018-07-09 15:45:00,42.00,5.79,41.42,0.00,0.00,0.00,0.00
25%,2018-07-11 15:26:15,96.00,5.79,56.23,0.00,0.07,0.00,0.00
50%,2018-07-13 15:07:30,146.00,6.49,62.97,0.00,0.08,0.00,0.00
75%,2018-07-15 14:48:45,219.58,10.54,71.69,18.00,0.09,0.00,0.00
max,2018-07-17 14:30:00,399.11,61.87,157.70,626.00,0.11,10.80,10.00
std,NaN,84.45,7.17,14.35,83.94,0.02,0.80,0.81

In [ ]:
Adding the Patient ID as first Column

In [39]:
# ============================================================
# CELL 14 — Adding the Patient ID as first Column
# ============================================================
df.insert(0, 'Patient ID', 'HUPA006', allow_duplicates=True)

In [40]:
df.head()

,Patient ID,Patient ID,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
0,HUPA006,HUPA006,2018-07-09 15:45:00,109.00,11.24,70.77,0.00,0.08,0.00,0.00
1,HUPA006,HUPA006,2018-07-09 15:50:00,107.67,8.11,70.19,5.00,0.08,0.00,0.00
2,HUPA006,HUPA006,2018-07-09 15:55:00,106.33,6.49,70.17,0.00,0.08,0.00,0.00
3,HUPA006,HUPA006,2018-07-09 16:00:00,105.00,7.07,72.37,0.00,0.06,0.00,0.00
4,HUPA006,HUPA006,2018-07-09 16:05:00,122.33,9.62,68.22,6.00,0.06,0.00,10.00

In [41]:
df.drop(columns=['Patient ID'], inplace=True)
df.insert(0, 'Patient ID', 'HUPA006')

In [42]:
df.head()

,Patient ID,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
0,HUPA006,2018-07-09 15:45:00,109.00,11.24,70.77,0.00,0.08,0.00,0.00
1,HUPA006,2018-07-09 15:50:00,107.67,8.11,70.19,5.00,0.08,0.00,0.00
2,HUPA006,2018-07-09 15:55:00,106.33,6.49,70.17,0.00,0.08,0.00,0.00
3,HUPA006,2018-07-09 16:00:00,105.00,7.07,72.37,0.00,0.06,0.00,0.00
4,HUPA006,2018-07-09 16:05:00,122.33,9.62,68.22,6.00,0.06,0.00,10.00

Save Cleaned File

In [44]:
# ============================================================
# CELL 15 — Save Cleaned File
# ============================================================
df.to_csv(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Abirami\HUPA0006P_cleaned.csv",
    index=False
)
print("Saved successfully!")

Saved successfully!