# <h1 align="center">Data Preprocessing - Data Cleaning</h1>

<h2 style="color: purple;"> Patiend ID - HUPA0001P,HUPA0002P,HUPA0003P,HUPA0004P,HUPA0005P </h2>

In [2]:
import pandas as pd
import glob
import os

cgm_5files_mv = glob.glob("C:/python_hackathon/HUPA-UC Diabetes Dataset-20250820T010637Z-1-001/HUPA-UC Diabetes Dataset/CGM5_MV/*.csv")

dfs = []
for file in cgm_5files_mv :
    if os.path.isfile(file):
        df = pd.read_csv(file, sep=';')
        df['patient_id'] = os.path.basename(file).replace('.csv', '')
        dfs.append(df)


df_CGM5_MV= pd.concat(dfs, ignore_index=True)

# Move patient_id to first column
cols = ['patient_id'] + [col for col in df_CGM5_MV.columns if col != 'patient_id']
df_CGM5_MV = df_CGM5_MV[cols]

df_CGM5_MV

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.35950,82.322835,34.0,0.091667,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.72800,83.740157,0.0,0.091667,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.74950,80.525180,0.0,0.091667,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.35950,89.129032,20.0,0.091667,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15200,92.495652,0.0,0.075000,0.0,0.0
...,...,...,...,...,...,...,...,...,...
18084,HUPA0005P,2018-07-22T23:25:00,76.5,4.26350,83.140496,0.0,0.075000,0.0,0.0
18085,HUPA0005P,2018-07-22T23:30:00,57.0,4.26350,83.041667,0.0,0.075000,0.0,0.0
18086,HUPA0005P,2018-07-22T23:35:00,53.0,4.26350,79.071429,0.0,0.075000,0.0,0.0
18087,HUPA0005P,2018-07-22T23:40:00,49.0,4.26350,82.910714,0.0,0.075000,0.0,0.0
18088,HUPA0005P,2018-07-22T23:45:00,45.0,5.54255,82.250000,6.0,0.075000,0.0,0.0

### Just we import the dataset into csv files to start  the data cleaning process to find the meaningful insights.

In [3]:
df_CGM5_MV[df_CGM5_MV.duplicated(subset="patient_id", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="time", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="glucose", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="heart_rate", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="steps", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="basal_rate", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="bolus_volume_delivered", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="carb_input", keep=False)]

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.35950,82.322835,34.0,0.091667,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.72800,83.740157,0.0,0.091667,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.74950,80.525180,0.0,0.091667,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.35950,89.129032,20.0,0.091667,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15200,92.495652,0.0,0.075000,0.0,0.0
...,...,...,...,...,...,...,...,...,...
18084,HUPA0005P,2018-07-22T23:25:00,76.5,4.26350,83.140496,0.0,0.075000,0.0,0.0
18085,HUPA0005P,2018-07-22T23:30:00,57.0,4.26350,83.041667,0.0,0.075000,0.0,0.0
18086,HUPA0005P,2018-07-22T23:35:00,53.0,4.26350,79.071429,0.0,0.075000,0.0,0.0
18087,HUPA0005P,2018-07-22T23:40:00,49.0,4.26350,82.910714,0.0,0.075000,0.0,0.0
18088,HUPA0005P,2018-07-22T23:45:00,45.0,5.54255,82.250000,6.0,0.075000,0.0,0.0

### We are finding duplicates here, because duplicates cause may wrong decision.In analytics, duplicates can inflate totals and wrong KPIs,wron aggregation, it affect the data quality.

In [5]:
df_CGM5_MV.columns = df_CGM5_MV.columns.str.title()

In [6]:
df_CGM5_MV.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.3595,82.322835,34.0,0.091667,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.7280,83.740157,0.0,0.091667,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.7495,80.525180,0.0,0.091667,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.3595,89.129032,20.0,0.091667,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.1520,92.495652,0.0,0.075000,0.0,0.0

### Using tile case its mandatory for column name to read dataset in analytics. looks good in power bi,excel,github.

In [7]:
df_CGM5_MV = df_CGM5_MV.round(2)

In [8]:
df_CGM5_MV.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0

### Here we are rounding two decimals between glucose, calories,heart-rate,steps,basal_rate,Bolus_volume_deliverd,carb_inputs,its not  just for  cleaning the data. Its making the data usable, readable,consistent,and meaningful

In [9]:
df_CGM5_MV.isnull().values.any()

np.False_

### we use isnull() to detect missing values in the dataset, because missing values cause major problems in the datait break the calculation, when performing visualization. so if you have null in your column we can drop , fill or interpolate them.

In [13]:
df_CGM5_MV[df_CGM5_MV['Glucose'] > 400]

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
2692,HUPA0001P,2018-06-23T03:00:00,401.00,4.03,76.95,0.0,0.05,0.0,0.0
2698,HUPA0001P,2018-06-23T03:30:00,430.00,4.03,73.78,0.0,0.05,0.0,0.0
2701,HUPA0001P,2018-06-23T03:45:00,418.00,4.03,70.07,0.0,0.05,0.0,0.0
2704,HUPA0001P,2018-06-23T04:00:00,430.00,4.03,75.11,0.0,0.05,0.0,0.0
2707,HUPA0001P,2018-06-23T04:15:00,444.00,4.11,76.34,0.0,0.05,0.5,0.0
2710,HUPA0001P,2018-06-23T04:30:00,439.00,11.35,92.42,83.0,0.05,0.0,0.0
2713,HUPA0001P,2018-06-23T04:45:00,429.00,9.98,81.58,101.0,0.05,0.0,0.0
2716,HUPA0001P,2018-06-23T05:00:00,427.00,4.03,66.69,0.0,0.04,0.0,0.0
11264,HUPA0004P,2018-07-10T09:35:00,403.67,12.30,90.00,13.0,0.07,0.0,0.0
11265,HUPA0004P,2018-07-10T09:40:00,407.33,7.91,89.13,0.0,0.07,0.0,0.0
11266,HUPA0004P,2018-07-10T09:45:00,411.00,9.79,87.66,0.0,0.07,0.0,0.0
11267,HUPA0004P,2018-07-10T09:50:00,409.67,9.92,87.41,5.0,0.07,0.0,0.0
11268,HUPA0004P,2018-07-10T09:55:00,408.33,7.78,87.70,0.0,0.07,0.0,0.0
11269,HUPA0004P,2018-07-10T10:00:00,407.00,7.53,89.50,0.0,0.05,0.0,0.0
11270,HUPA0004P,2018-07-10T10:05:00,404.33,13.68,97.20,41.0,0.05,0.0,0.0
11271,HUPA0004P,2018-07-10T10:10:00,401.67,8.03,89.79,0.0,0.05,0.0,0.0
13062,HUPA0004P,2018-07-16T15:25:00,402.00,8.66,74.14,0.0,0.08,0.0,0.0
13063,HUPA0004P,2018-07-16T15:30:00,406.00,10.29,74.13,54.0,0.08,0.0,0.0
13399,HUPA0004P,2018-07-17T19:30:00,403.00,11.30,72.40,11.0,0.11,0.0,0.0

### I check for glucose > 400 to identify the extreme outliers. These values may sensor errors or true hyperglycemia events.It helps to ensure the data quality before analysis,visualization or data modeling.

In [14]:
df_CGM5_MV[df_CGM5_MV['Glucose'] < 40]

Empty DataFrame
Columns: [Patient_Id, Time, Glucose, Calories, Heart_Rate, Steps, Basal_Rate, Bolus_Volume_Delivered, Carb_Input]
Index: []

### Same here also we check the condition glucose <40 satisfy the above condition, because it missing calibration,sensor dropouts,data corruption, possible hypoglycemia.so checking this condition help to ensure dataset is medically meaningfuland clean.

In [15]:
df_CGM5_MV['Glucose_Outlier'] = (df_CGM5_MV['Glucose'] < 40) | (df_CGM5_MV['Glucose'] > 400)

In [16]:
df_CGM5_MV.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input,Glucose_Outlier
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0,False
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0,False
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0,False
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0,False
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0,False

### We dont always want to delete or change outliers. In medical dataset evey value is important even one extremes. So instead of removing we flag them. A flag is simply true/ false indicator mark rows needing attention.

In [20]:
df_CGM5_MV.to_csv("cleaned_CGM5_MV.csv", index=False)

In [21]:
df_CGM5_MV.to_csv(r"C:/python_hackathon/cleaned_CGM5_MV.csv", index=False)

### Here once done cleaning process , we import the cleaned data in to the flie#

<h2 style="color: purple;"> Patient ID - HUPA0006P, HUPA0007P, HUPA0009P, HUPA0010P, HUPA0018P </h2>

In [2]:
# ============================================================
# Import Libraries
# ============================================================
import pandas as pd
import numpy as np

In [3]:
import pandas as pd
import glob
import os

# Get CSV files from the folder
files_abi = glob.glob(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Abirami\MY_FILES_ABI\*.csv"
)

# Add patient_id column & merge all files
dfs = []

for file in files_abi:
    if os.path.isfile(file):
        df = pd.read_csv(file, sep=';')
        df['patient_id'] = os.path.basename(file).replace('.csv', '')
        dfs.append(df)

df_CGM5_ABI = pd.concat(dfs, ignore_index=True)

# Move patient_id to first column
cols = ['patient_id'] + [col for col in df_CGM5_ABI.columns if col != 'patient_id']
df_CGM5_ABI = df_CGM5_ABI[cols]

df_CGM5_ABI

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0006P,2018-07-09T15:45:00,109.000000,11.23939,70.769231,0.0,0.075000,0.0,0.0
1,HUPA0006P,2018-07-09T15:50:00,107.666667,8.11090,70.189655,5.0,0.075000,0.0,0.0
2,HUPA0006P,2018-07-09T15:55:00,106.333333,6.48872,70.170940,0.0,0.075000,0.0,0.0
3,HUPA0006P,2018-07-09T16:00:00,105.000000,7.06807,72.368421,0.0,0.060833,0.0,0.0
4,HUPA0006P,2018-07-09T16:05:00,122.333333,9.61721,68.219298,6.0,0.060833,0.0,10.0
...,...,...,...,...,...,...,...,...,...
16825,HUPA0018P,2019-07-16T23:25:00,180.333333,6.56343,85.634328,0.0,0.000000,0.0,0.0
16826,HUPA0018P,2019-07-16T23:30:00,188.000000,4.94505,85.459259,0.0,0.000000,0.0,0.0
16827,HUPA0018P,2019-07-16T23:35:00,194.333333,5.12487,84.325581,0.0,0.000000,0.0,0.0
16828,HUPA0018P,2019-07-16T23:40:00,200.666667,9.35064,85.873950,0.0,0.000000,0.0,0.0
16829,HUPA0018P,2019-07-16T23:45:00,207.000000,5.39460,85.753846,0.0,0.000000,0.0,0.0

In [4]:
# ============================================================
#  CHECK: Duplicates
# ============================================================
print("Full duplicate rows:", df_CGM5_ABI.duplicated().sum())
print("Duplicate timestamps per patient:")
print(df_CGM5_ABI.duplicated(subset=['patient_id', 'time']).sum())

Full duplicate rows: 0
Duplicate timestamps per patient:
0

####  Ensured every timestamp per patient is unique, giving accurate time-series analysis.Averages, totals, and trend lines would be distorted by repeated data points.

In [5]:
# ============================================================
#  CHECK: Data Types
# ============================================================
print(df_CGM5_ABI.dtypes)

patient_id                 object
time                       object
glucose                   float64
calories                  float64
heart_rate                float64
steps                     float64
basal_rate                float64
bolus_volume_delivered    float64
carb_input                float64
dtype: object

In [6]:
# FIX: Data Types
df_CGM5_ABI['time'] = pd.to_datetime(df_CGM5_ABI['time'])

num_cols = ['glucose', 'calories', 'heart_rate', 'steps',
            'basal_rate', 'bolus_volume_delivered', 'carb_input']
df_CGM5_ABI[num_cols] = df_CGM5_ABI[num_cols].astype(float)

print("After fix:\n", df_CGM5_ABI.dtypes)

After fix:
 patient_id                        object
time                      datetime64[ns]
glucose                          float64
calories                         float64
heart_rate                       float64
steps                            float64
basal_rate                       float64
bolus_volume_delivered           float64
carb_input                       float64
dtype: object

### The 'Time' column was loaded as plain text and numeric columns had inconsistent types, which prevents any time-based operations or mathematical calculations.Correct types allow sorting by time, calculating time differences, and performing accurate numeric aggregations.Operations like groupby time, plotting trends, or computing mean glucose would throw errors or produce wrong results.¶

In [7]:
# ============================================================
# CHECK: Missing / Null Values
# ============================================================
print("Null values per column:")
print(df_CGM5_ABI.isnull().sum())
print("\nTotal nulls:", df_CGM5_ABI.isnull().sum().sum())

# Check null % per column
print("\nNull percentage:")
print((df_CGM5_ABI.isnull().sum() / len(df_CGM5_ABI) * 100).round(2))

Null values per column:
patient_id                0
time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Total nulls: 0

Null percentage:
patient_id                0.0
time                      0.0
glucose                   0.0
calories                  0.0
heart_rate                0.0
steps                     0.0
basal_rate                0.0
bolus_volume_delivered    0.0
carb_input                0.0
dtype: float64

#### Confirming zero nulls gives confidence that the dataset is complete and no imputation is needed.Any null left in glucose or heart_rate would produce NaN results in all downstream calculations involving those columns.

In [8]:
# ============================================================
# CHECK: Trim & Clean Text
# ============================================================
# Check whitespace in time column
print("Whitespace in time:")
print(df_CGM5_ABI['time'].astype(str).str.contains(r'^\s|\s$').sum())

# Check column name whitespace
print("\nColumn names:")
print([f"'{c}'" for c in df_CGM5_ABI.columns])

# Check patient_id formatting consistency
print("\nUnique patient IDs:")
print(df_CGM5_ABI['patient_id'].unique())

Whitespace in time:
0

Column names:
["'patient_id'", "'time'", "'glucose'", "'calories'", "'heart_rate'", "'steps'", "'basal_rate'", "'bolus_volume_delivered'", "'carb_input'"]

Unique patient IDs:
['HUPA0006P' 'HUPA0007P' 'HUPA0009P' 'HUPA0010P' 'HUPA0018P']

In [9]:
# ============================================================
# Check whitespace in any row values — df_CGM5_ABI
# ============================================================

print("df_CGM5_ABI — Whitespace check in all columns:")
for col in df_CGM5_ABI.columns:
    if df_CGM5_ABI[col].dtype == object:  # only text columns
        count = df_CGM5_ABI[col].astype(str).str.contains(r'^\s|\s$').sum()
        print(f"  {col}: {count} rows with whitespace")

df_CGM5_ABI — Whitespace check in all columns:
  patient_id: 0 rows with whitespace

### No trimming or cleaning required as the data is clean

In [10]:
# ============================================================
# CHECK: Standardize Values
# ============================================================
# Check sort order per patient
print("Is sorted by patient + time:")
sorted_check = df_CGM5_ABI.groupby('patient_id')['time'].is_monotonic_increasing
print(sorted_check)

# Check decimal precision
print("\nSample values:")
print(df_CGM5_ABI[num_cols].head(3))

Is sorted by patient + time:
patient_id
HUPA0006P    True
HUPA0007P    True
HUPA0009P    True
HUPA0010P    True
HUPA0018P    True
Name: time, dtype: bool

Sample values:
      glucose  calories  heart_rate  steps  basal_rate  \
0  109.000000  11.23939   70.769231    0.0       0.075
1  107.666667   8.11090   70.189655    5.0       0.075
2  106.333333   6.48872   70.170940    0.0       0.075

   bolus_volume_delivered  carb_input
0                     0.0         0.0
1                     0.0         0.0
2                     0.0         0.0

In [11]:
# FIX: Round to 2 decimal places
num_cols = ['glucose', 'calories', 'heart_rate', 'steps',
            'basal_rate', 'bolus_volume_delivered', 'carb_input']

df_CGM5_ABI[num_cols] = df_CGM5_ABI[num_cols].round(2)

print("After rounding:")
print(df_CGM5_ABI[num_cols].head(3))
df_CGM5_ABI.head(3)

After rounding:
   glucose  calories  heart_rate  steps  basal_rate  bolus_volume_delivered  \
0   109.00     11.24       70.77    0.0        0.08                     0.0
1   107.67      8.11       70.19    5.0        0.08                     0.0
2   106.33      6.49       70.17    0.0        0.08                     0.0

   carb_input
0         0.0
1         0.0
2         0.0

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0006P,2018-07-09 15:45:00,109.00,11.24,70.77,0.0,0.08,0.0,0.0
1,HUPA0006P,2018-07-09 15:50:00,107.67,8.11,70.19,5.0,0.08,0.0,0.0
2,HUPA0006P,2018-07-09 15:55:00,106.33,6.49,70.17,0.0,0.08,0.0,0.0

#### Data was not guaranteed to be in chronological order after merging, and numeric columns had up to 9 decimal places making the data inconsistent and hard to read.Sorting ensures time-series operations like diff() and interpolation work correctly. Rounding to 2 decimal places standardises precision across all patients.If it is not performed then Time-based calculations like glucose trend detection or interval checks would produce incorrect results on unsorted data. Excessive decimals would cause inconsistency when comparing values across patients.

In [12]:
# ============================================================
# CHECK: Column Names
# ============================================================
print("Current column names:")
print(df_CGM5_ABI.columns.tolist())

Current column names:
['patient_id', 'time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate', 'bolus_volume_delivered', 'carb_input']

In [13]:
# FIX: Rename Columns
df_CGM5_ABI = df_CGM5_ABI.rename(columns={
    'time'                   : 'Time',
    'glucose'                : 'Glucose',
    'calories'               : 'Calories',
    'heart_rate'             : 'Heart_Rate',
    'steps'                  : 'Steps',
    'basal_rate'             : 'Basal_Rate',
    'bolus_volume_delivered' : 'Bolus_Volume_Delivered',
    'carb_input'             : 'Carb_Input'
    
})
print("Renamed:", df_CGM5_ABI.columns.tolist())

Renamed: ['patient_id', 'Time', 'Glucose', 'Calories', 'Heart_Rate', 'Steps', 'Basal_Rate', 'Bolus_Volume_Delivered', 'Carb_Input']

#### Original column names like 'bolus_volume_delivered' were lowercase with underscores and lacked units, making them harder to read in reports and dashboards.Descriptive, consistently capitalised column names improve readability in Visualizations.The raw technical names that are unclear to non-technical stakeholders.

In [14]:
# ============================================================
# Inconsistent Categories
# ============================================================
# Validate zero distributions per patient
print("Zero % per column per patient:")
zero_pct = (
    df_CGM5_ABI.groupby('patient_id')[df_CGM5_ABI.columns[2:]]
    .apply(lambda x: (x == 0).sum() / len(x) * 100)
    .round(1)
)
print(zero_pct)

Zero % per column per patient:
            Glucose  Calories  Heart_Rate  Steps  Basal_Rate  \
patient_id
HUPA0006P       0.0       0.0         0.0   67.8         1.8
HUPA0007P       0.0       0.0         0.0   59.0         6.6
HUPA0009P       0.0       0.0         0.0   58.8         1.4
HUPA0010P       0.0       0.0         0.0   53.4         3.3
HUPA0018P       0.0       0.0         0.0   61.3       100.0

            Bolus_Volume_Delivered  Carb_Input
patient_id
HUPA0006P                     98.0        98.4
HUPA0007P                     97.7        97.9
HUPA0009P                     98.3        98.8
HUPA0010P                     97.4        98.6
HUPA0018P                    100.0       100.0

#### Confirming no categorical columns exist and that zeros are clinically valid prevents unnecessary data modification.Incorrectly treating valid zeros as missing data and replacing them would corrupt clinically meaningful readings like no bolus delivered or no food logged.

In [16]:
# ============================================================
# CHECK: Validate Relationships / Keys
# ============================================================
# Timestamp uniqueness per patient
dup_check = df_CGM5_ABI.duplicated(subset=['patient_id', 'Time']).sum()
print("Duplicate patient+timestamp combinations:", dup_check)

# Row count per patient
print("\nRows per patient:")
print(df_CGM5_ABI['patient_id'].value_counts())

# Time interval check per patient
print("\nTime interval check (should all be 5 min):")
df_CGM5_ABI_sorted = df_CGM5_ABI.sort_values(['patient_id', 'Time'])
intervals = (
    df_CGM5_ABI_sorted.groupby('patient_id')['Time']
    .diff()
    .dropna()
    .value_counts()
)
print(intervals.head(10))

Duplicate patient+timestamp combinations: 0

Rows per patient:
patient_id
HUPA0018P    3895
HUPA0007P    3857
HUPA0009P    3812
HUPA0010P    2976
HUPA0006P    2290
Name: count, dtype: int64

Time interval check (should all be 5 min):
Time
0 days 00:05:00    16825
Name: count, dtype: int64

#### As a time-series dataset, each patient must have unique timestamps and consistent 5-minute intervals. Any break in this structure affects trend analysis and machine learning models.Confirming the dataset is structurally sound  no duplicate keys, no missing intervals, and correct row counts per patient after merging.Duplicate timestamps would cause incorrect joins and aggregations. Irregular time intervals would break any model or visualisation that assumes evenly spaced readings.

In [17]:
# ============================================================
#  Final Summary
# ============================================================
print("Final Shape:", df_CGM5_ABI.shape)
print("\nData Types:\n", df_CGM5_ABI.dtypes)
print("\nNull Values:\n", df_CGM5_ABI.isnull().sum())
print("\nPatients:", df_CGM5_ABI['patient_id'].unique())
df_CGM5_ABI.describe()

Final Shape: (16830, 9)

Data Types:
 patient_id                        object
Time                      datetime64[ns]
Glucose                          float64
Calories                         float64
Heart_Rate                       float64
Steps                            float64
Basal_Rate                       float64
Bolus_Volume_Delivered           float64
Carb_Input                       float64
dtype: object

Null Values:
 patient_id                0
Time                      0
Glucose                   0
Calories                  0
Heart_Rate                0
Steps                     0
Basal_Rate                0
Bolus_Volume_Delivered    0
Carb_Input                0
dtype: int64

Patients: ['HUPA0006P' 'HUPA0007P' 'HUPA0009P' 'HUPA0010P' 'HUPA0018P']

,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
count,16830,16830.000000,16830.000000,16830.000000,16830.000000,16830.000000,16830.000000,16830.000000
mean,2018-11-29 22:16:18.110516992,163.323878,9.380301,76.121116,41.813428,0.060240,0.054743,0.038963
min,2018-07-09 15:45:00,40.000000,4.070000,41.420000,0.000000,0.000000,0.000000,0.000000
25%,2018-09-22 22:21:15,107.330000,4.680000,65.190000,0.000000,0.000000,0.000000,0.000000
50%,2018-09-30 05:40:00,158.330000,6.930000,76.745000,0.000000,0.070000,0.000000,0.000000
75%,2018-11-16 21:28:45,214.000000,11.070000,84.477500,43.000000,0.090000,0.000000,0.000000
max,2019-07-16 23:45:00,438.000000,78.860000,166.330000,682.000000,0.150000,13.300000,10.000000
std,NaN,71.129606,7.285117,14.450585,86.712816,0.039456,0.567493,0.435361

In [18]:
# ============================================================
#  Moving the patient id as first column
# ============================================================
cols = ['patient_id'] + [col for col in df_CGM5_ABI.columns if col != 'patient_id']
df_CGM5_ABI = df_CGM5_ABI[cols]

print(df_CGM5_ABI.columns.tolist())
df_CGM5_ABI.head()

['patient_id', 'Time', 'Glucose', 'Calories', 'Heart_Rate', 'Steps', 'Basal_Rate', 'Bolus_Volume_Delivered', 'Carb_Input']

,patient_id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0006P,2018-07-09 15:45:00,109.00,11.24,70.77,0.0,0.08,0.0,0.0
1,HUPA0006P,2018-07-09 15:50:00,107.67,8.11,70.19,5.0,0.08,0.0,0.0
2,HUPA0006P,2018-07-09 15:55:00,106.33,6.49,70.17,0.0,0.08,0.0,0.0
3,HUPA0006P,2018-07-09 16:00:00,105.00,7.07,72.37,0.0,0.06,0.0,0.0
4,HUPA0006P,2018-07-09 16:05:00,122.33,9.62,68.22,6.0,0.06,0.0,10.0

<h2 style="color: purple;">Data Cleaning and Preprocessing — Patient IDs: HUPA0011P, HUPA0014P, HUPA0015P, HUPA0016P, HUPA0017P</h2>

Data Cleaning and Preprocessing Patient ID - HUPA0011P, HUPA0014P, HUPA0015P, HUPA0016P, HUPA0017P

<h2>Get the correct working folder where the files are present</h2>

In [1]:
%cd "H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Raw files\HUPA-UC Diabetes Dataset

H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Raw files\HUPA-UC Diabetes Dataset

<h2>Check the folder where the files are present:</h2>

In [2]:
import os
os.getcwd()

'H:\\Numpy Ninja\\Python Hackathon\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Raw files\\HUPA-UC Diabetes Dataset'

<h2>Fetch the files using Dataframe:Just we import the dataset into csv files to start the data cleaning process to find the meaningful insights.</h2>

In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn



df_HUPA11 = pd.read_csv(
    "HUPA0011P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)


df_HUPA11

<h2>Create a copy of the original dataset: Here we are creating a copy of the original file before we start the cleaning process</h2>

In [205]:
df_HUPA11Copy= df_HUPA11.copy()
df_HUPA11Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0

<h2>Check for the datatypes of the columns and also null values.</h22>

In [206]:
df_HUPA11.info()
df_HUPA11.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3839 entries, 0 to 3838
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3839 non-null   datetime64[ns]
 1   glucose                 3839 non-null   float64
 2   calories                3839 non-null   float64
 3   heart_rate              3839 non-null   float64
 4   steps                   3839 non-null   float64
 5   basal_rate              3839 non-null   int64
 6   bolus_volume_delivered  3839 non-null   int64
 7   carb_input              3839 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2)
memory usage: 240.1 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

<h2>Add a new column called Patient_id as patient_id column is missing.</h2>

In [207]:
df_HUPA11["patient_id"] = "HUPA011P"
df_HUPA11

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0,HUPA011P
1,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0,HUPA011P
2,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0,HUPA011P
3,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0,HUPA011P
4,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0,HUPA011P
...,...,...,...,...,...,...,...,...,...
3834,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0,HUPA011P
3835,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0,HUPA011P
3836,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0,HUPA011P
3837,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0,HUPA011P
3838,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0,HUPA011P

<h2>Bring the patient_id column to the beginning.</h2>

In [208]:
df_HUPA11 = df_HUPA11[["patient_id"] + [col for col in df_HUPA11.columns if col != "patient_id"]]
df_HUPA11

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA011P,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0
3835,HUPA011P,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0
3836,HUPA011P,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0
3837,HUPA011P,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0
3838,HUPA011P,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0

<h2>Remove whitespaces in the data</h2>

In [209]:
df_HUPA11.columns = df_HUPA11.columns.str.strip()

Capitalize the first letter of each column

In [210]:
df_HUPA11.columns = df_HUPA11.columns.str.capitalize()
df_HUPA11

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.000000,11.55785,79.504348,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.000000,22.28420,95.265487,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.666667,12.55565,107.966387,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.333333,5.07215,90.556338,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.000000,6.90145,83.423729,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.000000,5.40475,63.000000,0.0,0,0,0.0
3835,HUPA011P,2018-11-20 23:30:00,213.000000,6.65200,62.023810,0.0,0,0,0.0
3836,HUPA011P,2018-11-20 23:35:00,212.000000,5.32160,62.977273,0.0,0,0,0.0
3837,HUPA011P,2018-11-20 23:40:00,211.000000,4.73955,72.129630,0.0,0,0,0.0
3838,HUPA011P,2018-11-20 23:45:00,210.000000,8.31500,73.219512,50.0,0,0,0.0

<h2>Check for duplicate records for the same timestamp</h2>

In [211]:
df_HUPA11['Time'].duplicated().sum()

np.int64(0)

<h2>Round the float columns to 2 decimal places</h2>

In [212]:
float_cols = df_HUPA11.select_dtypes(include=['float64']).columns
df_HUPA11[float_cols] = df_HUPA11[float_cols].round(2)
df_HUPA11.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0,0,0.0

<h2>Repeat the same steps for rest of the files too</h2>

<h2>Cleaning for the file HUPA014.csv</h2>

In [201]:
df_HUPA11.head()

,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input,Patient_id
0,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0,0,0.0,HUPA011P
1,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0,0,0.0,HUPA011P
2,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0,0,0.0,HUPA011P
3,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0,0,0.0,HUPA011P
4,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0,0,0.0,HUPA011P

In [20]:

df_HUPA14 = pd.read_csv(
    "HUPA0014P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)


df_HUPA14

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 16:45:00,165.000000,4.49350,71.214286,0.0,0,10.0,5.0
1,2018-11-07 16:50:00,164.666667,4.49350,70.156522,0.0,0,0.0,0.0
2,2018-11-07 16:55:00,164.333333,4.49350,69.077519,0.0,0,0.0,0.0
3,2018-11-07 17:00:00,164.000000,4.49350,69.341270,0.0,0,0.0,0.0
4,2018-11-07 17:05:00,163.666667,4.49350,70.663793,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...
3824,2018-11-20 23:25:00,237.000000,5.21246,86.903226,0.0,0,0.0,0.0
3825,2018-11-20 23:30:00,247.000000,5.12259,86.064516,0.0,0,0.0,0.0
3826,2018-11-20 23:35:00,251.666667,7.27947,83.923077,18.0,0,0.0,0.0
3827,2018-11-20 23:40:00,256.333333,4.49350,76.722222,0.0,0,0.0,0.0
3828,2018-11-20 23:45:00,261.000000,4.49350,75.310345,0.0,0,0.0,0.0

Create a copy of the original Dataset

In [21]:
df_HUPA14Copy= df_HUPA14.copy()
df_HUPA14Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-11-07 16:45:00,165.000000,4.4935,71.214286,0.0,0,10.0,5.0
1,2018-11-07 16:50:00,164.666667,4.4935,70.156522,0.0,0,0.0,0.0
2,2018-11-07 16:55:00,164.333333,4.4935,69.077519,0.0,0,0.0,0.0
3,2018-11-07 17:00:00,164.000000,4.4935,69.341270,0.0,0,0.0,0.0
4,2018-11-07 17:05:00,163.666667,4.4935,70.663793,0.0,0,0.0,0.0

Check for the datatypes of the columns and also null values.

In [22]:
df_HUPA14.info()
df_HUPA14.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3829 entries, 0 to 3828
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3829 non-null   datetime64[ns]
 1   glucose                 3829 non-null   float64
 2   calories                3829 non-null   float64
 3   heart_rate              3829 non-null   float64
 4   steps                   3829 non-null   float64
 5   basal_rate              3829 non-null   int64
 6   bolus_volume_delivered  3829 non-null   float64
 7   carb_input              3829 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 239.4 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Add a new column called Patient_id.

In [23]:
df_HUPA14["patient_id"] = "HUPA014P"
df_HUPA14

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2018-11-07 16:45:00,165.000000,4.49350,71.214286,0.0,0,10.0,5.0,HUPA014P
1,2018-11-07 16:50:00,164.666667,4.49350,70.156522,0.0,0,0.0,0.0,HUPA014P
2,2018-11-07 16:55:00,164.333333,4.49350,69.077519,0.0,0,0.0,0.0,HUPA014P
3,2018-11-07 17:00:00,164.000000,4.49350,69.341270,0.0,0,0.0,0.0,HUPA014P
4,2018-11-07 17:05:00,163.666667,4.49350,70.663793,0.0,0,0.0,0.0,HUPA014P
...,...,...,...,...,...,...,...,...,...
3824,2018-11-20 23:25:00,237.000000,5.21246,86.903226,0.0,0,0.0,0.0,HUPA014P
3825,2018-11-20 23:30:00,247.000000,5.12259,86.064516,0.0,0,0.0,0.0,HUPA014P
3826,2018-11-20 23:35:00,251.666667,7.27947,83.923077,18.0,0,0.0,0.0,HUPA014P
3827,2018-11-20 23:40:00,256.333333,4.49350,76.722222,0.0,0,0.0,0.0,HUPA014P
3828,2018-11-20 23:45:00,261.000000,4.49350,75.310345,0.0,0,0.0,0.0,HUPA014P

Bring the patient_id column to the beginning

In [24]:
df_HUPA14 = df_HUPA14[["patient_id"] + [col for col in df_HUPA14.columns if col != "patient_id"]]
df_HUPA14

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA014P,2018-11-07 16:45:00,165.000000,4.49350,71.214286,0.0,0,10.0,5.0
1,HUPA014P,2018-11-07 16:50:00,164.666667,4.49350,70.156522,0.0,0,0.0,0.0
2,HUPA014P,2018-11-07 16:55:00,164.333333,4.49350,69.077519,0.0,0,0.0,0.0
3,HUPA014P,2018-11-07 17:00:00,164.000000,4.49350,69.341270,0.0,0,0.0,0.0
4,HUPA014P,2018-11-07 17:05:00,163.666667,4.49350,70.663793,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3824,HUPA014P,2018-11-20 23:25:00,237.000000,5.21246,86.903226,0.0,0,0.0,0.0
3825,HUPA014P,2018-11-20 23:30:00,247.000000,5.12259,86.064516,0.0,0,0.0,0.0
3826,HUPA014P,2018-11-20 23:35:00,251.666667,7.27947,83.923077,18.0,0,0.0,0.0
3827,HUPA014P,2018-11-20 23:40:00,256.333333,4.49350,76.722222,0.0,0,0.0,0.0
3828,HUPA014P,2018-11-20 23:45:00,261.000000,4.49350,75.310345,0.0,0,0.0,0.0

Remove whitespaces in the data

In [25]:
df_HUPA14.columns = df_HUPA14.columns.str.strip()

Capitalize the first letter of each column

In [26]:
df_HUPA14.columns = df_HUPA14.columns.str.capitalize()
df_HUPA14

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA014P,2018-11-07 16:45:00,165.000000,4.49350,71.214286,0.0,0,10.0,5.0
1,HUPA014P,2018-11-07 16:50:00,164.666667,4.49350,70.156522,0.0,0,0.0,0.0
2,HUPA014P,2018-11-07 16:55:00,164.333333,4.49350,69.077519,0.0,0,0.0,0.0
3,HUPA014P,2018-11-07 17:00:00,164.000000,4.49350,69.341270,0.0,0,0.0,0.0
4,HUPA014P,2018-11-07 17:05:00,163.666667,4.49350,70.663793,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3824,HUPA014P,2018-11-20 23:25:00,237.000000,5.21246,86.903226,0.0,0,0.0,0.0
3825,HUPA014P,2018-11-20 23:30:00,247.000000,5.12259,86.064516,0.0,0,0.0,0.0
3826,HUPA014P,2018-11-20 23:35:00,251.666667,7.27947,83.923077,18.0,0,0.0,0.0
3827,HUPA014P,2018-11-20 23:40:00,256.333333,4.49350,76.722222,0.0,0,0.0,0.0
3828,HUPA014P,2018-11-20 23:45:00,261.000000,4.49350,75.310345,0.0,0,0.0,0.0

Check for duplicate records for the same timestamp

In [27]:
df_HUPA14['Time'].duplicated().sum()

np.int64(0)

Round the float columns to 2 decimal places

In [28]:
float_cols = df_HUPA14.select_dtypes(include=['float64']).columns
df_HUPA14[float_cols] = df_HUPA14[float_cols].round(2)
df_HUPA14.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA014P,2018-11-07 16:45:00,165.00,4.49,71.21,0.0,0,10.0,5.0
1,HUPA014P,2018-11-07 16:50:00,164.67,4.49,70.16,0.0,0,0.0,0.0
2,HUPA014P,2018-11-07 16:55:00,164.33,4.49,69.08,0.0,0,0.0,0.0
3,HUPA014P,2018-11-07 17:00:00,164.00,4.49,69.34,0.0,0,0.0,0.0
4,HUPA014P,2018-11-07 17:05:00,163.67,4.49,70.66,0.0,0,0.0,0.0

<h2> Cleaning for the file HUPA015.csv</h2>

In [30]:

df_HUPA15 = pd.read_csv(
    "HUPA0015P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)
df_HUPA15

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0
1,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0
2,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0
3,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0
4,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0
...,...,...,...,...,...,...,...,...
3787,2019-04-09 19:50:00,243.666667,6.35100,74.000000,38.0,0,0,0
3788,2019-04-09 19:55:00,241.333333,4.23400,78.102332,0.0,0,0,0
3789,2019-04-09 20:00:00,239.000000,4.23400,82.748787,0.0,0,0,0
3790,2019-04-09 20:05:00,240.000000,4.23400,82.178256,0.0,0,0,0
3791,2019-04-09 20:10:00,241.000000,8.89140,70.629630,14.0,0,0,0

In [31]:
#Create a copy of the original Dataset

df_HUPA15Copy= df_HUPA15.copy()
df_HUPA15Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0
1,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0
2,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0
3,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0
4,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0

In [32]:
#Check for the datatypes of the columns and also null values.

df_HUPA15.info()
df_HUPA15.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3792 entries, 0 to 3791
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3792 non-null   datetime64[ns]
 1   glucose                 3792 non-null   float64
 2   calories                3792 non-null   float64
 3   heart_rate              3792 non-null   float64
 4   steps                   3792 non-null   float64
 5   basal_rate              3792 non-null   int64
 6   bolus_volume_delivered  3792 non-null   int64
 7   carb_input              3792 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(3)
memory usage: 237.1 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

In [33]:
#Add a new column called Patient_id.

df_HUPA15["patient_id"] = "HUPA015P"
df_HUPA15

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0,HUPA015P
1,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0,HUPA015P
2,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0,HUPA015P
3,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0,HUPA015P
4,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0,HUPA015P
...,...,...,...,...,...,...,...,...,...
3787,2019-04-09 19:50:00,243.666667,6.35100,74.000000,38.0,0,0,0,HUPA015P
3788,2019-04-09 19:55:00,241.333333,4.23400,78.102332,0.0,0,0,0,HUPA015P
3789,2019-04-09 20:00:00,239.000000,4.23400,82.748787,0.0,0,0,0,HUPA015P
3790,2019-04-09 20:05:00,240.000000,4.23400,82.178256,0.0,0,0,0,HUPA015P
3791,2019-04-09 20:10:00,241.000000,8.89140,70.629630,14.0,0,0,0,HUPA015P

In [34]:
#Bring the patient_id column to the beginning.

df_HUPA15 = df_HUPA15[["patient_id"] + [col for col in df_HUPA15.columns if col != "patient_id"]]
df_HUPA15

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA015P,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0
1,HUPA015P,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0
2,HUPA015P,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0
3,HUPA015P,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0
4,HUPA015P,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...
3787,HUPA015P,2019-04-09 19:50:00,243.666667,6.35100,74.000000,38.0,0,0,0
3788,HUPA015P,2019-04-09 19:55:00,241.333333,4.23400,78.102332,0.0,0,0,0
3789,HUPA015P,2019-04-09 20:00:00,239.000000,4.23400,82.748787,0.0,0,0,0
3790,HUPA015P,2019-04-09 20:05:00,240.000000,4.23400,82.178256,0.0,0,0,0
3791,HUPA015P,2019-04-09 20:10:00,241.000000,8.89140,70.629630,14.0,0,0,0

In [35]:
#Remove whitespaces in the data

df_HUPA15.columns = df_HUPA15.columns.str.strip()

In [36]:
#Capitalize the first letter of each column

df_HUPA15.columns = df_HUPA15.columns.str.capitalize()
df_HUPA15

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA015P,2019-03-27 16:15:00,60.000000,17.69812,109.162602,15.0,0,0,0
1,HUPA015P,2019-03-27 16:20:00,58.666667,6.77440,89.536585,0.0,0,0,0
2,HUPA015P,2019-03-27 16:25:00,57.333333,6.01228,56.885965,32.0,0,0,0
3,HUPA015P,2019-03-27 16:30:00,56.000000,5.50420,58.721311,0.0,0,0,0
4,HUPA015P,2019-03-27 16:35:00,54.000000,4.65740,58.177966,0.0,0,0,0
...,...,...,...,...,...,...,...,...,...
3787,HUPA015P,2019-04-09 19:50:00,243.666667,6.35100,74.000000,38.0,0,0,0
3788,HUPA015P,2019-04-09 19:55:00,241.333333,4.23400,78.102332,0.0,0,0,0
3789,HUPA015P,2019-04-09 20:00:00,239.000000,4.23400,82.748787,0.0,0,0,0
3790,HUPA015P,2019-04-09 20:05:00,240.000000,4.23400,82.178256,0.0,0,0,0
3791,HUPA015P,2019-04-09 20:10:00,241.000000,8.89140,70.629630,14.0,0,0,0

In [37]:
#Check for duplicate records for the same timestamp

df_HUPA15['Time'].duplicated().sum()

np.int64(0)

In [38]:
#Round the float columns to 2 decimal places

float_cols = df_HUPA15.select_dtypes(include=['float64']).columns
df_HUPA15[float_cols] = df_HUPA15[float_cols].round(2)
df_HUPA15.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA015P,2019-03-27 16:15:00,60.00,17.70,109.16,15.0,0,0,0
1,HUPA015P,2019-03-27 16:20:00,58.67,6.77,89.54,0.0,0,0,0
2,HUPA015P,2019-03-27 16:25:00,57.33,6.01,56.89,32.0,0,0,0
3,HUPA015P,2019-03-27 16:30:00,56.00,5.50,58.72,0.0,0,0,0
4,HUPA015P,2019-03-27 16:35:00,54.00,4.66,58.18,0.0,0,0,0

<h2>Cleaning for the file HUPA016.csv</h2>

In [40]:
#Cleaning for the file HUPA016.csv

df_HUPA16 = pd.read_csv(
    "HUPA0016P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)


df_HUPA16

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0
1,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0
2,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0
3,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0
4,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0
...,...,...,...,...,...,...,...,...
3830,2019-04-09 23:25:00,65.333333,4.656000,75.095238,0.0,0.073333,0.0,0.0
3831,2019-04-09 23:30:00,65.000000,4.842240,86.362205,0.0,0.073333,0.0,0.0
3832,2019-04-09 23:35:00,73.666667,4.749120,76.833333,0.0,0.073333,0.7,2.0
3833,2019-04-09 23:40:00,82.333333,4.749120,76.343284,0.0,0.073333,0.0,0.0
3834,2019-04-09 23:45:00,91.000000,4.656000,75.545455,0.0,0.073333,0.0,0.0

In [41]:
#Create a copy of the original Dataset

df_HUPA16Copy= df_HUPA16.copy()
df_HUPA16Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0
1,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0
2,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0
3,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0
4,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0

In [42]:
#Check for the datatypes of the columns and also null values.

df_HUPA16.info()
df_HUPA16.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3835 entries, 0 to 3834
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3835 non-null   datetime64[ns]
 1   glucose                 3835 non-null   float64
 2   calories                3835 non-null   float64
 3   heart_rate              3835 non-null   float64
 4   steps                   3835 non-null   float64
 5   basal_rate              3835 non-null   float64
 6   bolus_volume_delivered  3835 non-null   float64
 7   carb_input              3835 non-null   float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 239.8 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

In [43]:
#Add a new column called Patient_id.

df_HUPA16["patient_id"] = "HUPA016P"
df_HUPA16

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0,HUPA016P
1,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0,HUPA016P
2,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0,HUPA016P
3,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0,HUPA016P
4,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0,HUPA016P
...,...,...,...,...,...,...,...,...,...
3830,2019-04-09 23:25:00,65.333333,4.656000,75.095238,0.0,0.073333,0.0,0.0,HUPA016P
3831,2019-04-09 23:30:00,65.000000,4.842240,86.362205,0.0,0.073333,0.0,0.0,HUPA016P
3832,2019-04-09 23:35:00,73.666667,4.749120,76.833333,0.0,0.073333,0.7,2.0,HUPA016P
3833,2019-04-09 23:40:00,82.333333,4.749120,76.343284,0.0,0.073333,0.0,0.0,HUPA016P
3834,2019-04-09 23:45:00,91.000000,4.656000,75.545455,0.0,0.073333,0.0,0.0,HUPA016P

In [44]:
#Bring the patient_id column to the beginning.

df_HUPA16 = df_HUPA16[["patient_id"] + [col for col in df_HUPA16.columns if col != "patient_id"]]
df_HUPA16

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA016P,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0
1,HUPA016P,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0
2,HUPA016P,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0
3,HUPA016P,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0
4,HUPA016P,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3830,HUPA016P,2019-04-09 23:25:00,65.333333,4.656000,75.095238,0.0,0.073333,0.0,0.0
3831,HUPA016P,2019-04-09 23:30:00,65.000000,4.842240,86.362205,0.0,0.073333,0.0,0.0
3832,HUPA016P,2019-04-09 23:35:00,73.666667,4.749120,76.833333,0.0,0.073333,0.7,2.0
3833,HUPA016P,2019-04-09 23:40:00,82.333333,4.749120,76.343284,0.0,0.073333,0.0,0.0
3834,HUPA016P,2019-04-09 23:45:00,91.000000,4.656000,75.545455,0.0,0.073333,0.0,0.0

In [45]:
#Remove whitespaces in the data

df_HUPA16.columns = df_HUPA16.columns.str.strip()

In [46]:
#Capitalize the first letter of each column

df_HUPA16.columns = df_HUPA16.columns.str.capitalize()
df_HUPA16

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA016P,2019-03-27 16:15:00,55.000000,5.866560,94.265152,0.0,0.069167,0.0,0.0
1,HUPA016P,2019-03-27 16:20:00,55.333333,5.866560,92.787879,0.0,0.069167,0.0,0.0
2,HUPA016P,2019-03-27 16:25:00,55.666667,5.773440,89.572464,0.0,0.069167,0.0,0.0
3,HUPA016P,2019-03-27 16:30:00,56.000000,22.535040,112.895105,278.0,0.069167,0.0,0.0
4,HUPA016P,2019-03-27 16:35:00,64.666667,34.454401,125.904762,491.0,0.069167,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3830,HUPA016P,2019-04-09 23:25:00,65.333333,4.656000,75.095238,0.0,0.073333,0.0,0.0
3831,HUPA016P,2019-04-09 23:30:00,65.000000,4.842240,86.362205,0.0,0.073333,0.0,0.0
3832,HUPA016P,2019-04-09 23:35:00,73.666667,4.749120,76.833333,0.0,0.073333,0.7,2.0
3833,HUPA016P,2019-04-09 23:40:00,82.333333,4.749120,76.343284,0.0,0.073333,0.0,0.0
3834,HUPA016P,2019-04-09 23:45:00,91.000000,4.656000,75.545455,0.0,0.073333,0.0,0.0

In [47]:
#Check for duplicate records for the same timestamp

df_HUPA16['Time'].duplicated().sum()

np.int64(0)

In [48]:
#Round the float columns to 2 decimal places

float_cols = df_HUPA11.select_dtypes(include=['float64']).columns
df_HUPA16[float_cols] = df_HUPA16[float_cols].round(2)
df_HUPA16.head()

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA016P,2019-03-27 16:15:00,55.00,5.87,94.27,0.0,0.069167,0.0,0.0
1,HUPA016P,2019-03-27 16:20:00,55.33,5.87,92.79,0.0,0.069167,0.0,0.0
2,HUPA016P,2019-03-27 16:25:00,55.67,5.77,89.57,0.0,0.069167,0.0,0.0
3,HUPA016P,2019-03-27 16:30:00,56.00,22.54,112.90,278.0,0.069167,0.0,0.0
4,HUPA016P,2019-03-27 16:35:00,64.67,34.45,125.90,491.0,0.069167,0.0,0.0

<h2>Cleaning for the file HUPA017.csv </h2>

In [217]:
#Cleaning for the file HUPA017.csv

df_HUPA17 = pd.read_csv(
    "HUPA0017P.csv",
    sep=";",
    parse_dates=["time"],
    na_values=["", " ", "NA", "NaN"]
)
df_HUPA17

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0
1,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0
2,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0
3,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0
4,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0
...,...,...,...,...,...,...,...,...
3594,2019-04-09 23:30:00,165.750000,4.77150,81.246461,0.0,0.059,0.0,0.0
3595,2019-04-09 23:35:00,166.833333,4.77150,80.897641,0.0,0.059,0.0,0.0
3596,2019-04-09 23:40:00,167.916667,4.77150,80.548820,0.0,0.059,0.0,0.0
3597,2019-04-09 23:45:00,169.000000,4.96236,80.200000,0.0,0.059,0.0,0.0
3598,2019-04-09 23:50:00,170.083333,8.87499,83.868421,35.0,0.059,0.0,0.0

In [219]:
#Create a copy of the original Dataset

df_HUPA17Copy= df_HUPA17.copy()
df_HUPA17Copy.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0
1,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0
2,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0
3,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0
4,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0

In [220]:
#Check for the datatypes of the columns and also null values.

df_HUPA17.info()
df_HUPA17.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3599 entries, 0 to 3598
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   time                    3599 non-null   datetime64[ns]
 1   glucose                 3599 non-null   float64
 2   calories                3599 non-null   float64
 3   heart_rate              3599 non-null   float64
 4   steps                   3599 non-null   float64
 5   basal_rate              3599 non-null   float64
 6   bolus_volume_delivered  3599 non-null   float64
 7   carb_input              3599 non-null   float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 225.1 KB

time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

In [221]:
#Add a new column called Patient_id.

df_HUPA17["patient_id"] = "HUPA017P"
df_HUPA17

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id
0,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0,HUPA017P
1,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0,HUPA017P
2,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0,HUPA017P
3,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0,HUPA017P
4,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0,HUPA017P
...,...,...,...,...,...,...,...,...,...
3594,2019-04-09 23:30:00,165.750000,4.77150,81.246461,0.0,0.059,0.0,0.0,HUPA017P
3595,2019-04-09 23:35:00,166.833333,4.77150,80.897641,0.0,0.059,0.0,0.0,HUPA017P
3596,2019-04-09 23:40:00,167.916667,4.77150,80.548820,0.0,0.059,0.0,0.0,HUPA017P
3597,2019-04-09 23:45:00,169.000000,4.96236,80.200000,0.0,0.059,0.0,0.0,HUPA017P
3598,2019-04-09 23:50:00,170.083333,8.87499,83.868421,35.0,0.059,0.0,0.0,HUPA017P

In [222]:
#Bring the patient_id column to the beginning.

df_HUPA17 = df_HUPA17[["patient_id"] + [col for col in df_HUPA17.columns if col != "patient_id"]]
df_HUPA17

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA017P,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0
1,HUPA017P,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0
2,HUPA017P,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0
3,HUPA017P,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0
4,HUPA017P,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3594,HUPA017P,2019-04-09 23:30:00,165.750000,4.77150,81.246461,0.0,0.059,0.0,0.0
3595,HUPA017P,2019-04-09 23:35:00,166.833333,4.77150,80.897641,0.0,0.059,0.0,0.0
3596,HUPA017P,2019-04-09 23:40:00,167.916667,4.77150,80.548820,0.0,0.059,0.0,0.0
3597,HUPA017P,2019-04-09 23:45:00,169.000000,4.96236,80.200000,0.0,0.059,0.0,0.0
3598,HUPA017P,2019-04-09 23:50:00,170.083333,8.87499,83.868421,35.0,0.059,0.0,0.0

In [151]:
#Remove whitespaces in the data

df_HUPA17.columns = df_HUPA17.columns.str.strip()

In [223]:
#Capitalize the first letter of each column

df_HUPA17.columns = df_HUPA17.columns.str.capitalize()
df_HUPA17

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA017P,2019-03-28 12:00:00,81.000000,7.15725,91.663934,13.0,0.059,0.0,0.0
1,HUPA017P,2019-03-28 12:05:00,74.666667,8.01612,82.906475,19.0,0.059,0.0,0.0
2,HUPA017P,2019-03-28 12:10:00,68.333333,5.15322,79.400000,48.0,0.059,0.0,0.0
3,HUPA017P,2019-03-28 12:15:00,62.000000,6.29838,78.126050,0.0,0.059,0.0,0.0
4,HUPA017P,2019-03-28 12:20:00,60.000000,9.73386,86.033333,38.0,0.059,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3594,HUPA017P,2019-04-09 23:30:00,165.750000,4.77150,81.246461,0.0,0.059,0.0,0.0
3595,HUPA017P,2019-04-09 23:35:00,166.833333,4.77150,80.897641,0.0,0.059,0.0,0.0
3596,HUPA017P,2019-04-09 23:40:00,167.916667,4.77150,80.548820,0.0,0.059,0.0,0.0
3597,HUPA017P,2019-04-09 23:45:00,169.000000,4.96236,80.200000,0.0,0.059,0.0,0.0
3598,HUPA017P,2019-04-09 23:50:00,170.083333,8.87499,83.868421,35.0,0.059,0.0,0.0

In [224]:
cols_to_round = [
    'Glucose',
    'Calories',
    'Heart_rate',
    'Steps',
    'Bolus_volume_delivered',
    'Carb_input'
]

df_HUPA17[cols_to_round] = df_HUPA17[cols_to_round].round(2)

<h2> Detect the outliers for all the major parameters in each of the files. </h2>

Detect the outliers for all the five patients in each file. For that we give upper limits and lower limits for the parameters which we need to handle and only those files which has outliers will be displayed. For glucose we give the upper limit as 500 and lower limit as 40. For the heart rate, upper limit is 220 and lower limit is 30. Similarly for the other parameters also we fix the upper and lower limits. Any patient whose values show either above or below this range, there might be a sensor error.

In [254]:
def identify_real_outliers(df):
    df['outlier'] = False
    df['outlier_column'] = ""

    for idx, row in df.iterrows():

        # Glucose
        if row['Glucose'] < 40 or row['Glucose'] >500:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Glucose, "

        # Heart rate
        if row['Heart_rate'] < 30 or row['Heart_rate'] > 220:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Heart_rate, "

        # Steps
        if row['Steps'] < 0 or row['Steps'] > 6000:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Steps, "

        # Bolus insulin
        if row['Bolus_volume_delivered'] < 0 or row['Bolus_volume_delivered'] > 25:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Bolus_volume_delivered, "

        # Carb input
        if row['Carb_input'] < 0 or row['Carb_input'] > 200:
            df.at[idx, 'outlier'] = True
            df.at[idx, 'outlier_column'] += "Carb_input, "

    # Print message
    if not df['outlier'].any():
        print("No outliers in the specified columns")
    else:
        print("Outliers found in the specified columns")

    # Return only the outlier rows
    return df[df['outlier'] == True]

In [226]:
all_dfs = {
    "HUPA11": df_HUPA11,
    "HUPA14": df_HUPA14,
    "HUPA15": df_HUPA15,
    "HUPA16": df_HUPA16,
    "HUPA17": df_HUPA17
}

<h2> Checking for the ouliers in each of the files</h2>

In [227]:
outlier_results = {}

for name, df in all_dfs.items():
    print(f"\nChecking outliers for {name}...")
    outlier_results[name] = identify_real_outliers(df)

Checking outliers for HUPA11...
No outliers in the specified columns

Checking outliers for HUPA14...
No outliers in the specified columns

Checking outliers for HUPA15...
No outliers in the specified columns

Checking outliers for HUPA16...
No outliers in the specified columns

Checking outliers for HUPA17...
Outliers found in the specified columns

<h2> Only file HUPA17 has ouliers. The bolus volume delivered is in negative values for 4 records. Generally the bogus volumne delivered cannot be in 
negative.</h2>

In [228]:
outlier_results["HUPA17"]

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input,outlier,outlier_column
324,HUPA017P,2019-03-29 15:00:00,103.0,6.49,84.18,0.0,0.059,-1.0,7.0,True,"Bolus_volume_delivered,"
894,HUPA017P,2019-03-31 14:30:00,84.0,4.77,98.22,0.0,0.059,-1.0,4.0,True,"Bolus_volume_delivered,"
2601,HUPA017P,2019-04-06 12:45:00,134.0,14.60,100.23,84.0,0.059,-3.0,4.0,True,"Bolus_volume_delivered,"
2895,HUPA017P,2019-04-07 13:15:00,97.0,4.77,98.32,0.0,0.059,-1.0,2.5,True,"Bolus_volume_delivered,"

<h2>Converting negative Bogus volume delievered column from negative to 0 for the patient HUPA017P</h2>

In [229]:
df_HUPA17.loc[df_HUPA17['Bolus_volume_delivered'] < 0, 'Bolus_volume_delivered'] = 0

In [230]:
df_HUPA17[df_HUPA17['Bolus_volume_delivered'] < 0]

Empty DataFrame
Columns: [Patient_id, Time, Glucose, Calories, Heart_rate, Steps, Basal_rate, Bolus_volume_delivered, Carb_input, outlier, outlier_column]
Index: []

In [160]:
df_HUPA17[df_HUPA17['outlier_column'].str.contains("Bolus_volume_delivered")]

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input,outlier,outlier_column
324,HUPA017P,2019-03-29 15:00:00,103.0,6.49,84.18,0.0,0.059,0.0,7.0,True,"Bolus_volume_delivered,"
894,HUPA017P,2019-03-31 14:30:00,84.0,4.77,98.22,0.0,0.059,0.0,4.0,True,"Bolus_volume_delivered,"
2601,HUPA017P,2019-04-06 12:45:00,134.0,14.60,100.23,84.0,0.059,0.0,4.0,True,"Bolus_volume_delivered,"
2895,HUPA017P,2019-04-07 13:15:00,97.0,4.77,98.32,0.0,0.059,0.0,2.5,True,"Bolus_volume_delivered,"

<h2>Remove all the outlier and the outlier column</h2>

In [231]:
df_HUPA11 = df_HUPA11.drop(columns=['outlier', 'outlier_column'])

In [232]:
df_HUPA14 = df_HUPA14.drop(columns=['outlier', 'outlier_column'])

In [233]:
df_HUPA15 = df_HUPA15.drop(columns=['outlier', 'outlier_column'])

In [234]:
df_HUPA16 = df_HUPA16.drop(columns=['outlier', 'outlier_column'])

In [235]:
df_HUPA17 = df_HUPA17.drop(columns=['outlier', 'outlier_column'])

<h2>Save all the individual files into 5 cleaned .csv files</h2>

In [243]:
#Save the individual cleaned file to a .csv file

df_HUPA11.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA011_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [244]:
#Save the individual cleaned file to a .csv file

df_HUPA14.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA014_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [245]:
#Save the individual cleaned file to a .csv file

df_HUPA15.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA015_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [246]:
#Save the individual cleaned file to a .csv file

df_HUPA16.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA016_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [247]:
#Save the individual cleaned file to a .csv file

df_HUPA17.to_csv(
    r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\HUPA017_cleaned.csv",
    index=False
)
print("Cleaned .csv file created")

Cleaned .csv file created

In [185]:
df_HUPA14

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA014P,2018-11-07 16:45:00,165.00,4.49,71.21,0.0,0,10.0,5.0
1,HUPA014P,2018-11-07 16:50:00,164.67,4.49,70.16,0.0,0,0.0,0.0
2,HUPA014P,2018-11-07 16:55:00,164.33,4.49,69.08,0.0,0,0.0,0.0
3,HUPA014P,2018-11-07 17:00:00,164.00,4.49,69.34,0.0,0,0.0,0.0
4,HUPA014P,2018-11-07 17:05:00,163.67,4.49,70.66,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3824,HUPA014P,2018-11-20 23:25:00,237.00,5.21,86.90,0.0,0,0.0,0.0
3825,HUPA014P,2018-11-20 23:30:00,247.00,5.12,86.06,0.0,0,0.0,0.0
3826,HUPA014P,2018-11-20 23:35:00,251.67,7.28,83.92,18.0,0,0.0,0.0
3827,HUPA014P,2018-11-20 23:40:00,256.33,4.49,76.72,0.0,0,0.0,0.0
3828,HUPA014P,2018-11-20 23:45:00,261.00,4.49,75.31,0.0,0,0.0,0.0

In [167]:
df_HUPA11

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input,outlier,outlier_column
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0,0,0.0,False,
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0,0,0.0,False,
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0,0,0.0,False,
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0,0,0.0,False,
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0,0,0.0,False,
...,...,...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.00,5.40,63.00,0.0,0,0,0.0,False,
3835,HUPA011P,2018-11-20 23:30:00,213.00,6.65,62.02,0.0,0,0,0.0,False,
3836,HUPA011P,2018-11-20 23:35:00,212.00,5.32,62.98,0.0,0,0,0.0,False,
3837,HUPA011P,2018-11-20 23:40:00,211.00,4.74,72.13,0.0,0,0,0.0,False,
3838,HUPA011P,2018-11-20 23:45:00,210.00,8.32,73.22,50.0,0,0,0.0,False,

In [186]:
df_HUPA16

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA016P,2019-03-27 16:15:00,55.00,5.87,94.27,0.0,0.069167,0.0,0.0
1,HUPA016P,2019-03-27 16:20:00,55.33,5.87,92.79,0.0,0.069167,0.0,0.0
2,HUPA016P,2019-03-27 16:25:00,55.67,5.77,89.57,0.0,0.069167,0.0,0.0
3,HUPA016P,2019-03-27 16:30:00,56.00,22.54,112.90,278.0,0.069167,0.0,0.0
4,HUPA016P,2019-03-27 16:35:00,64.67,34.45,125.90,491.0,0.069167,0.0,0.0
...,...,...,...,...,...,...,...,...,...
3830,HUPA016P,2019-04-09 23:25:00,65.33,4.66,75.10,0.0,0.073333,0.0,0.0
3831,HUPA016P,2019-04-09 23:30:00,65.00,4.84,86.36,0.0,0.073333,0.0,0.0
3832,HUPA016P,2019-04-09 23:35:00,73.67,4.75,76.83,0.0,0.073333,0.7,2.0
3833,HUPA016P,2019-04-09 23:40:00,82.33,4.75,76.34,0.0,0.073333,0.0,0.0
3834,HUPA016P,2019-04-09 23:45:00,91.00,4.66,75.55,0.0,0.073333,0.0,0.0

In [241]:
df_HUPA11

,Patient_id,Time,Glucose,Calories,Heart_rate,Steps,Basal_rate,Bolus_volume_delivered,Carb_input
0,HUPA011P,2018-11-07 15:55:00,75.00,11.56,79.50,135.0,0,0,0.0
1,HUPA011P,2018-11-07 16:00:00,76.00,22.28,95.27,507.0,0,0,0.0
2,HUPA011P,2018-11-07 16:05:00,83.67,12.56,107.97,102.0,0,0,0.0
3,HUPA011P,2018-11-07 16:10:00,91.33,5.07,90.56,0.0,0,0,0.0
4,HUPA011P,2018-11-07 16:15:00,99.00,6.90,83.42,5.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...
3834,HUPA011P,2018-11-20 23:25:00,217.00,5.40,63.00,0.0,0,0,0.0
3835,HUPA011P,2018-11-20 23:30:00,213.00,6.65,62.02,0.0,0,0,0.0
3836,HUPA011P,2018-11-20 23:35:00,212.00,5.32,62.98,0.0,0,0,0.0
3837,HUPA011P,2018-11-20 23:40:00,211.00,4.74,72.13,0.0,0,0,0.0
3838,HUPA011P,2018-11-20 23:45:00,210.00,8.32,73.22,50.0,0,0,0.0

Merge all the five datasets into one single csv file

In [248]:
dfs = [df_HUPA11, df_HUPA14, df_HUPA15, df_HUPA16, df_HUPA17]

In [249]:
merged_df = pd.concat(dfs, ignore_index=True)

In [250]:
merged_df = merged_df.sort_values(by=['Patient_id', 'Time'])

In [253]:
merged_df.to_csv(r"H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Purnima\Cleaned .csv files\All_Patients_Merged.csv", index=False)
print("Saved into one csv file")

Saved into one csv file

<h2 style="color: purple;"> PATIENT_ID -HUPA0019P,HUPA0020P,HUPA0021P,HUPA0022P,HUPA0023P IN TO A SINGLE FILE FOR CLEANING </h2>

In [54]:
import pandas as pd
import glob
import os

# Get 5 CSV files from the folder
cgm_5files_hg = glob.glob("C:/Users/Owner/Downloads/Data_5file/*.csv")

# Add Patient_ID column & merge all 5 files
dfs = []
for file in cgm_5files_hg:
    if os.path.isfile(file):
        df = pd.read_csv(file, sep=';')
        df['patient_id'] = os.path.basename(file).replace('.csv', '')
        dfs.append(df)   # ← this must be inside the IF block

# Merge all files
df_CGM5_hg = pd.concat(dfs, ignore_index=True)

# Move patient_id to first column
cols = ['patient_id'] + [col for col in df_CGM5_hg.columns if col != 'patient_id']
df_CGM5_hg = df_CGM5_hg[cols]

df_CGM5_hg

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0019P,2019-07-03T14:00:00,195.000000,6.14906,60.172414,0.0,0.069,1.0,1.0
1,HUPA0019P,2019-07-03T14:05:00,193.666667,9.74568,64.264706,20.0,0.069,0.0,0.0
2,HUPA0019P,2019-07-03T14:10:00,192.333333,12.76220,75.464286,50.0,0.069,0.0,0.0
3,HUPA0019P,2019-07-03T14:15:00,191.000000,14.96658,76.360000,65.0,0.069,0.0,0.0
4,HUPA0019P,2019-07-03T14:20:00,192.666667,9.28160,76.172414,13.0,0.069,0.0,0.0
...,...,...,...,...,...,...,...,...,...
16853,HUPA0023P,2020-01-30T14:10:00,76.000000,6.72650,67.931818,0.0,0.035,0.0,0.0
16854,HUPA0023P,2020-01-30T14:15:00,76.000000,12.84150,69.116279,39.0,0.035,0.0,0.0
16855,HUPA0023P,2020-01-30T14:20:00,76.333333,6.60420,63.785714,0.0,0.035,0.0,0.0
16856,HUPA0023P,2020-01-30T14:25:00,76.666667,6.84880,69.115385,0.0,0.035,0.0,0.0
16857,HUPA0023P,2020-01-30T14:30:00,77.000000,12.96380,71.150000,20.0,0.035,0.0,0.0

### To improve readability and maintain consistent formatting across the dataset, all column names were converted to Title Case. This ensures that each word in the column name starts with a capital letter, making the dataset easier to understand and more visualization.

In [58]:
# Convert all column names to title case
df_CGM5_hg.columns = df_CGM5_hg.columns.str.title()

# Check Existing datatype of columns
df_CGM5_hg.dtypes

# Convert 'time' column from object to datetime format for time-based operation
df_CGM5_hg['Time'] = pd.to_datetime(df_CGM5_hg['Time'])

# Convert 'steps' column from float64 to int as steps are always whole numbers
df_CGM5_hg['Steps'] = df_CGM5_hg['Steps'].astype(int)

df_CGM5_hg.dtypes

Patient_Id                        object
Time                      datetime64[ns]
Glucose                          float64
Calories                         float64
Heart_Rate                       float64
Steps                              int64
Basal_Rate                       float64
Bolus_Volume_Delivered           float64
Carb_Input                       float64
dtype: object

### To ensure consistency and improve readability in the dataset, all columns with the data type float64 were rounded to 2 decimal places. This is especially useful when working with measurements such as glucose levels, BMI, insulin values, or any continuous numeric data.The code identifies all float64 columns using `select_dtypes()` and then applies the `round(2)` function to those columns only.

In [59]:
# Round all float64 columns to 2 decimal places
float_cols = df_CGM5_hg.select_dtypes(include='float64').columns
df_CGM5_hg[float_cols] = df_CGM5_hg[float_cols].round(2)

df_CGM5_hg.tail()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
16853,HUPA0023P,2020-01-30 14:10:00,76.00,6.73,67.93,0,0.04,0.0,0.0
16854,HUPA0023P,2020-01-30 14:15:00,76.00,12.84,69.12,39,0.04,0.0,0.0
16855,HUPA0023P,2020-01-30 14:20:00,76.33,6.60,63.79,0,0.04,0.0,0.0
16856,HUPA0023P,2020-01-30 14:25:00,76.67,6.85,69.12,0,0.04,0.0,0.0
16857,HUPA0023P,2020-01-30 14:30:00,77.00,12.96,71.15,20,0.04,0.0,0.0

### Duplicate rows can cause incorrect analysis, biased statistics, and misleading results.To ensure data quality, we check for duplicate entries in the dataset.

In [60]:
#Duplicate value check
print("Total duplicates:", df_CGM5_hg.duplicated().sum())

Total duplicates: 0

### Null values (missing data) can affect analysis, calculations, and model performance.To ensure data quality, we checked for missing values in each column of the dataset.

In [61]:
#Null Value
df_CGM5_hg.isnull().sum()

Patient_Id                0
Time                      0
Glucose                   0
Calories                  0
Heart_Rate                0
Steps                     0
Basal_Rate                0
Bolus_Volume_Delivered    0
Carb_Input                0
dtype: int64

### Negative values are not valid for this dataset because variables such as glucose level, insulin dose, steps, BMI, and heart rate cannot logically be negative.To ensure data quality, we checked all columns for negative values and handled them appropriately.

In [62]:
# No column should have negative values
numeric_cols = df_CGM5_hg.select_dtypes(include=['float64', 'int64']).columns
for col in numeric_cols:
    neg = (df_CGM5_hg[col] < 0).sum()
    print(f"{col}: {neg} negative values")

Glucose: 0 negative values
Calories: 0 negative values
Heart_Rate: 0 negative values
Steps: 0 negative values
Basal_Rate: 0 negative values
Bolus_Volume_Delivered: 0 negative values
Carb_Input: 0 negative values

### Whitespace in a dataset can cause issues such as incorrect grouping, mismatched categories, failed merges, and inaccurate analysis.To ensure data consistency, we checked all columns for the presence of whitespace characters (spaces, tabs, newlines).

In [66]:
# Check whitespace
print("Whitespace check in all columns:")
for col in df_CGM5_hg.columns:
    if df_CGM5_hg[col].dtype == object:  # only text columns
        count = df_CGM5_hg[col].astype(str).str.contains(r'^\s|\s$').sum()
        print(f"  {col}: {count} rows with whitespace")

Whitespace check in all columns:
  Patient_Id: 0 rows with whitespace

### To perform accurate time‑series analysis, the dataset must be ordered chronologically for each patient.Sorting ensures that glucose readings, insulin doses, steps, and other measurements follow the correct timeline.

In [64]:
# Sort data by patient and time for proper time series analysis
df_CGM5_hg = df_CGM5_hg.sort_values(['Patient_Id', 'Time']).reset_index(drop=True)
df_CGM5_hg.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0019P,2019-07-03 14:00:00,195.00,6.15,60.17,0,0.07,1.0,1.0
1,HUPA0019P,2019-07-03 14:05:00,193.67,9.75,64.26,20,0.07,0.0,0.0
2,HUPA0019P,2019-07-03 14:10:00,192.33,12.76,75.46,50,0.07,0.0,0.0
3,HUPA0019P,2019-07-03 14:15:00,191.00,14.97,76.36,65,0.07,0.0,0.0
4,HUPA0019P,2019-07-03 14:20:00,192.67,9.28,76.17,13,0.07,0.0,0.0

### SAVE CLEANED FILE TO CSV FILE

df_CGM5_hg.to_csv(
    r"C:/Users/Owner/Desktop/Harshali/DataAnalyst-Numpy Ninja/Python_Hakython/Team2_-PyQueens_-Python-Hackathon-_MAY-2026/Harshali_Datacleaning/Clean-data-fivefile.csv",
    index=False
)
print("Cleaned .csv file created")

<h2 style="color: purple;"> Patient IDs: HUPA0024P, HUPA0025P, HUPA0026P, HUPA0027P, HUPA0028 </h2>

In [11]:
import pandas as pd
import glob
import os

# Get 5 CSV files from the folder
cgm_5files_tm = glob.glob("/Users/tejaswinimode/Desktop/NUMPY/PyHackathon/CGM_5files/*.csv")

# Add Patient_ID column & merge all 5 files 
dfs = []
for file in cgm_5files_tm :
    if os.path.isfile(file):
        df = pd.read_csv(file, sep=';')
        df['patient_id'] = os.path.basename(file).replace('.csv', '')
        dfs.append(df)

df_CGM5_TM = pd.concat(dfs, ignore_index=True)

# Move patient_id to first column
cols = ['patient_id'] + [col for col in df_CGM5_TM.columns if col != 'patient_id']
df_CGM5_TM = df_CGM5_TM[cols]

df_CGM5_TM

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0025P,2020-01-16T13:45:00,108.000000,17.58320,80.828571,54.0,0.000,0.0,0.0
1,HUPA0025P,2020-01-16T13:50:00,103.666667,11.34400,74.729730,22.0,0.000,0.0,0.0
2,HUPA0025P,2020-01-16T13:55:00,99.333333,13.18740,76.444444,14.0,0.000,0.0,0.0
3,HUPA0025P,2020-01-16T14:00:00,95.000000,12.76200,80.151515,17.0,0.000,0.0,0.0
4,HUPA0025P,2020-01-16T14:05:00,98.333333,15.59800,74.952381,71.0,0.000,0.0,0.0
...,...,...,...,...,...,...,...,...,...
238716,HUPA0026P,2020-10-10T23:35:00,156.666667,4.55436,79.600000,0.0,0.052,0.0,0.0
238717,HUPA0026P,2020-10-10T23:40:00,158.333333,4.55436,78.137931,0.0,0.052,0.0,0.0
238718,HUPA0026P,2020-10-10T23:45:00,160.000000,4.21700,75.657143,0.0,0.052,0.0,0.0
238719,HUPA0026P,2020-10-10T23:50:00,159.666667,4.38568,75.096774,0.0,0.052,0.0,0.0
238720,HUPA0026P,2020-10-10T23:55:00,159.333333,4.38568,74.629630,0.0,0.052,0.0,0.0

In [12]:
# Convert all column names to title case
df_CGM5_TM.columns = df_CGM5_TM.columns.str.title()

# Check Existing datatype of columns
df_CGM5_TM.dtypes

# Convert 'time' column from object to datetime format for time-based operation
df_CGM5_TM['Time'] = pd.to_datetime(df_CGM5_TM['Time'])

# Convert 'steps' column from float64 to int as steps are always whole numbers
df_CGM5_TM['Steps'] = df_CGM5_TM['Steps'].astype(int)

df_CGM5_TM.dtypes

Patient_Id                        object
Time                      datetime64[ns]
Glucose                          float64
Calories                         float64
Heart_Rate                       float64
Steps                              int64
Basal_Rate                       float64
Bolus_Volume_Delivered           float64
Carb_Input                       float64
dtype: object

## Check nulls

In [13]:
df_CGM5_TM.isnull().sum() # There are no null values

Patient_Id                0
Time                      0
Glucose                   0
Calories                  0
Heart_Rate                0
Steps                     0
Basal_Rate                0
Bolus_Volume_Delivered    0
Carb_Input                0
dtype: int64

## Round all float64 columns to 2 decimal places

In [14]:
float_cols = df_CGM5_TM.select_dtypes(include='float64').columns
df_CGM5_TM[float_cols] = df_CGM5_TM[float_cols].round(2)


df_CGM5_TM.tail()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
238716,HUPA0026P,2020-10-10 23:35:00,156.67,4.55,79.60,0,0.05,0.0,0.0
238717,HUPA0026P,2020-10-10 23:40:00,158.33,4.55,78.14,0,0.05,0.0,0.0
238718,HUPA0026P,2020-10-10 23:45:00,160.00,4.22,75.66,0,0.05,0.0,0.0
238719,HUPA0026P,2020-10-10 23:50:00,159.67,4.39,75.10,0,0.05,0.0,0.0
238720,HUPA0026P,2020-10-10 23:55:00,159.33,4.39,74.63,0,0.05,0.0,0.0

## Check total number of duplicate rows

In [15]:
print("Total duplicates:", df_CGM5_TM.duplicated().sum())

Total duplicates: 0

## No column should have negative values

In [16]:
numeric_cols = df_CGM5_TM.select_dtypes(include=['float64', 'int64']).columns
for col in numeric_cols:
    neg = (df_CGM5_TM[col] < 0).sum()
    print(f"{col}: {neg} negative values")

Glucose: 0 negative values
Calories: 0 negative values
Heart_Rate: 0 negative values
Steps: 0 negative values
Basal_Rate: 0 negative values
Bolus_Volume_Delivered: 0 negative values
Carb_Input: 0 negative values

## Sort data by patient and time for proper time series analysis

In [17]:
df_CGM5_TM = df_CGM5_TM.sort_values(['Patient_Id', 'Time']).reset_index(drop=True)
df_CGM5_TM.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0024P,2020-01-20 11:30:00,87.00,8.19,67.36,20,0.07,0.0,0.0
1,HUPA0024P,2020-01-20 11:35:00,86.00,17.99,75.25,107,0.07,0.0,0.0
2,HUPA0024P,2020-01-20 11:40:00,85.00,17.41,76.78,123,0.07,0.0,0.0
3,HUPA0024P,2020-01-20 11:45:00,84.00,10.38,83.67,30,0.07,0.0,0.0
4,HUPA0024P,2020-01-20 11:50:00,85.33,14.53,80.29,74,0.07,0.0,0.0

## Save Data into .csv File

In [18]:
df_CGM5_TM.to_csv(
    r"/Users/tejaswinimode/Desktop/NUMPY/PyHackathon/GitHub/Team2_-PyQueens_-Python-Hackathon-_MAY-2026/Tejaswini/CleanedData_TM.csv",
    index=False
)

<h2 style="color: purple;"> Data Cleaning for patient_sleep_demographics files </h2>

In [19]:
import pandas as pd

df_sl = pd.read_csv("/Users/tejaswinimode/Desktop/NUMPY/PyHackathon/CGM_Data/HUPA-UC Diabetes Dataset/T1DM_patient_sleep_demographics_with_race.csv", sep=',',engine = 'python')
df_sl

,Patient_ID,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,HUPA0001P,34,Male,Other,6.3,4.5,80
1,HUPA0002P,49,Male,Hispanic,6.6,4.4,40
2,HUPA0003P,64,Male,Black,5.3,5.2,70
3,HUPA0004P,34,Female,Native American,5.2,6.9,60
4,HUPA0005P,49,Male,Native American,5.8,7.9,30
5,HUPA0006P,35,Male,White,6.6,4.2,60
6,HUPA0007P,67,Male,Native American,7.1,6.0,80
7,HUPA0009P,65,Female,Other,6.6,4.6,40
8,HUPA0010P,22,Male,Asian,7.1,5.5,50
9,HUPA0011P,63,Female,Other,5.6,4.7,60
10,HUPA0014P,56,Male,White,6.4,4.6,30
11,HUPA0015P,33,Female,Other,6.2,6.5,50
12,HUPA0016P,46,Male,Black,5.0,4.6,40
13,HUPA0017P,64,Female,Hispanic,5.8,7.3,50
14,HUPA0018P,20,Female,Native American,5.9,7.1,80
15,HUPA0019P,46,Male,Black,5.3,7.1,30
16,HUPA0020P,29,Male,White,5.4,7.9,70
17,HUPA0021P,30,Female,Black,5.7,5.4,70
18,HUPA0022P,35,Male,Other,7.2,7.5,30
19,HUPA0023P,74,Female,Black,5.1,6.8,40
20,HUPA0024P,53,Male,Asian,5.9,7.5,80
21,HUPA0025P,44,Male,Native American,6.6,4.1,40
22,HUPA0026P,33,Male,Hispanic,6.0,4.7,50
23,HUPA0027P,60,Female,Black,5.5,5.9,60
24,HUPA0028P,62,Male,Black,5.1,7.9,30

## Check Existing datatype of columns

In [20]:
df_sl.dtypes   # data looks clean

Patient_ID                       object
Age                               int64
Gender                           object
Race                             object
Average Sleep Duration (hrs)    float64
Sleep Quality (1-10)            float64
% with Sleep Disturbances         int64
dtype: object