Data Preprocessing - Data Cleaning

PATIENT ID - HUPA0006P

In [2]:
# ============================================================
# Import Libraries
# ============================================================
import pandas as pd
import numpy as np

Loading Data Set

In [46]:
# ============================================================
# 1— Load Dataset HUPA0006P.CSV
# ============================================================
df = pd.read_csv(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Raw files\HUPA-UC Diabetes Dataset\HUPA0006P.csv",
    sep=";"
)

print("Shape:", df.shape)
print("\nColumns:", list(df.columns))
df.head()

Shape: (2290, 8)

Columns: ['time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate', 'bolus_volume_delivered', 'carb_input']

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,2018-07-09T15:45:00,109.00,11.24,70.77,0.00,0.07,0.00,0.00
1,2018-07-09T15:50:00,107.67,8.11,70.19,5.00,0.07,0.00,0.00
2,2018-07-09T15:55:00,106.33,6.49,70.17,0.00,0.07,0.00,0.00
3,2018-07-09T16:00:00,105.00,7.07,72.37,0.00,0.06,0.00,0.00
4,2018-07-09T16:05:00,122.33,9.62,68.22,6.00,0.06,0.00,10.00

Check Duplicate

In [54]:
#============================================================
#CELL 2— CHECK: Duplicates
# ============================================================
print("Full duplicate rows:", df.duplicated().sum())
print("Duplicate timestamps:", df.duplicated(subset='time').sum())

Full duplicate rows: 0
Duplicate timestamps: 0

Fixing Done remains same rows

In [6]:
df = df.drop_duplicates()
df = df.drop_duplicates(subset='time', keep='first').reset_index(drop=True)
print("After fix — Shape:", df.shape)

After fix — Shape: (2290, 8)

CHECK: Data Types

In [7]:
print(df.dtypes)

time                       object
glucose                   float64
calories                  float64
heart_rate                float64
steps                     float64
basal_rate                float64
bolus_volume_delivered    float64
carb_input                float64
dtype: object

In [8]:
df['time'] = pd.to_datetime(df['time'])

num_cols = ['glucose', 'calories', 'heart_rate', 'steps',
            'basal_rate', 'bolus_volume_delivered', 'carb_input']
df[num_cols] = df[num_cols].astype(float)

print("After fix:\n", df.dtypes)

After fix:
 time                      datetime64[ns]
glucose                          float64
calories                         float64
heart_rate                       float64
steps                            float64
basal_rate                       float64
bolus_volume_delivered           float64
carb_input                       float64
dtype: object

CHECK: Missing / Null Values

In [9]:
print("Null values per column:")
print(df.isnull().sum())
print("\nTotal nulls:", df.isnull().sum().sum())

Null values per column:
time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Total nulls: 0

In [10]:
# FIX: Null Values (interpolate if any found)
df[num_cols] = df[num_cols].interpolate(method='linear', limit_direction='both')
print("Nulls after fix:", df.isnull().sum().sum())

Nulls after fix: 0

 CHECK: Trim & Clean Text

In [11]:
#Check for leading/trailing whitespace in time column
print("Whitespace issues in time:")
print(df['time'].astype(str).str.contains(r'^\s|\s$').sum())

# Check column name whitespace
print("\nColumn names:")
print([f"'{c}'" for c in df.columns])

Whitespace issues in time:
0

Column names:
["'time'", "'glucose'", "'calories'", "'heart_rate'", "'steps'", "'basal_rate'", "'bolus_volume_delivered'", "'carb_input'"]

In [12]:
# FIX: Trim Text
df['time'] = pd.to_datetime(df['time'].astype(str).str.strip())
df.columns = df.columns.str.strip()
print("Text trimmed.")

Text trimmed.

CHECK: Standardize Values

In [13]:
# Check if data is sorted by time
is_sorted = df['time'].is_monotonic_increasing
print("Is sorted by time:", is_sorted)

# Check decimal precision
print("\nSample decimal values:")
print(df[num_cols].head(3))

Is sorted by time: True

Sample decimal values:
      glucose  calories  heart_rate  steps  basal_rate  \
0  109.000000  11.23939   70.769231    0.0       0.075
1  107.666667   8.11090   70.189655    5.0       0.075
2  106.333333   6.48872   70.170940    0.0       0.075

   bolus_volume_delivered  carb_input
0                     0.0         0.0
1                     0.0         0.0
2                     0.0         0.0

In [35]:
import pandas as pd

pd.options.display.float_format = '{:.2f}'.format
df.describe()

,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
count,2290,2290.00,2290.00,2290.00,2290.00,2290.00,2290.00,2290.00
mean,2018-07-13 15:07:30,165.11,9.84,65.62,34.01,0.08,0.10,0.10
min,2018-07-09 15:45:00,42.00,5.79,41.42,0.00,0.00,0.00,0.00
25%,2018-07-11 15:26:15,96.00,5.79,56.23,0.00,0.07,0.00,0.00
50%,2018-07-13 15:07:30,146.00,6.49,62.97,0.00,0.08,0.00,0.00
75%,2018-07-15 14:48:45,219.58,10.54,71.69,18.00,0.09,0.00,0.00
max,2018-07-17 14:30:00,399.11,61.87,157.70,626.00,0.11,10.80,10.00
std,NaN,84.45,7.17,14.35,83.94,0.02,0.80,0.81

CHECK: Invalid / Erroneous Values

In [15]:
# ============================================================
# CELL 8 — CHECK: Invalid / Erroneous Values
# ============================================================
# CGM sensor hardware limits: < 40 or > 400 = sensor error only
sensor_errors = df_CGM5_ABI[(df_CGM5_ABI['glucose'] < 40) | (df_CGM5_ABI['glucose'] > 400)]
print("Sensor error rows (outside CGM hardware range):", len(sensor_errors))

# Hypoglycemia events (clinically real — keep)
hypo = df_CGM5_ABI[(df_CGM5_ABI['glucose'] >= 40) & (df_CGM5_ABI['glucose'] < 70)]
print("Hypoglycemia readings (<70 mg/dL):", len(hypo))

# Hyperglycemia events (clinically real — keep)
hyper = df_CGM5_ABI[(df_CGM5_ABI['glucose'] > 180) & (df_CGM5_ABI['glucose'] <= 400)]
print("Hyperglycemia readings (>180 mg/dL):", len(hyper))

Glucose outliers (<40 or >400):
                    time  glucose
2115 2018-07-17 00:00:00   401.00
2116 2018-07-17 00:05:00   406.00
2117 2018-07-17 00:10:00   411.00
2118 2018-07-17 00:15:00   416.00
2119 2018-07-17 00:20:00   423.33
2120 2018-07-17 00:25:00   430.67
2121 2018-07-17 00:30:00   438.00
2122 2018-07-17 00:35:00   430.22
2123 2018-07-17 00:40:00   422.44
2124 2018-07-17 00:45:00   414.67
2125 2018-07-17 00:50:00   406.89

Negative values per column:
  glucose: 0
  calories: 0
  heart_rate: 0
  steps: 0
  basal_rate: 0
  bolus_volume_delivered: 0
  carb_input: 0

Zero heart rate rows: 0

In [92]:
# FIX: Correct Invalid Values
# ============================================================
#  8 — CHECK: HUPA0006P
# ============================================================
sensor_errors = df[(df['glucose'] < 40) | (df['glucose'] > 400)]
print("Sensor error rows:", len(sensor_errors))

hypo = df[(df['glucose'] >= 40) & (df['glucose'] < 70)]
print("Hypoglycemia readings (<70 mg/dL):", len(hypo))

hyper = df[(df['glucose'] > 180) & (df['glucose'] <= 400)]
print("Hyperglycemia readings (>180 mg/dL):", len(hyper))

Sensor error rows: 0
Hypoglycemia readings (<70 mg/dL): 685
Hyperglycemia readings (>180 mg/dL): 1210

In [94]:
# FIX: HUPA0006P
df['glucose_outlier_flag'] = (
    (df['glucose'] < 40) | (df['glucose'] > 400)
).astype(int)

df.loc[df['glucose_outlier_flag'] == 1, 'glucose'] = np.nan
df['glucose'] = df['glucose'].interpolate(method='linear', limit_direction='both').round(2)

print("Sensor errors after fix:", ((df['glucose'] < 40) | (df['glucose'] > 400)).sum())
print("Glucose range:", df['glucose'].min(), "–", df['glucose'].max())
print("Hypoglycemia preserved:", ((df['glucose'] >= 40) & (df['glucose'] < 70)).sum())
print("Hyperglycemia preserved:", ((df['glucose'] > 180) & (df['glucose'] <= 400)).sum())

Sensor errors after fix: 0
Glucose range: 40.0 – 358.0
Hypoglycemia preserved: 685
Hyperglycemia preserved: 1210

checking column names

In [17]:
# ============================================================
# CELL 9 — CHECK: Column Names
# ============================================================
print("Current column names:")
print(df.columns.tolist())

Current column names:
['time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate', 'bolus_volume_delivered', 'carb_input', 'glucose_outlier_flag']

In [18]:
# FIX: Rename Columns
df = df.rename(columns={
    'time'                   : 'Time',
    'glucose'                : 'Glucose',
    'calories'               : 'Calories',
    'heart_rate'             : 'Heart Rate',
    'steps'                  : 'Steps',
    'basal_rate'             : 'Basal Rate',
    'bolus_volume_delivered' : 'Bolus Volume',
    'carb_input'             : 'Carb Input',
    '
})
print("Renamed:", df.columns.tolist())

Renamed: ['Time', 'Glucose', 'Calories', 'Heart Rate', 'Steps', 'Basal Rate', 'Bolus Volume', 'Carb Input', 'glucose_outlier_flag']

CHECK: Irrelevant Columns

In [88]:
print("All columns:")
print(df.columns.tolist())
print("\nOutlier flag column value counts:")
print(df['glucose_outlier_flag'].value_counts())

All columns:
['time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate', 'bolus_volume_delivered', 'carb_input', 'patient_id', 'glucose_outlier_flag']

Outlier flag column value counts:
glucose_outlier_flag
0    3895
Name: count, dtype: int64

CELL 11 — CHECK: Inconsistent Categories

In [21]:
print("Zero value counts per column:")
for col in df.columns[1:]:
    zeros = (df[col] == 0).sum()
    pct = round(zeros / len(df) * 100, 1)
    print(f"  {col}: {zeros} zeros ({pct}%)")

Zero value counts per column:
  Glucose: 0 zeros (0.0%)
  Calories: 0 zeros (0.0%)
  Heart Rate: 0 zeros (0.0%)
  Steps: 1553 zeros (67.8%)
  Basal Rate: 42 zeros (1.8%)
  Bolus Volume: 2244 zeros (98.0%)
  Carb Input: 2253 zeros (98.4%)

In [22]:
# No fix needed — zeros are clinically valid
# (patient not moving = 0 steps, no bolus given = 0 bolus_units)
print("No fix required. Zeros are valid in this dataset.")

No fix required. Zeros are valid in this dataset.

CHECK: Validate Relationships / Keys

In [28]:
# ============================================================
# CELL 12 — CHECK: Validate Relationships / Keys
# ============================================================
print("Unique timestamps:", df['Time'].nunique(), "of", len(df))
print("Duplicate timestamps:", df.duplicated(subset='Time').sum())

diffs = df['Time'].diff().dropna()
print("\nTime interval check:")
print(diffs.value_counts())

Unique timestamps: 2290 of 2290
Duplicate timestamps: 0

Time interval check:
Time
0 days 00:05:00    2289
Name: count, dtype: int64

In [30]:
# No fix needed if all intervals = 5 min and no duplicates
print("Timestamp validation passed." if df.duplicated(subset='Time').sum() == 0 else "Fix needed.")

Timestamp validation passed.

Final Summary

In [31]:
# ============================================================
# CELL 13 — Final Summary
# ============================================================
print("Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nNull Values:\n", df.isnull().sum())
print("\nDescriptive Stats:")
df.describe()

Shape: (2290, 8)

Data Types:
 Time            datetime64[ns]
Glucose                float64
Calories               float64
Heart Rate             float64
Steps                  float64
Basal Rate             float64
Bolus Volume           float64
Carb Input             float64
dtype: object

Null Values:
 Time            0
Glucose         0
Calories        0
Heart Rate      0
Steps           0
Basal Rate      0
Bolus Volume    0
Carb Input      0
dtype: int64

Descriptive Stats:

,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
count,2290,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000,2290.000000
mean,2018-07-13 15:07:30,165.107017,9.843834,65.619393,34.008297,0.076646,0.099039,0.097817
min,2018-07-09 15:45:00,42.000000,5.790000,41.420000,0.000000,0.000000,0.000000,0.000000
25%,2018-07-11 15:26:15,96.000000,5.790000,56.225000,0.000000,0.070000,0.000000,0.000000
50%,2018-07-13 15:07:30,146.000000,6.490000,62.965000,0.000000,0.080000,0.000000,0.000000
75%,2018-07-15 14:48:45,219.585000,10.540000,71.687500,18.000000,0.090000,0.000000,0.000000
max,2018-07-17 14:30:00,399.110000,61.870000,157.700000,626.000000,0.110000,10.800000,10.000000
std,NaN,84.452280,7.173064,14.345908,83.938115,0.018611,0.797489,0.813170

,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
count,2290,2290.00,2290.00,2290.00,2290.00,2290.00,2290.00,2290.00
mean,2018-07-13 15:07:30,165.11,9.84,65.62,34.01,0.08,0.10,0.10
min,2018-07-09 15:45:00,42.00,5.79,41.42,0.00,0.00,0.00,0.00
25%,2018-07-11 15:26:15,96.00,5.79,56.23,0.00,0.07,0.00,0.00
50%,2018-07-13 15:07:30,146.00,6.49,62.97,0.00,0.08,0.00,0.00
75%,2018-07-15 14:48:45,219.58,10.54,71.69,18.00,0.09,0.00,0.00
max,2018-07-17 14:30:00,399.11,61.87,157.70,626.00,0.11,10.80,10.00
std,NaN,84.45,7.17,14.35,83.94,0.02,0.80,0.81

In [ ]:
Adding the Patient ID as first Column

In [39]:
# ============================================================
# CELL 14 — Adding the Patient ID as first Column
# ============================================================
df.insert(0, 'Patient ID', 'HUPA006', allow_duplicates=True)

In [40]:
df.head()

,Patient ID,Patient ID,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
0,HUPA006,HUPA006,2018-07-09 15:45:00,109.00,11.24,70.77,0.00,0.08,0.00,0.00
1,HUPA006,HUPA006,2018-07-09 15:50:00,107.67,8.11,70.19,5.00,0.08,0.00,0.00
2,HUPA006,HUPA006,2018-07-09 15:55:00,106.33,6.49,70.17,0.00,0.08,0.00,0.00
3,HUPA006,HUPA006,2018-07-09 16:00:00,105.00,7.07,72.37,0.00,0.06,0.00,0.00
4,HUPA006,HUPA006,2018-07-09 16:05:00,122.33,9.62,68.22,6.00,0.06,0.00,10.00

In [41]:
df.drop(columns=['Patient ID'], inplace=True)
df.insert(0, 'Patient ID', 'HUPA006')

In [42]:
df.head()

,Patient ID,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
0,HUPA006,2018-07-09 15:45:00,109.00,11.24,70.77,0.00,0.08,0.00,0.00
1,HUPA006,2018-07-09 15:50:00,107.67,8.11,70.19,5.00,0.08,0.00,0.00
2,HUPA006,2018-07-09 15:55:00,106.33,6.49,70.17,0.00,0.08,0.00,0.00
3,HUPA006,2018-07-09 16:00:00,105.00,7.07,72.37,0.00,0.06,0.00,0.00
4,HUPA006,2018-07-09 16:05:00,122.33,9.62,68.22,6.00,0.06,0.00,10.00

Save Cleaned File

In [96]:
# ============================================================
# CELL 15 — Save Cleaned File
# ============================================================
df.to_csv(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Abirami\HUPA0006P_cleaned.csv",
    index=False
)
print("Saved successfully!")

Saved successfully!

==================================================================================================
1.LOADED 4 FILES HUPA0007P ,HUPA0009P,HUPA0010P,HUPA0018P IN TO A SINGLE FILE FOR FURTHER CLEANING
==================================================================================================

In [83]:
import pandas as pd
import glob
import os

# Get CSV files from the folder
files_abi = glob.glob(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Abirami\MY_FILES_ABI\*.csv"
)

# Add patient_id column & merge all files
dfs = []

for file in files_abi:
    if os.path.isfile(file):
        df = pd.read_csv(file, sep=';')
        df['patient_id'] = os.path.basename(file).replace('.csv', '')
        dfs.append(df)

df_CGM5_ABI = pd.concat(dfs, ignore_index=True)

# Move patient_id to first column
cols = ['patient_id'] + [col for col in df_CGM5_ABI.columns if col != 'patient_id']
df_CGM5_ABI = df_CGM5_ABI[cols]

df_CGM5_ABI

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0006P,2018-07-09T15:45:00,109.00,11.24,70.77,0.00,0.07,0.00,0.00
1,HUPA0006P,2018-07-09T15:50:00,107.67,8.11,70.19,5.00,0.07,0.00,0.00
2,HUPA0006P,2018-07-09T15:55:00,106.33,6.49,70.17,0.00,0.07,0.00,0.00
3,HUPA0006P,2018-07-09T16:00:00,105.00,7.07,72.37,0.00,0.06,0.00,0.00
4,HUPA0006P,2018-07-09T16:05:00,122.33,9.62,68.22,6.00,0.06,0.00,10.00
...,...,...,...,...,...,...,...,...,...
16825,HUPA0018P,2019-07-16T23:25:00,180.33,6.56,85.63,0.00,0.00,0.00,0.00
16826,HUPA0018P,2019-07-16T23:30:00,188.00,4.95,85.46,0.00,0.00,0.00,0.00
16827,HUPA0018P,2019-07-16T23:35:00,194.33,5.12,84.33,0.00,0.00,0.00,0.00
16828,HUPA0018P,2019-07-16T23:40:00,200.67,9.35,85.87,0.00,0.00,0.00,0.00
16829,HUPA0018P,2019-07-16T23:45:00,207.00,5.39,85.75,0.00,0.00,0.00,0.00

2— CHECK: Duplicates

In [60]:
# ============================================================
#  2 — CHECK: Duplicates
# ============================================================
print("Full duplicate rows:", df_CGM5_ABI.duplicated().sum())
print("Duplicate timestamps per patient:")
print(df_CGM5_ABI.duplicated(subset=['patient_id', 'time']).sum())

Full duplicate rows: 0
Duplicate timestamps per patient:
0

In [61]:
# FIX: Duplicates
df_CGM5_ABI = df_CGM5_ABI.drop_duplicates()
df_CGM5_ABI = df_CGM5_ABI.drop_duplicates(subset=['patient_id', 'time'], keep='first').reset_index(drop=True)
print("After fix — Shape:", df_CGM5_ABI.shape)

After fix — Shape: (14540, 9)

 3-CHECK: Data Types

In [62]:
# ============================================================
# 3 — CHECK: Data Types
# ============================================================
print(df_CGM5_ABI.dtypes)

patient_id                 object
time                       object
glucose                   float64
calories                  float64
heart_rate                float64
steps                     float64
basal_rate                float64
bolus_volume_delivered    float64
carb_input                float64
dtype: object

In [63]:
# FIX: Data Types
df_CGM5_ABI['time'] = pd.to_datetime(df_CGM5_ABI['time'])

num_cols = ['glucose', 'calories', 'heart_rate', 'steps',
            'basal_rate', 'bolus_volume_delivered', 'carb_input']
df_CGM5_ABI[num_cols] = df_CGM5_ABI[num_cols].astype(float)

print("After fix:\n", df_CGM5_ABI.dtypes)

After fix:
 patient_id                        object
time                      datetime64[ns]
glucose                          float64
calories                         float64
heart_rate                       float64
steps                            float64
basal_rate                       float64
bolus_volume_delivered           float64
carb_input                       float64
dtype: object

4-CHECK: Missing / Null Values

In [64]:
# ============================================================
# 4 — CHECK: Missing / Null Values
# ============================================================
print("Null values per column:")
print(df_CGM5_ABI.isnull().sum())
print("\nTotal nulls:", df_CGM5_ABI.isnull().sum().sum())

# Check null % per column
print("\nNull percentage:")
print((df_CGM5_ABI.isnull().sum() / len(df_CGM5_ABI) * 100).round(2))

Null values per column:
patient_id                0
time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Total nulls: 0

Null percentage:
patient_id               0.00
time                     0.00
glucose                  0.00
calories                 0.00
heart_rate               0.00
steps                    0.00
basal_rate               0.00
bolus_volume_delivered   0.00
carb_input               0.00
dtype: float64

In [65]:
# FIX: Interpolate nulls per patient (so patient boundaries don't mix)
df_CGM5_ABI[num_cols] = (
    df_CGM5_ABI.groupby('patient_id')[num_cols]
    .transform(lambda x: x.interpolate(method='linear', limit_direction='both'))
)
print("Nulls after fix:", df_CGM5_ABI.isnull().sum().sum())

Nulls after fix: 0

5- CHECK: Trim & Clean Text

In [66]:
# ============================================================
# 5 — CHECK: Trim & Clean Text
# ============================================================
# Check whitespace in time column
print("Whitespace in time:")
print(df_CGM5_ABI['time'].astype(str).str.contains(r'^\s|\s$').sum())

# Check column name whitespace
print("\nColumn names:")
print([f"'{c}'" for c in df_CGM5_ABI.columns])

# Check patient_id formatting consistency
print("\nUnique patient IDs:")
print(df_CGM5_ABI['patient_id'].unique())

Whitespace in time:
0

Column names:
["'patient_id'", "'time'", "'glucose'", "'calories'", "'heart_rate'", "'steps'", "'basal_rate'", "'bolus_volume_delivered'", "'carb_input'"]

Unique patient IDs:
['HUPA0007P' 'HUPA0009P' 'HUPA0010P' 'HUPA0018P']

In [67]:
# FIX: Trim Text
df_CGM5_ABI['time'] = pd.to_datetime(df_CGM5_ABI['time'].astype(str).str.strip())
df_CGM5_ABI.columns = df_CGM5_ABI.columns.str.strip()
df_CGM5_ABI['patient_id'] = df_CGM5_ABI['patient_id'].str.strip().str.upper()
print("Text trimmed.")
print("Patient IDs after fix:", df_CGM5_ABI['patient_id'].unique())

Text trimmed.
Patient IDs after fix: ['HUPA0007P' 'HUPA0009P' 'HUPA0010P' 'HUPA0018P']

6-CHECK: Standardize Values

In [68]:
# ============================================================
# 6- — CHECK: Standardize Values
# ============================================================
# Check sort order per patient
print("Is sorted by patient + time:")
sorted_check = df_CGM5_ABI.groupby('patient_id')['time'].is_monotonic_increasing
print(sorted_check)

# Check decimal precision
print("\nSample values:")
print(df_CGM5_ABI[num_cols].head(3))

Is sorted by patient + time:
patient_id
HUPA0007P    True
HUPA0009P    True
HUPA0010P    True
HUPA0018P    True
Name: time, dtype: bool

Sample values:
   glucose  calories  heart_rate  steps  basal_rate  bolus_volume_delivered  \
0    90.04     14.55       70.52  77.00        0.07                    0.00
1    85.75     17.32       78.50  62.00        0.07                    0.00
2    81.46     12.89       73.06  16.00        0.07                    0.00

   carb_input
0        0.00
1        0.00
2        0.00

In [69]:
# FIX: Sort and Round
df_CGM5_ABI = df_CGM5_ABI.sort_values(['patient_id', 'time']).reset_index(drop=True)
df_CGM5_ABI[num_cols] = df_CGM5_ABI[num_cols].round(2)
print("Sorted and rounded.")
df_CGM5_ABI.head(3)

Sorted and rounded.

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0007P,2018-09-19 14:25:00,90.04,14.55,70.52,77.00,0.07,0.00,0.00
1,HUPA0007P,2018-09-19 14:30:00,85.75,17.32,78.50,62.00,0.07,0.00,0.00
2,HUPA0007P,2018-09-19 14:35:00,81.46,12.89,73.06,16.00,0.07,0.00,0.00

7-CHECK: Column Names

In [ ]:
# ============================================================
# 7 — CHECK: Column Names
# ============================================================
print("Current column names:")
print(df_CGM5_ABI.columns.tolist())

In [72]:
# FIX: Rename Columns
df_CGM5_ABI = df_CGM5_ABI.rename(columns={
    'time'                   : 'Time',
    'glucose'                : 'Glucose',
    'calories'               : 'Calories',
    'heart_rate'             : 'Heart Rate',
    'steps'                  : 'Steps',
    'basal_rate'             : 'Basal Rate',
    'bolus_volume_delivered' : 'Bolus Volume',
    'carb_input'             : 'Carb Input',
    
})
print("Renamed:", df_CGM5_ABI.columns.tolist())

Renamed: ['patient_id', 'Time', 'Glucose', 'Calories', 'Heart Rate', 'Steps', 'Basal Rate', 'Bolus Volume', 'Carb Input']

Inconsistent Categories

In [84]:
# ============================================================
# 8-Inconsistent Categories
# ============================================================
# Validate zero distributions per patient
print("Zero % per column per patient:")
zero_pct = (
    df_CGM5_ABI.groupby('patient_id')[df_CGM5_ABI.columns[2:]]
    .apply(lambda x: (x == 0).sum() / len(x) * 100)
    .round(1)
)
print(zero_pct)

Zero % per column per patient:
            glucose  calories  heart_rate  steps  basal_rate  \
patient_id
HUPA0006P      0.00      0.00        0.00  67.80        1.80
HUPA0007P      0.00      0.00        0.00  59.00        6.60
HUPA0009P      0.00      0.00        0.00  58.80        1.40
HUPA0010P      0.00      0.00        0.00  53.40        3.30
HUPA0018P      0.00      0.00        0.00  61.30      100.00

            bolus_volume_delivered  carb_input
patient_id
HUPA0006P                    98.00       98.40
HUPA0007P                    97.70       97.90
HUPA0009P                    98.30       98.80
HUPA0010P                    97.40       98.60
HUPA0018P                   100.00      100.00

In [85]:
# No fix needed — zeros are clinically valid
print("No fix required.")

No fix required.

In [78]:
# ============================================================
# 9- CHECK: Validate Relationships / Keys
# ============================================================
# Timestamp uniqueness per patient
dup_check = df_CGM5_ABI.duplicated(subset=['patient_id', 'Time']).sum()
print("Duplicate patient+timestamp combinations:", dup_check)

# Row count per patient
print("\nRows per patient:")
print(df_CGM5_ABI['patient_id'].value_counts())

# Time interval check per patient
print("\nTime interval check (should all be 5 min):")
df_CGM5_ABI_sorted = df_CGM5_ABI.sort_values(['patient_id', 'Time'])
intervals = (
    df_CGM5_ABI_sorted.groupby('patient_id')['Time']
    .diff()
    .dropna()
    .value_counts()
)
print(intervals.head(10))

Duplicate patient+timestamp combinations: 0

Rows per patient:
patient_id
HUPA0018P    3895
HUPA0007P    3857
HUPA0009P    3812
HUPA0010P    2976
Name: count, dtype: int64

Time interval check (should all be 5 min):
Time
0 days 00:05:00    14536
Name: count, dtype: int64

In [79]:
# No fix needed if all intervals = 5 min
print("Validation passed." if dup_check == 0 else "Fix required.")

Validation passed.

In [81]:
# ============================================================
# 10— Final Summary
# ============================================================
print("Final Shape:", df_CGM5_ABI.shape)
print("\nData Types:\n", df_CGM5_ABI.dtypes)
print("\nNull Values:\n", df_CGM5_ABI.isnull().sum())
print("\nPatients:", df_CGM5_ABI['patient_id'].unique())
df_CGM5_ABI.describe()

Final Shape: (14540, 9)

Data Types:
 patient_id              object
Time            datetime64[ns]
Glucose                float64
Calories               float64
Heart Rate             float64
Steps                  float64
Basal Rate             float64
Bolus Volume           float64
Carb Input             float64
dtype: object

Null Values:
 patient_id      0
Time            0
Glucose         0
Calories        0
Heart Rate      0
Steps           0
Basal Rate      0
Bolus Volume    0
Carb Input      0
dtype: int64

Patients: ['HUPA0007P' 'HUPA0009P' 'HUPA0010P' 'HUPA0018P']

,Time,Glucose,Calories,Heart Rate,Steps,Basal Rate,Bolus Volume,Carb Input
count,14540,14540.00,14540.00,14540.00,14540.00,14540.00,14540.00,14540.00
mean,2018-12-21 20:48:20.900962816,163.03,9.31,77.78,43.04,0.06,0.05,0.03
min,2018-09-19 14:25:00,40.00,4.07,43.93,0.00,0.00,0.00,0.00
25%,2018-09-25 21:55:00,109.86,4.59,68.00,0.00,0.00,0.00,0.00
50%,2018-10-02 05:22:30,159.62,6.93,78.44,0.00,0.07,0.00,0.00
75%,2019-07-04 08:51:15,213.41,11.15,85.64,47.00,0.09,0.00,0.00
max,2019-07-16 23:45:00,416.00,78.86,166.33,682.00,0.15,13.30,8.50
std,NaN,68.74,7.30,13.76,87.08,0.04,0.52,0.34

In [91]:
df.head()

,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input,patient_id,glucose_outlier_flag
0,2019-07-03T11:15:00,108.00,4.59,64.46,0.00,0,0,0,HUPA0018P,0
1,2019-07-03T11:20:00,105.33,4.68,65.05,0.00,0,0,0,HUPA0018P,0
2,2019-07-03T11:25:00,102.67,6.38,66.86,0.00,0,0,0,HUPA0018P,0
3,2019-07-03T11:30:00,100.00,6.02,67.16,9.00,0,0,0,HUPA0018P,0
4,2019-07-03T11:35:00,97.67,6.02,65.79,19.00,0,0,0,HUPA0018P,0

checking for outliers

In [89]:
# ============================================================
#  CHECK: df_CGM5_ABI (HUPA0007P, 0009P, 0010P, 0018P) outliers
# ============================================================
sensor_errors = df_CGM5_ABI[(df_CGM5_ABI['glucose'] < 40) | (df_CGM5_ABI['glucose'] > 400)]
print("Sensor error rows:", len(sensor_errors))
print("\nSensor errors per patient:")
print(sensor_errors.groupby('patient_id').size())

hypo = df_CGM5_ABI[(df_CGM5_ABI['glucose'] >= 40) & (df_CGM5_ABI['glucose'] < 70)]
print("\nHypoglycemia readings (<70 mg/dL):", len(hypo))
print(hypo.groupby('patient_id').size())

hyper = df_CGM5_ABI[(df_CGM5_ABI['glucose'] > 180) & (df_CGM5_ABI['glucose'] <= 400)]
print("\nHyperglycemia readings (>180 mg/dL):", len(hyper))
print(hyper.groupby('patient_id').size())

Sensor error rows: 17

Sensor errors per patient:
patient_id
HUPA0006P    11
HUPA0010P     6
dtype: int64

Hypoglycemia readings (<70 mg/dL): 1476
patient_id
HUPA0006P    198
HUPA0007P    345
HUPA0010P    248
HUPA0018P    685
dtype: int64

Hyperglycemia readings (>180 mg/dL): 6478
patient_id
HUPA0006P     798
HUPA0007P    1743
HUPA0009P    2232
HUPA0010P     495
HUPA0018P    1210
dtype: int64

11-checking for outliers

In [90]:
# FIX: df_CGM5_ABI — grouped by patient to avoid boundary bleed
df_CGM5_ABI['glucose_outlier_flag'] = (
    (df_CGM5_ABI['glucose'] < 40) | (df_CGM5_ABI['glucose'] > 400)
).astype(int)

df_CGM5_ABI.loc[df_CGM5_ABI['glucose_outlier_flag'] == 1, 'glucose'] = np.nan

df_CGM5_ABI['glucose'] = (
    df_CGM5_ABI.groupby('patient_id')['glucose']
    .transform(lambda x: x.interpolate(method='linear', limit_direction='both'))
    .round(2)
)

print("Sensor errors after fix:", ((df_CGM5_ABI['glucose'] < 40) | (df_CGM5_ABI['glucose'] > 400)).sum())
print("Glucose range:", df_CGM5_ABI['glucose'].min(), "–", df_CGM5_ABI['glucose'].max())
print("\nPer patient — Hypoglycemia preserved:")
print(df_CGM5_ABI[(df_CGM5_ABI['glucose'] >= 40) & (df_CGM5_ABI['glucose'] < 70)].groupby('patient_id').size())
print("\nPer patient — Hyperglycemia preserved:")
print(df_CGM5_ABI[(df_CGM5_ABI['glucose'] > 180) & (df_CGM5_ABI['glucose'] <= 400)].groupby('patient_id').size())

Sensor errors after fix: 0
Glucose range: 40.0 – 399.11

Per patient — Hypoglycemia preserved:
patient_id
HUPA0006P    198
HUPA0007P    345
HUPA0010P    248
HUPA0018P    685
dtype: int64

Per patient — Hyperglycemia preserved:
patient_id
HUPA0006P     809
HUPA0007P    1743
HUPA0009P    2232
HUPA0010P     501
HUPA0018P    1210
dtype: int64