# <h1 align="center"> Data Preprocessingand cleaning of file T1DM_patient_sleep_demographics_with_race </h1>

In [6]:
%cd "H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Final cleaned csv files\Final cleaned csv files"

H:\Numpy Ninja\Python Hackathon\Team2_ PyQueens_ Python Hackathon _MAY 2026\Team2_ PyQueens_ Python Hackathon _MAY 2026\Final cleaned csv files\Final cleaned csv files

In [7]:
import os
os.getcwd()

'H:\\Numpy Ninja\\Python Hackathon\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Team2_ PyQueens_ Python Hackathon _MAY 2026\\Final cleaned csv files\\Final cleaned csv files'

In [8]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn

In [9]:
df_slp=pd.read_csv("T1DM_patient_sleep_demographics_with_race.csv")
df_slp.head()

,Patient_ID,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,HUPA0001P,34,Male,Other,6.3,4.5,80
1,HUPA0002P,49,Male,Hispanic,6.6,4.4,40
2,HUPA0003P,64,Male,Black,5.3,5.2,70
3,HUPA0004P,34,Female,Native American,5.2,6.9,60
4,HUPA0005P,49,Male,Native American,5.8,7.9,30

In [13]:
df_slp.columns = df_slp.columns.str.replace('_', ' ').str.title().str.replace(' ', '_')
df_slp.head()

,Patient_Id,Age,Gender,Race,Average_Sleep_Duration_(Hrs),Sleep_Quality_(1-10),%_With_Sleep_Disturbances
0,HUPA0001P,34,Male,Other,6.3,4.5,80
1,HUPA0002P,49,Male,Hispanic,6.6,4.4,40
2,HUPA0003P,64,Male,Black,5.3,5.2,70
3,HUPA0004P,34,Female,Native American,5.2,6.9,60
4,HUPA0005P,49,Male,Native American,5.8,7.9,30

In [11]:
df_HUPA = pd.read_csv("Team2_PyQueens_Final_Cleaned_File.csv")
df_HUPA.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0

In [15]:
merged_df = pd.merge(df_slp, df_HUPA, on="Patient_Id", how="right")
merged_df

,Patient_Id,Age,Gender,Race,Average_Sleep_Duration_(Hrs),Sleep_Quality_(1-10),%_With_Sleep_Disturbances,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,34.0,Male,Other,6.3,4.5,80.0,2018-06-13T18:40:00,332.00,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,34.0,Male,Other,6.3,4.5,80.0,2018-06-13T18:45:00,326.00,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,34.0,Male,Other,6.3,4.5,80.0,2018-06-13T18:50:00,330.00,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,34.0,Male,Other,6.3,4.5,80.0,2018-06-13T18:55:00,324.00,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,34.0,Male,Other,6.3,4.5,80.0,2018-06-13T19:00:00,306.00,5.15,92.50,0.0,0.08,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309387,HUPA0028P,62.0,Male,Black,5.1,7.9,30.0,2022-05-18 11:55:00,109.33,10.79,104.17,0.0,0.00,0.0,0.0
309388,HUPA0028P,62.0,Male,Black,5.1,7.9,30.0,2022-05-18 12:00:00,114.00,9.80,103.44,0.0,0.00,0.0,0.0
309389,HUPA0028P,62.0,Male,Black,5.1,7.9,30.0,2022-05-18 12:05:00,118.67,5.67,95.54,0.0,0.00,0.0,0.0
309390,HUPA0028P,62.0,Male,Black,5.1,7.9,30.0,2022-05-18 12:10:00,123.33,5.58,91.38,0.0,0.00,0.0,0.0
309391,HUPA0028P,62.0,Male,Black,5.1,7.9,30.0,2022-05-18 12:15:00,128.00,5.58,99.26,0.0,0.00,0.0,0.0

In [18]:
unique_ids = df_HUPA["Patient_Id"].unique()
unique_ids

array(['HUPA0001P', 'HUPA0002P', 'HUPA0003P', 'HUPA0004P', 'HUPA0005P',
       'HUPA0006P', 'HUPA0007P', 'HUPA0009P', 'HUPA0010P', 'HUPA0018P',
       'HUPA0019P', 'HUPA0020P', 'HUPA0021P', 'HUPA0022P', 'HUPA0023P',
       'HUPA011P', 'HUPA014P', 'HUPA015P', 'HUPA016P', 'HUPA017P',
       'HUPA0024P', 'HUPA0025P', 'HUPA0026P', 'HUPA0027P', 'HUPA0028P'],
      dtype=object)

In [1]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Final cleaned csv files\Final cleaned csv files\Team2_PyQueens_Merged_Final.csv"
)

print("Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)
print("\nFirst 3 rows:")
df.head(3)

Shape: (309392, 15)

Data Types:
Patient_Id                       object
Time                             object
Glucose                         float64
Calories                        float64
Heart_Rate                      float64
Steps                           float64
Basal_Rate                      float64
Bolus_Volume_Delivered          float64
Carb_Input                      float64
Age                               int64
Gender                           object
Race                             object
Average Sleep Duration (hrs)    float64
Sleep Quality (1-10)            float64
% with Sleep Disturbances         int64
dtype: object

First 3 rows:

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input,Age,Gender,Race,Average Sleep Duration (hrs),Sleep Quality (1-10),% with Sleep Disturbances
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0,34,Male,Other,6.3,4.5,80
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0,34,Male,Other,6.3,4.5,80
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0,34,Male,Other,6.3,4.5,80

In [2]:
# ── Fix Data Types ────────────────────────────────────────────────────────────
df['Time']     = pd.to_datetime(df['Time'], format='mixed')
df['Gender']   = df['Gender'].astype('category')
df['Race']     = df['Race'].astype('category')
df['Patient_Id'] = df['Patient_Id'].astype('string')

# Numeric columns — ensure float64
float_cols = [
    'Glucose', 'Calories', 'Heart_Rate', 'Steps',
    'Basal_Rate', 'Bolus_Volume_Delivered', 'Carb_Input',
    'Average Sleep Duration (hrs)', 'Sleep Quality (1-10)'
]
df[float_cols] = df[float_cols].astype(float)

# Integer columns
df['Age']                       = df['Age'].astype(int)
df['% with Sleep Disturbances'] = df['% with Sleep Disturbances'].astype(int)

# ── Verify ────────────────────────────────────────────────────────────────────
print("Updated Data Types:")
print(df.dtypes)

Updated Data Types:
Patient_Id                      string[python]
Time                            datetime64[ns]
Glucose                                float64
Calories                               float64
Heart_Rate                             float64
Steps                                  float64
Basal_Rate                             float64
Bolus_Volume_Delivered                 float64
Carb_Input                             float64
Age                                      int64
Gender                                category
Race                                  category
Average Sleep Duration (hrs)           float64
Sleep Quality (1-10)                   float64
% with Sleep Disturbances                int64
dtype: object

In [3]:
import pandas as pd

# ── Step 1: Load both files ──
df_main = pd.read_csv(r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Final cleaned csv files\Final cleaned csv files\Team2_PyQueens_Final_Cleaned_File.csv")

df_demo = pd.read_csv(r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Final cleaned csv files\Final cleaned csv files\T1DM_patient_sleep_demographics_with_race.csv")

print("File 1 shape :", df_main.shape)
print("File 1 columns:", list(df_main.columns))
print("\nFile 2 shape :", df_demo.shape)
print("File 2 columns:", list(df_demo.columns))

# ── Step 2: Standardize Patient ID column name ──
df_demo.rename(columns={'Patient_ID': 'Patient_Id'}, inplace=True)

# ── Step 3: Merge on Patient_Id (many-to-one) ──
# df_main has 309392 rows (sensor readings)
# df_demo has 25 rows (one per patient)
# Each sensor row gets the demographic info of that patient
merged_df = pd.merge(df_main, df_demo, on='Patient_Id', how='left')

# ── Step 4: Validate merge ──
print(f"\n✅ Merged DataFrame:")
print(f"   Shape          : {merged_df.shape[0]} rows × {merged_df.shape[1]} columns")
print(f"   Total Patients : {merged_df['Patient_Id'].nunique()}")
print(f"   Columns        : {list(merged_df.columns)}")
print(f"   Missing after merge: {merged_df.isnull().sum().sum()}")
print(f"\nSample:")
print(merged_df[['Patient_Id','Time','Glucose','Steps','Age','Gender',
                  'Average Sleep Duration (hrs)','Sleep Quality (1-10)']].head(5))

# ── Step 5: Save merged file ──
output_path = r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Final cleaned csv files\Final cleaned csv files\Team2_PyQueens_Merged_Final.csv"

merged_df.to_csv(output_path, index=False)
print(f"\n✅ Merged file saved as: Team2_PyQueens_Merged_Final.csv")
print(f"   Rows    : {len(merged_df)}")
print(f"   Columns : {merged_df.shape[1]}")

File 1 shape : (309392, 9)
File 1 columns: ['Patient_Id', 'Time', 'Glucose', 'Calories', 'Heart_Rate', 'Steps', 'Basal_Rate', 'Bolus_Volume_Delivered', 'Carb_Input']

File 2 shape : (25, 7)
File 2 columns: ['Patient_ID', 'Age', 'Gender', 'Race', 'Average Sleep Duration (hrs)', 'Sleep Quality (1-10)', '% with Sleep Disturbances']

✅ Merged DataFrame:
   Shape          : 309392 rows × 15 columns
   Total Patients : 25
   Columns        : ['Patient_Id', 'Time', 'Glucose', 'Calories', 'Heart_Rate', 'Steps', 'Basal_Rate', 'Bolus_Volume_Delivered', 'Carb_Input', 'Age', 'Gender', 'Race', 'Average Sleep Duration (hrs)', 'Sleep Quality (1-10)', '% with Sleep Disturbances']
   Missing after merge: 0

Sample:
  Patient_Id                 Time  Glucose  Steps  Age Gender  \
0  HUPA0001P  2018-06-13T18:40:00    332.0   34.0   34   Male
1  HUPA0001P  2018-06-13T18:45:00    326.0    0.0   34   Male
2  HUPA0001P  2018-06-13T18:50:00    330.0    0.0   34   Male
3  HUPA0001P  2018-06-13T18:55:00    324.0   20.0   34   Male
4  HUPA0001P  2018-06-13T19:00:00    306.0    0.0   34   Male

   Average Sleep Duration (hrs)  Sleep Quality (1-10)
0                           6.3                   4.5
1                           6.3                   4.5
2                           6.3                   4.5
3                           6.3                   4.5
4                           6.3                   4.5

✅ Merged file saved as: Team2_PyQueens_Merged_Final.csv
   Rows    : 309392
   Columns : 15