# <h1 align="center">Data Preprocessing - Data Cleaning</h1>

## Patiend ID - HUPA0001P,HUPA0002P,HUPA0003P,HUPA0004P,HUPA0005P

In [2]:
import pandas as pd
import glob
import os

cgm_5files_mv = glob.glob("C:/python_hackathon/HUPA-UC Diabetes Dataset-20250820T010637Z-1-001/HUPA-UC Diabetes Dataset/CGM5_MV/*.csv")

dfs = []
for file in cgm_5files_mv :
    if os.path.isfile(file):
        df = pd.read_csv(file, sep=';')
        df['patient_id'] = os.path.basename(file).replace('.csv', '')
        dfs.append(df)


df_CGM5_MV= pd.concat(dfs, ignore_index=True)

# Move patient_id to first column
cols = ['patient_id'] + [col for col in df_CGM5_MV.columns if col != 'patient_id']
df_CGM5_MV = df_CGM5_MV[cols]

df_CGM5_MV

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.35950,82.322835,34.0,0.091667,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.72800,83.740157,0.0,0.091667,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.74950,80.525180,0.0,0.091667,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.35950,89.129032,20.0,0.091667,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15200,92.495652,0.0,0.075000,0.0,0.0
...,...,...,...,...,...,...,...,...,...
18084,HUPA0005P,2018-07-22T23:25:00,76.5,4.26350,83.140496,0.0,0.075000,0.0,0.0
18085,HUPA0005P,2018-07-22T23:30:00,57.0,4.26350,83.041667,0.0,0.075000,0.0,0.0
18086,HUPA0005P,2018-07-22T23:35:00,53.0,4.26350,79.071429,0.0,0.075000,0.0,0.0
18087,HUPA0005P,2018-07-22T23:40:00,49.0,4.26350,82.910714,0.0,0.075000,0.0,0.0
18088,HUPA0005P,2018-07-22T23:45:00,45.0,5.54255,82.250000,6.0,0.075000,0.0,0.0

### Just we import the dataset into csv files to start  the data cleaning process to find the meaningful insights.

In [3]:
df_CGM5_MV[df_CGM5_MV.duplicated(subset="patient_id", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="time", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="glucose", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="heart_rate", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="steps", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="basal_rate", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="bolus_volume_delivered", keep=False)]
df_CGM5_MV[df_CGM5_MV.duplicated(subset="carb_input", keep=False)]

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.35950,82.322835,34.0,0.091667,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.72800,83.740157,0.0,0.091667,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.74950,80.525180,0.0,0.091667,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.35950,89.129032,20.0,0.091667,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15200,92.495652,0.0,0.075000,0.0,0.0
...,...,...,...,...,...,...,...,...,...
18084,HUPA0005P,2018-07-22T23:25:00,76.5,4.26350,83.140496,0.0,0.075000,0.0,0.0
18085,HUPA0005P,2018-07-22T23:30:00,57.0,4.26350,83.041667,0.0,0.075000,0.0,0.0
18086,HUPA0005P,2018-07-22T23:35:00,53.0,4.26350,79.071429,0.0,0.075000,0.0,0.0
18087,HUPA0005P,2018-07-22T23:40:00,49.0,4.26350,82.910714,0.0,0.075000,0.0,0.0
18088,HUPA0005P,2018-07-22T23:45:00,45.0,5.54255,82.250000,6.0,0.075000,0.0,0.0

### We are finding duplicates here, because duplicates cause may wrong decision.In analytics, duplicates can inflate totals and wrong KPIs,wron aggregation, it affect the data quality.

In [5]:
df_CGM5_MV.columns = df_CGM5_MV.columns.str.title()

In [6]:
df_CGM5_MV.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.3595,82.322835,34.0,0.091667,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.7280,83.740157,0.0,0.091667,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.7495,80.525180,0.0,0.091667,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.3595,89.129032,20.0,0.091667,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.1520,92.495652,0.0,0.075000,0.0,0.0

### Using tile case its mandatory for column name to read dataset in analytics. looks good in power bi,excel,github.

In [7]:
df_CGM5_MV = df_CGM5_MV.round(2)

In [8]:
df_CGM5_MV.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0

### Here we are rounding two decimals between glucose, calories,heart-rate,steps,basal_rate,Bolus_volume_deliverd,carb_inputs,its not  just for  cleaning the data. Its making the data usable, readable,consistent,and meaningful

In [9]:
df_CGM5_MV.isnull().values.any()

np.False_

### we use isnull() to detect missing values in the dataset, because missing values cause major problems in the datait break the calculation, when performing visualization. so if you have null in your column we can drop , fill or interpolate them.

In [13]:
df_CGM5_MV[df_CGM5_MV['Glucose'] > 400]

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
2692,HUPA0001P,2018-06-23T03:00:00,401.00,4.03,76.95,0.0,0.05,0.0,0.0
2698,HUPA0001P,2018-06-23T03:30:00,430.00,4.03,73.78,0.0,0.05,0.0,0.0
2701,HUPA0001P,2018-06-23T03:45:00,418.00,4.03,70.07,0.0,0.05,0.0,0.0
2704,HUPA0001P,2018-06-23T04:00:00,430.00,4.03,75.11,0.0,0.05,0.0,0.0
2707,HUPA0001P,2018-06-23T04:15:00,444.00,4.11,76.34,0.0,0.05,0.5,0.0
2710,HUPA0001P,2018-06-23T04:30:00,439.00,11.35,92.42,83.0,0.05,0.0,0.0
2713,HUPA0001P,2018-06-23T04:45:00,429.00,9.98,81.58,101.0,0.05,0.0,0.0
2716,HUPA0001P,2018-06-23T05:00:00,427.00,4.03,66.69,0.0,0.04,0.0,0.0
11264,HUPA0004P,2018-07-10T09:35:00,403.67,12.30,90.00,13.0,0.07,0.0,0.0
11265,HUPA0004P,2018-07-10T09:40:00,407.33,7.91,89.13,0.0,0.07,0.0,0.0
11266,HUPA0004P,2018-07-10T09:45:00,411.00,9.79,87.66,0.0,0.07,0.0,0.0
11267,HUPA0004P,2018-07-10T09:50:00,409.67,9.92,87.41,5.0,0.07,0.0,0.0
11268,HUPA0004P,2018-07-10T09:55:00,408.33,7.78,87.70,0.0,0.07,0.0,0.0
11269,HUPA0004P,2018-07-10T10:00:00,407.00,7.53,89.50,0.0,0.05,0.0,0.0
11270,HUPA0004P,2018-07-10T10:05:00,404.33,13.68,97.20,41.0,0.05,0.0,0.0
11271,HUPA0004P,2018-07-10T10:10:00,401.67,8.03,89.79,0.0,0.05,0.0,0.0
13062,HUPA0004P,2018-07-16T15:25:00,402.00,8.66,74.14,0.0,0.08,0.0,0.0
13063,HUPA0004P,2018-07-16T15:30:00,406.00,10.29,74.13,54.0,0.08,0.0,0.0
13399,HUPA0004P,2018-07-17T19:30:00,403.00,11.30,72.40,11.0,0.11,0.0,0.0

### I check for glucose > 400 to identify the extreme outliers. These values may sensor errors or true hyperglycemia events.It helps to ensure the data quality before analysis,visualization or data modeling.

In [14]:
df_CGM5_MV[df_CGM5_MV['Glucose'] < 40]

Empty DataFrame
Columns: [Patient_Id, Time, Glucose, Calories, Heart_Rate, Steps, Basal_Rate, Bolus_Volume_Delivered, Carb_Input]
Index: []

### Same here also we check the condition glucose <40 satisfy the above condition, because it missing calibration,sensor dropouts,data corruption, possible hypoglycemia.so checking this condition help to ensure dataset is medically meaningfuland clean.

In [15]:
df_CGM5_MV['Glucose_Outlier'] = (df_CGM5_MV['Glucose'] < 40) | (df_CGM5_MV['Glucose'] > 400)

In [16]:
df_CGM5_MV.head()

,Patient_Id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input,Glucose_Outlier
0,HUPA0001P,2018-06-13T18:40:00,332.0,6.36,82.32,34.0,0.09,0.0,0.0,False
1,HUPA0001P,2018-06-13T18:45:00,326.0,7.73,83.74,0.0,0.09,0.0,0.0,False
2,HUPA0001P,2018-06-13T18:50:00,330.0,4.75,80.53,0.0,0.09,0.0,0.0,False
3,HUPA0001P,2018-06-13T18:55:00,324.0,6.36,89.13,20.0,0.09,0.0,0.0,False
4,HUPA0001P,2018-06-13T19:00:00,306.0,5.15,92.50,0.0,0.08,0.0,0.0,False

### We dont always want to delete or change outliers. In medical dataset evey value is important even one extremes. So instead of removing we flag them. A flag is simply true/ false indicator mark rows needing attention.

In [20]:
df_CGM5_MV.to_csv("cleaned_CGM5_MV.csv", index=False)

In [21]:
df_CGM5_MV.to_csv(r"C:/python_hackathon/cleaned_CGM5_MV.csv", index=False)

### Here once done cleaning process , we import the cleaned data in to the flie#

## Patient ID - HUPA0006P, HUPA0007P, HUPA0009P, HUPA0010P, HUPA0018P

In [6]:
# ============================================================
# Import Libraries
# ============================================================
import pandas as pd
import numpy as np

In [7]:
import pandas as pd
import glob
import os

# Get CSV files from the folder
files_abi = glob.glob(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Abirami\MY_FILES_ABI\*.csv"
)

# Add patient_id column & merge all files
dfs = []

for file in files_abi:
    if os.path.isfile(file):
        df = pd.read_csv(file, sep=';')
        df['patient_id'] = os.path.basename(file).replace('.csv', '')
        dfs.append(df)

df_CGM5_ABI = pd.concat(dfs, ignore_index=True)

# Move patient_id to first column
cols = ['patient_id'] + [col for col in df_CGM5_ABI.columns if col != 'patient_id']
df_CGM5_ABI = df_CGM5_ABI[cols]

df_CGM5_ABI

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0006P,2018-07-09T15:45:00,109.000000,11.23939,70.769231,0.0,0.075000,0.0,0.0
1,HUPA0006P,2018-07-09T15:50:00,107.666667,8.11090,70.189655,5.0,0.075000,0.0,0.0
2,HUPA0006P,2018-07-09T15:55:00,106.333333,6.48872,70.170940,0.0,0.075000,0.0,0.0
3,HUPA0006P,2018-07-09T16:00:00,105.000000,7.06807,72.368421,0.0,0.060833,0.0,0.0
4,HUPA0006P,2018-07-09T16:05:00,122.333333,9.61721,68.219298,6.0,0.060833,0.0,10.0
...,...,...,...,...,...,...,...,...,...
16825,HUPA0018P,2019-07-16T23:25:00,180.333333,6.56343,85.634328,0.0,0.000000,0.0,0.0
16826,HUPA0018P,2019-07-16T23:30:00,188.000000,4.94505,85.459259,0.0,0.000000,0.0,0.0
16827,HUPA0018P,2019-07-16T23:35:00,194.333333,5.12487,84.325581,0.0,0.000000,0.0,0.0
16828,HUPA0018P,2019-07-16T23:40:00,200.666667,9.35064,85.873950,0.0,0.000000,0.0,0.0
16829,HUPA0018P,2019-07-16T23:45:00,207.000000,5.39460,85.753846,0.0,0.000000,0.0,0.0

In [8]:
# ============================================================
#  CHECK: Duplicates
# ============================================================
print("Full duplicate rows:", df_CGM5_ABI.duplicated().sum())
print("Duplicate timestamps per patient:")
print(df_CGM5_ABI.duplicated(subset=['patient_id', 'time']).sum())

Full duplicate rows: 0
Duplicate timestamps per patient:
0

####  Ensured every timestamp per patient is unique, giving accurate time-series analysis.Averages, totals, and trend lines would be distorted by repeated data points.

In [9]:
# ============================================================
#  CHECK: Data Types
# ============================================================
print(df_CGM5_ABI.dtypes)

patient_id                 object
time                       object
glucose                   float64
calories                  float64
heart_rate                float64
steps                     float64
basal_rate                float64
bolus_volume_delivered    float64
carb_input                float64
dtype: object

In [11]:
# FIX: Data Types
df_CGM5_ABI['time'] = pd.to_datetime(df_CGM5_ABI['time'])

num_cols = ['glucose', 'calories', 'heart_rate', 'steps',
            'basal_rate', 'bolus_volume_delivered', 'carb_input']
df_CGM5_ABI[num_cols] = df_CGM5_ABI[num_cols].astype(float)

print("After fix:\n", df_CGM5_ABI.dtypes)

After fix:
 patient_id                        object
time                      datetime64[ns]
glucose                          float64
calories                         float64
heart_rate                       float64
steps                            float64
basal_rate                       float64
bolus_volume_delivered           float64
carb_input                       float64
dtype: object

### The 'Time' column was loaded as plain text and numeric columns had inconsistent types, which prevents any time-based operations or mathematical calculations.Correct types allow sorting by time, calculating time differences, and performing accurate numeric aggregations.Operations like groupby time, plotting trends, or computing mean glucose would throw errors or produce wrong results.¶

In [12]:
# ============================================================
# CHECK: Missing / Null Values
# ============================================================
print("Null values per column:")
print(df_CGM5_ABI.isnull().sum())
print("\nTotal nulls:", df_CGM5_ABI.isnull().sum().sum())

# Check null % per column
print("\nNull percentage:")
print((df_CGM5_ABI.isnull().sum() / len(df_CGM5_ABI) * 100).round(2))

Null values per column:
patient_id                0
time                      0
glucose                   0
calories                  0
heart_rate                0
steps                     0
basal_rate                0
bolus_volume_delivered    0
carb_input                0
dtype: int64

Total nulls: 0

Null percentage:
patient_id                0.0
time                      0.0
glucose                   0.0
calories                  0.0
heart_rate                0.0
steps                     0.0
basal_rate                0.0
bolus_volume_delivered    0.0
carb_input                0.0
dtype: float64

#### Confirming zero nulls gives confidence that the dataset is complete and no imputation is needed.Any null left in glucose or heart_rate would produce NaN results in all downstream calculations involving those columns.

In [13]:
# ============================================================
# CHECK: Trim & Clean Text
# ============================================================
# Check whitespace in time column
print("Whitespace in time:")
print(df_CGM5_ABI['time'].astype(str).str.contains(r'^\s|\s$').sum())

# Check column name whitespace
print("\nColumn names:")
print([f"'{c}'" for c in df_CGM5_ABI.columns])

# Check patient_id formatting consistency
print("\nUnique patient IDs:")
print(df_CGM5_ABI['patient_id'].unique())

Whitespace in time:
0

Column names:
["'patient_id'", "'time'", "'glucose'", "'calories'", "'heart_rate'", "'steps'", "'basal_rate'", "'bolus_volume_delivered'", "'carb_input'"]

Unique patient IDs:
['HUPA0006P' 'HUPA0007P' 'HUPA0009P' 'HUPA0010P' 'HUPA0018P']

In [14]:
# ============================================================
# Check whitespace in any row values — df_CGM5_ABI
# ============================================================

print("df_CGM5_ABI — Whitespace check in all columns:")
for col in df_CGM5_ABI.columns:
    if df_CGM5_ABI[col].dtype == object:  # only text columns
        count = df_CGM5_ABI[col].astype(str).str.contains(r'^\s|\s$').sum()
        print(f"  {col}: {count} rows with whitespace")

df_CGM5_ABI — Whitespace check in all columns:
  patient_id: 0 rows with whitespace

### No trimming or cleaning required as the data is clean

In [15]:
# ============================================================
# CHECK: Standardize Values
# ============================================================
# Check sort order per patient
print("Is sorted by patient + time:")
sorted_check = df_CGM5_ABI.groupby('patient_id')['time'].is_monotonic_increasing
print(sorted_check)

# Check decimal precision
print("\nSample values:")
print(df_CGM5_ABI[num_cols].head(3))

Is sorted by patient + time:
patient_id
HUPA0006P    True
HUPA0007P    True
HUPA0009P    True
HUPA0010P    True
HUPA0018P    True
Name: time, dtype: bool

Sample values:
      glucose  calories  heart_rate  steps  basal_rate  \
0  109.000000  11.23939   70.769231    0.0       0.075
1  107.666667   8.11090   70.189655    5.0       0.075
2  106.333333   6.48872   70.170940    0.0       0.075

   bolus_volume_delivered  carb_input
0                     0.0         0.0
1                     0.0         0.0
2                     0.0         0.0

In [16]:
# FIX: Round to 2 decimal places
num_cols = ['glucose', 'calories', 'heart_rate', 'steps',
            'basal_rate', 'bolus_volume_delivered', 'carb_input']

df_CGM5_ABI[num_cols] = df_CGM5_ABI[num_cols].round(2)

print("After rounding:")
print(df_CGM5_ABI[num_cols].head(3))
df_CGM5_ABI.head(3)

After rounding:
   glucose  calories  heart_rate  steps  basal_rate  bolus_volume_delivered  \
0   109.00     11.24       70.77    0.0        0.08                     0.0
1   107.67      8.11       70.19    5.0        0.08                     0.0
2   106.33      6.49       70.17    0.0        0.08                     0.0

   carb_input
0         0.0
1         0.0
2         0.0

,patient_id,time,glucose,calories,heart_rate,steps,basal_rate,bolus_volume_delivered,carb_input
0,HUPA0006P,2018-07-09 15:45:00,109.00,11.24,70.77,0.0,0.08,0.0,0.0
1,HUPA0006P,2018-07-09 15:50:00,107.67,8.11,70.19,5.0,0.08,0.0,0.0
2,HUPA0006P,2018-07-09 15:55:00,106.33,6.49,70.17,0.0,0.08,0.0,0.0

#### Data was not guaranteed to be in chronological order after merging, and numeric columns had up to 9 decimal places making the data inconsistent and hard to read.Sorting ensures time-series operations like diff() and interpolation work correctly. Rounding to 2 decimal places standardises precision across all patients.If it is not performed then Time-based calculations like glucose trend detection or interval checks would produce incorrect results on unsorted data. Excessive decimals would cause inconsistency when comparing values across patients.

In [18]:
# ============================================================
# CHECK: Column Names
# ============================================================
print("Current column names:")
print(df_CGM5_ABI.columns.tolist())

Current column names:
['patient_id', 'time', 'glucose', 'calories', 'heart_rate', 'steps', 'basal_rate', 'bolus_volume_delivered', 'carb_input']

In [19]:
# FIX: Rename Columns
df_CGM5_ABI = df_CGM5_ABI.rename(columns={
    'time'                   : 'Time',
    'glucose'                : 'Glucose',
    'calories'               : 'Calories',
    'heart_rate'             : 'Heart_Rate',
    'steps'                  : 'Steps',
    'basal_rate'             : 'Basal_Rate',
    'bolus_volume_delivered' : 'Bolus_Volume_Delivered',
    'carb_input'             : 'Carb_Input'
    
})
print("Renamed:", df_CGM5_ABI.columns.tolist())

Renamed: ['patient_id', 'Time', 'Glucose', 'Calories', 'Heart_Rate', 'Steps', 'Basal_Rate', 'Bolus_Volume_Delivered', 'Carb_Input']

#### Original column names like 'bolus_volume_delivered' were lowercase with underscores and lacked units, making them harder to read in reports and dashboards.Descriptive, consistently capitalised column names improve readability in Visualizations.The raw technical names that are unclear to non-technical stakeholders.

In [20]:
# ============================================================
# Inconsistent Categories
# ============================================================
# Validate zero distributions per patient
print("Zero % per column per patient:")
zero_pct = (
    df_CGM5_ABI.groupby('patient_id')[df_CGM5_ABI.columns[2:]]
    .apply(lambda x: (x == 0).sum() / len(x) * 100)
    .round(1)
)
print(zero_pct)

Zero % per column per patient:
            Glucose  Calories  Heart_Rate  Steps  Basal_Rate  \
patient_id
HUPA0006P       0.0       0.0         0.0   67.8         1.8
HUPA0007P       0.0       0.0         0.0   59.0         6.6
HUPA0009P       0.0       0.0         0.0   58.8         1.4
HUPA0010P       0.0       0.0         0.0   53.4         3.3
HUPA0018P       0.0       0.0         0.0   61.3       100.0

            Bolus_Volume_Delivered  Carb_Input
patient_id
HUPA0006P                     98.0        98.4
HUPA0007P                     97.7        97.9
HUPA0009P                     98.3        98.8
HUPA0010P                     97.4        98.6
HUPA0018P                    100.0       100.0

#### Confirming no categorical columns exist and that zeros are clinically valid prevents unnecessary data modification.Incorrectly treating valid zeros as missing data and replacing them would corrupt clinically meaningful readings like no bolus delivered or no food logged.

In [21]:
# ============================================================
# CHECK: Validate Relationships / Keys
# ============================================================
# Timestamp uniqueness per patient
dup_check = df_CGM5_ABI.duplicated(subset=['patient_id', 'Time']).sum()
print("Duplicate patient+timestamp combinations:", dup_check)

# Row count per patient
print("\nRows per patient:")
print(df_CGM5_ABI['patient_id'].value_counts())

# Time interval check per patient
print("\nTime interval check (should all be 5 min):")
df_CGM5_ABI_sorted = df_CGM5_ABI.sort_values(['patient_id', 'Time'])
intervals = (
    df_CGM5_ABI_sorted.groupby('patient_id')['Time']
    .diff()
    .dropna()
    .value_counts()
)
print(intervals.head(10))

Duplicate patient+timestamp combinations: 0

Rows per patient:
patient_id
HUPA0018P    3895
HUPA0007P    3857
HUPA0009P    3812
HUPA0010P    2976
HUPA0006P    2290
Name: count, dtype: int64

Time interval check (should all be 5 min):
Time
0 days 00:05:00    16825
Name: count, dtype: int64

#### As a time-series dataset, each patient must have unique timestamps and consistent 5-minute intervals. Any break in this structure affects trend analysis and machine learning models.Confirming the dataset is structurally sound  no duplicate keys, no missing intervals, and correct row counts per patient after merging.Duplicate timestamps would cause incorrect joins and aggregations. Irregular time intervals would break any model or visualisation that assumes evenly spaced readings.

In [22]:
# ============================================================
#  Final Summary
# ============================================================
print("Final Shape:", df_CGM5_ABI.shape)
print("\nData Types:\n", df_CGM5_ABI.dtypes)
print("\nNull Values:\n", df_CGM5_ABI.isnull().sum())
print("\nPatients:", df_CGM5_ABI['patient_id'].unique())
df_CGM5_ABI.describe()

Final Shape: (16830, 9)

Data Types:
 patient_id                        object
Time                      datetime64[ns]
Glucose                          float64
Calories                         float64
Heart_Rate                       float64
Steps                            float64
Basal_Rate                       float64
Bolus_Volume_Delivered           float64
Carb_Input                       float64
dtype: object

Null Values:
 patient_id                0
Time                      0
Glucose                   0
Calories                  0
Heart_Rate                0
Steps                     0
Basal_Rate                0
Bolus_Volume_Delivered    0
Carb_Input                0
dtype: int64

Patients: ['HUPA0006P' 'HUPA0007P' 'HUPA0009P' 'HUPA0010P' 'HUPA0018P']

,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
count,16830,16830.000000,16830.000000,16830.000000,16830.000000,16830.000000,16830.000000,16830.000000
mean,2018-11-29 22:16:18.110516992,163.323878,9.380301,76.121116,41.813428,0.060240,0.054743,0.038963
min,2018-07-09 15:45:00,40.000000,4.070000,41.420000,0.000000,0.000000,0.000000,0.000000
25%,2018-09-22 22:21:15,107.330000,4.680000,65.190000,0.000000,0.000000,0.000000,0.000000
50%,2018-09-30 05:40:00,158.330000,6.930000,76.745000,0.000000,0.070000,0.000000,0.000000
75%,2018-11-16 21:28:45,214.000000,11.070000,84.477500,43.000000,0.090000,0.000000,0.000000
max,2019-07-16 23:45:00,438.000000,78.860000,166.330000,682.000000,0.150000,13.300000,10.000000
std,NaN,71.129606,7.285117,14.450585,86.712816,0.039456,0.567493,0.435361

In [23]:
# ============================================================
#  Moving the patient id as first column
# ============================================================
cols = ['patient_id'] + [col for col in df_CGM5_ABI.columns if col != 'patient_id']
df_CGM5_ABI = df_CGM5_ABI[cols]

print(df_CGM5_ABI.columns.tolist())
df_CGM5_ABI.head()

['patient_id', 'Time', 'Glucose', 'Calories', 'Heart_Rate', 'Steps', 'Basal_Rate', 'Bolus_Volume_Delivered', 'Carb_Input']

,patient_id,Time,Glucose,Calories,Heart_Rate,Steps,Basal_Rate,Bolus_Volume_Delivered,Carb_Input
0,HUPA0006P,2018-07-09 15:45:00,109.00,11.24,70.77,0.0,0.08,0.0,0.0
1,HUPA0006P,2018-07-09 15:50:00,107.67,8.11,70.19,5.0,0.08,0.0,0.0
2,HUPA0006P,2018-07-09 15:55:00,106.33,6.49,70.17,0.0,0.08,0.0,0.0
3,HUPA0006P,2018-07-09 16:00:00,105.00,7.07,72.37,0.0,0.06,0.0,0.0
4,HUPA0006P,2018-07-09 16:05:00,122.33,9.62,68.22,6.0,0.06,0.0,10.0

In [24]:
# ============================================================
# Save Cleaned File
# ============================================================
df_CGM5_ABI.to_csv(
    r"C:\Users\vidya\OneDrive\Desktop\DATA ANALYST\NUMPY NINJA\GITHUB\Team2_-PyQueens_-Python-Hackathon-_MAY-2026\Abirami\CGM5_ABI_cleaned.csv",
    index=False
)
print("Saved successfully!")

Saved successfully!

## Patient ID - HUPA0011P, HUPA0014P, HUPA0015P, HUPA0016P, HUPA0017P